DROP SEQUENCE CSM_APPLICATI_APPLICATION__SEQ;

DROP TABLE CSM_APPLICATION CASCADE CONSTRAINTS
;

DROP SEQUENCE CSM_GROUP_GROUP_ID_SEQ;

DROP TABLE CSM_GROUP CASCADE CONSTRAINTS
;

DROP TRIGGER SET_CSM_PG_PE_PG_PE_ID;

DROP TRIGGER SET_CSM_PG_PE_UPDATE_DATE;

DROP SEQUENCE CSM_PG_PE_PG_PE_ID_SEQ;

DROP TABLE CSM_PG_PE CASCADE CONSTRAINTS
;

DROP SEQUENCE CSM_PRIVILEGE_PRIVILEGE_ID_SEQ;

DROP TABLE CSM_PRIVILEGE CASCADE CONSTRAINTS
;

DROP SEQUENCE CSM_PROTECTIO_PROTECTION_E_SEQ;

DROP TABLE CSM_PROTECTION_ELEMENT CASCADE CONSTRAINTS
;

DROP SEQUENCE CSM_PROTECTIO_PROTECTION_G_SEQ;

DROP TABLE CSM_PROTECTION_GROUP CASCADE CONSTRAINTS
;

DROP SEQUENCE CSM_ROLE_ROLE_ID_SEQ;

DROP TABLE CSM_ROLE CASCADE CONSTRAINTS
;

DROP TRIGGER SET_CSM_ROLE_PRIV_ROLE_PRIVILE;

DROP TRIGGER SET_CSM_ROLE_PRIV_UPDATE_DATE;

DROP SEQUENCE CSM_ROLE_PRIV_ROLE_PRIVILE_SEQ;

DROP TABLE CSM_ROLE_PRIVILEGE CASCADE CONSTRAINTS
;

DROP SEQUENCE CSM_USER_USER_ID_SEQ;

DROP TABLE CSM_USER CASCADE CONSTRAINTS
;

DROP TRIGGER SET_CSM_USER_GROU_USER_GROUP_I;

DROP SEQUENCE CSM_USER_GROU_USER_GROUP_I_SEQ;

DROP TABLE CSM_USER_GROUP CASCADE CONSTRAINTS
;

DROP SEQUENCE CSM_USER_GROU_USER_GROUP_R_SEQ;

DROP TABLE CSM_USER_GROUP_ROLE_PG CASCADE CONSTRAINTS
;

DROP TRIGGER SET_CSM_USER_PE_USER_PROTECTIO;

DROP TRIGGER SET_CSM_USER_PE_UPDATE_DATE;

DROP SEQUENCE CSM_USER_PE_USER_PROTECTIO_SEQ;

DROP TABLE CSM_USER_PE CASCADE CONSTRAINTS
;