package gov.nih.nci.ess.sr.service.safetyreportadvancedquery.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportAdvancedQueryImpl extends SafetyReportAdvancedQueryImplBase {

	
	public SafetyReportAdvancedQueryImpl() throws RemoteException {
		super();
	}
	
  public void getSafetyReportSummaryData() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

