class AddCtcV2Terms extends edu.northwestern.bioinformatics.bering.Migration {
    void up() {
        // Have to break up the inserts so as not to exceed the java max method length
        m0()
        m1()
        m2()
        m3()
        m4()
        m5()
        m6()
        m7()
        m8()
        m9()
        m10()
        m11()
        m12()
        m13()
        m14()
        m15()
        m16()
        m17()
        m18()
        m19()
        m20()
        m21()
        m22()
        m23()
        m24()
        m25()
    }

    void m0() {
        // ALLERGY/IMMUNOLOGY (6 terms)
        insert('ctc_categories', [version_id: 2, id: 201, name: 'ALLERGY/IMMUNOLOGY'], primaryKey: false)
        insert('ctc_terms', [category_id: 201, id: 2001, term: "Allergic reaction/hypersensitivity (including drug fever)", ctep_term: "Hypersensitivity", ctep_code: 10020751], primaryKey: false)
        insert('ctc_terms', [category_id: 201, id: 2002, term: "Allergic rhinitis (including sneezing, nasal stuffiness, postnasal drip)", ctep_term: "Allergic rhinitis", ctep_code: 10001723], primaryKey: false)
        insert('ctc_terms', [category_id: 201, id: 2003, term: "Allergy-Other (Specify,_____)", ctep_term: "Immune system disorder", ctep_code: 10021425, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 201, id: 2004, term: "Autoimmune reaction", ctep_term: "Autoimmune disorder", ctep_code: 10061664], primaryKey: false)
        insert('ctc_terms', [category_id: 201, id: 2005, term: "Serum sickness", ctep_term: "Serum sickness", ctep_code: 10040400], primaryKey: false)
        insert('ctc_terms', [category_id: 201, id: 2006, term: "Vasculitis", ctep_term: "Vasculitis", ctep_code: 10047115], primaryKey: false)
    }

    void m1() {
        // AUDITORY/HEARING (4 terms)
        insert('ctc_categories', [version_id: 2, id: 202, name: 'AUDITORY/HEARING'], primaryKey: false)
        insert('ctc_terms', [category_id: 202, id: 2007, term: "Auditory/Hearing-Other (Specify,_____)", ctep_term: "Ear disorder", ctep_code: 10014004, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 202, id: 2008, term: "External Auditory Canal", ctep_term: "External ear inflammation", ctep_code: 10065837], primaryKey: false)
        insert('ctc_terms', [category_id: 202, id: 2009, term: "Inner ear/hearing", ctep_term: "Hearing loss", ctep_code: 10019246], primaryKey: false)
        insert('ctc_terms', [category_id: 202, id: 2010, term: "Middle ear/hearing", ctep_term: "Middle ear inflammation", ctep_code: 10065838], primaryKey: false)
    }

    void m2() {
        // Appendix IV RTOG/EORTC Late Radiation Morbidity Scoring Scheme (Use for adverse events occurring greater than 90 days after radiation therapy.) (18 terms)
        insert('ctc_categories', [version_id: 2, id: 203, name: 'Appendix IV RTOG/EORTC Late Radiation Morbidity Scoring Scheme (Use for adverse events occurring greater than 90 days after radiation therapy.)'], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2011, term: "Bladder- Late RT Morbidity Scoring", ctep_code: 90004114], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2012, term: "Bone - Late RT Morbidity Scoring", ctep_code: 90004112], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2013, term: "Brain- Late RT Morbidity Scoring", ctep_code: 90004130], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2014, term: "Esophagus- Late RT Morbidity Scoring", ctep_code: 90004128], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2015, term: "Eye- Late RT Morbidity Scoring", ctep_code: 90004104], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2016, term: "Heart- Late RT Morbidity Scoring", ctep_code: 90004116], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2017, term: "Joint- Late RT Morbidity Scoring", ctep_code: 90004126], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2018, term: "Kidney-Late RT Morbidity Scoring", ctep_code: 90004118], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2019, term: "Larynx-Late RT Morbidity Scoring", ctep_code: 90004124], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2020, term: "Liver-Late RT Morbidity Scoring", ctep_code: 90004096], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2021, term: "Lung-Late RT Morbidity Scoring", ctep_code: 90004122], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2022, term: "Mucous membrane-Late RT Morbidity Scoring", ctep_code: 90004098], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2023, term: "Radiation-Other(Specify,_____)", ctep_code: 90004106, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2024, term: "Salivary glands-Late RT Morbidity Scoring", ctep_code: 90004120], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2025, term: "Skin-Late RT Morbidity Scoring", ctep_code: 90004108], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2026, term: "Small/Large intestine-Late RT Morbidity Scoring", ctep_code: 90004110], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2027, term: "Spinal cord-Late RT Morbidity Scoring", ctep_code: 90004100], primaryKey: false)
        insert('ctc_terms', [category_id: 203, id: 2028, term: "Subcutaneous tissue-Late RT Morbidity Scoring", ctep_code: 90004102], primaryKey: false)
    }

    void m3() {
        // Appendix VI BMT Complex/Multicomponent Events (4 terms)
        insert('ctc_categories', [version_id: 2, id: 204, name: 'Appendix VI BMT Complex/Multicomponent Events'], primaryKey: false)
        insert('ctc_terms', [category_id: 204, id: 2029, term: "Failure to engraft", ctep_code: 90004134], primaryKey: false)
        insert('ctc_terms', [category_id: 204, id: 2030, term: "Graft versus host disease", ctep_term: "Graft versus host disease", ctep_code: 10018651], primaryKey: false)
        insert('ctc_terms', [category_id: 204, id: 2031, term: "Stem cell infusion complications", ctep_code: 90004132], primaryKey: false)
        insert('ctc_terms', [category_id: 204, id: 2032, term: "Veno-Occlusive Disease (VOD)", ctep_term: "Venoocclusive disease NOS", ctep_code: 10052612], primaryKey: false)
    }

    void m4() {
        // BLOOD/BONE MARROW (23 terms)
        insert('ctc_categories', [version_id: 2, id: 205, name: 'BLOOD/BONE MARROW'], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2033, term: "Blood/Bone Marrow-Other (Specify,_____)", ctep_term: "Blood disorder", ctep_code: 10061590, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2034, term: "Bone marrow cellularity", ctep_term: "Bone marrow hypocellular", ctep_code: 10048580], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2035, term: "CD4 count", ctep_term: "CD4 lymphocytes decreased", ctep_code: 10007839], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2036, term: "Haptoglobin", ctep_term: "Haptoglobin decreased", ctep_code: 10019150], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2037, term: "Hemoglobin", ctep_term: "Hemoglobin decreased", ctep_code: 10019483], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2038, term: "Hemoglobin for leukemia studies or bone marrow infiltrative/ myelophthisic processes, if specified in the protocol.", ctep_code: 90004010], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2039, term: "Hemolysis (e.g., immune hemolytic anemia, drug related hemolysis, other)", ctep_term: "Hemolysis", ctep_code: 10019491], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2040, term: "Leukocytes (total WBC)", ctep_term: "Leukopenia", ctep_code: 10024384], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2041, term: "Leukocytes (total WBC) for BMT studies, if specified in the protocol.", ctep_code: 90004014], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2042, term: "Leukocytes (total WBC) for pediatric BMT studies (using age, race and sex normal values), if specified in the protocol.", ctep_code: 90004022], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2043, term: "Lymphopenia", ctep_term: "Lymphopenia", ctep_code: 10025327], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2044, term: "Lymphopenia for pediatric BMT studies (using age, race and sex normal values), if specified in the protocol.", ctep_code: 90004024], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2045, term: "Neutrophils/granulocytes (ANC/AGC)", ctep_term: "Neutrophil count decreased", ctep_code: 10029366], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2046, term: "Neutrophils/granulocytes (ANC/AGC) for BMT studies, if specified in the protocol.", ctep_code: 90004006], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2047, term: "Neutrophils/granulocytes (ANC/AGC) for leukemia studies or bone marrow infiltrative/myelophthisic process, if specified in the protocol.", ctep_code: 90004008], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2048, term: "Platelets", ctep_term: "Platelet count decreased", ctep_code: 10035528], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2049, term: "Platelets for BMT studies, if specified in the protocol.", ctep_code: 90004026], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2050, term: "Platelets for leukemia studies or bone marrow infiltrative/myelophthisic process, if specified in the protocol.", ctep_code: 90004020], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2051, term: "Transfusion: Platelets", ctep_term: "Platelet transfusion", ctep_code: 10035543], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2052, term: "Transfusion: Platelets for BMT studies, if specified in the protocol.", ctep_code: 90004004], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2053, term: "Transfusion: pRBCs", ctep_term: "Packed red blood cell transfusion", ctep_code: 10033359], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2054, term: "Transfusion: pRBCs for BMT studies, if specified in the protocol.", ctep_code: 90004016], primaryKey: false)
        insert('ctc_terms', [category_id: 205, id: 2055, term: "Transfusion: pRBCs for pediatric BMT studies, if specified in the protocol.", ctep_code: 90004012], primaryKey: false)
    }

    void m5() {
        // CARDIOVASCULAR (ARRHYTHMIA) (10 terms)
        insert('ctc_categories', [version_id: 2, id: 206, name: 'CARDIOVASCULAR (ARRHYTHMIA)'], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2056, term: "Cardiovascular/Arrhythmia-Other (Specify,_____)", ctep_term: "Arrhythmia", ctep_code: 10003119, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2057, term: "Conduction abnormality/Atrioventricular heart block", ctep_term: "Conduction disorder", ctep_code: 10010276], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2058, term: "Nodal/junctional arrhythmia/dysrhythmia", ctep_term: "Nodal arrhythmia", ctep_code: 10029458], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2059, term: "Palpitations", ctep_term: "Palpitations", ctep_code: 10033557], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2060, term: "Prolonged QTc interval (QTc > 0.48 seconds)", ctep_term: "Electrocardiogram QTc interval prolonged", ctep_code: 10053698], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2061, term: "Sinus bradycardia", ctep_term: "Sinus bradycardia", ctep_code: 10040741], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2062, term: "Sinus tachycardia", ctep_term: "Sinus tachycardia", ctep_code: 10040752], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2063, term: "Supraventricular arrhythmias (SVT/atrial fibrillation/flutter)", ctep_term: "Arrhythmia supraventricular", ctep_code: 10003130], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2064, term: "Vasovagal episode", ctep_term: "Syncope vasovagal", ctep_code: 10042777], primaryKey: false)
        insert('ctc_terms', [category_id: 206, id: 2065, term: "Ventricular arrhythmia (PVCs/bigeminy/trigeminy/ventricular tachycardia)", ctep_term: "Ventricular arrhythmia", ctep_code: 10047281], primaryKey: false)
    }

    void m6() {
        // CARDIOVASCULAR (GENERAL) (16 terms)
        insert('ctc_categories', [version_id: 2, id: 207, name: 'CARDIOVASCULAR (GENERAL)'], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2066, term: "Acute vascular leak syndrome", ctep_term: "Capillary leak syndrome", ctep_code: 10007196], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2067, term: "Cardiac left ventricular function", ctep_term: "Left ventricular failure", ctep_code: 10024119], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2068, term: "Cardiac troponin I (cTnI)", ctep_term: "Cardiac troponin I increased", ctep_code: 10007612], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2069, term: "Cardiac troponin T (cTnT)", ctep_term: "Cardiac troponin T increased", ctep_code: 10007613], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2070, term: "Cardiac-ischemia/infarction", ctep_term: "Myocardial ischemia", ctep_code: 10028601], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2071, term: "Cardiovascular/General-Other (Specify,_____)", ctep_term: "Cardiac disorder", ctep_code: 10061024, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2072, term: "Edema", ctep_term: "Oedema NOS", ctep_code: 10030114], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2073, term: "Hypertension", ctep_term: "Hypertension", ctep_code: 10020772], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2074, term: "Hypotension", ctep_term: "Hypotension", ctep_code: 10021097], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2075, term: "Myocarditis", ctep_term: "Myocarditis", ctep_code: 10028606], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2076, term: "Operative injury of vein/artery", ctep_term: "Intraoperative venous injury", ctep_code: 10065848], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2077, term: "Pericardial effusion/pericarditis", ctep_term: "Pericardial effusion", ctep_code: 10034474], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2078, term: "Peripheral arterial ischemia", ctep_term: "Peripheral ischemia", ctep_code: 10034578], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2079, term: "Phlebitis (superficial)", ctep_term: "Phlebitis superficial", ctep_code: 10034902], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2080, term: "Thrombosis/embolism", ctep_term: "Thrombosis", ctep_code: 10043607], primaryKey: false)
        insert('ctc_terms', [category_id: 207, id: 2081, term: "Visceral arterial ischemia (non-myocardial)", ctep_term: "Visceral arterial ischemia", ctep_code: 10054692], primaryKey: false)
    }

    void m7() {
        // COAGULATION (8 terms)
        insert('ctc_categories', [version_id: 2, id: 208, name: 'COAGULATION'], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2082, term: "Coagulation-Other (Specify,_____)", ctep_term: "Coagulopathy", ctep_code: 10009802, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2083, term: "DIC (disseminated intravascular coagulation)", ctep_term: "Disseminated intravascular coagulation", ctep_code: 10013442], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2084, term: "Fibrinogen", ctep_term: "Fibrinogen decreased", ctep_code: 10016596], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2085, term: "Fibrinogen for leukemia studies or bone marrow infiltrative/myelophthisic process, if specified in the protocol.", ctep_code: 90004034], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2086, term: "Partial thromboplastin time (PTT)", ctep_term: "Activated partial thromboplastin time prolonged", ctep_code: 10000636], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2087, term: "Prothrombin time (PT)", ctep_term: "INR increased", ctep_code: 10022402], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2088, term: "Thrombotic microangiopathy (e.g., thrombotic thrombocytopenic purpura/TTP or hemolytic uremic syndrome/HUS)", ctep_term: "Thrombotic microangiopathy", ctep_code: 10043645], primaryKey: false)
        insert('ctc_terms', [category_id: 208, id: 2089, term: "Thrombotic microangiopathy (e.g., thrombotic thrombocytopenic purpura/TTP or hemolytic uremic syndrome/HUS) for BMT studies, if specified by the protocol.", ctep_code: 90004032], primaryKey: false)
    }

    void m8() {
        // CONSTITUTIONAL SYMPTOMS (8 terms)
        insert('ctc_categories', [version_id: 2, id: 209, name: 'CONSTITUTIONAL SYMPTOMS'], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2090, term: "Constitutional Symptoms-Other (Specify,_____)", ctep_term: "General symptom", ctep_code: 10060891, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2091, term: "Fatigue (lethargy, malaise, asthenia)", ctep_term: "Fatigue", ctep_code: 10016256], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2092, term: "Fever (in the absence of neutropenia, where neutropenia is defined as AGC<1.0 x 10e9/L)", ctep_term: "Fever", ctep_code: 10016558], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2093, term: "Rigors, chills", ctep_term: "Chills", ctep_code: 10008531], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2094, term: "Sweating (diaphoresis)", ctep_term: "Sweating", ctep_code: 10042661], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2095, term: "Weight gain", ctep_term: "Weight gain", ctep_code: 10047896], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2096, term: "Weight gain - Veno-Occlusive Disease (VOD) for BMT studies if specified in the protocol.", ctep_code: 90004036], primaryKey: false)
        insert('ctc_terms', [category_id: 209, id: 2097, term: "Weight loss", ctep_term: "Weight loss", ctep_code: 10047900], primaryKey: false)
    }

    void m9() {
        // DERMATOLOGY/SKIN (20 terms)
        insert('ctc_categories', [version_id: 2, id: 210, name: 'DERMATOLOGY/SKIN'], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2098, term: "Alopecia", ctep_term: "Alopecia", ctep_code: 10001760], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2099, term: "Bruising (in absence of grade 3 or 4 thrombocytopenia)", ctep_term: "Bruising", ctep_code: 10006504], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2100, term: "Dermatology/Skin-Other (Specify,_____)", ctep_term: "Skin disorder", ctep_code: 10040831, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2101, term: "Dry skin", ctep_term: "Dry skin", ctep_code: 10013786], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2102, term: "Erythema multiforme (e.g., Stevens-Johnson syndrome, toxic epidermal necrolysis)", ctep_term: "Erythema multiforme", ctep_code: 10015218], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2103, term: "Flushing", ctep_term: "Flushing", ctep_code: 10016825], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2104, term: "Hand-foot skin reaction", ctep_term: "Hand-and-foot syndrome", ctep_code: 10019126], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2105, term: "Injection site reaction", ctep_term: "Injection site reaction", ctep_code: 10022095], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2106, term: "Nail changes", ctep_term: "Nail disorder", ctep_code: 10028694], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2107, term: "Photosensitivity", ctep_term: "Photosensitivity", ctep_code: 10034966], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2108, term: "Pigmentation changes (e.g., vitiligo)", ctep_term: "Skin discolouration", ctep_code: 10040829], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2109, term: "Pruritus", ctep_term: "Pruritus", ctep_code: 10037087], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2110, term: "Radiation dermatitis", ctep_term: "Dermatitis radiation", ctep_code: 10061103], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2111, term: "Radiation recall reaction (reaction following chemotherapy in the absence of additional radiation therapy that occurs in a previous radiation port)", ctep_term: "Radiation recall reaction (dermatologic)", ctep_code: 10037767], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2112, term: "Rash/dermatitis associated with high-dose chemotherapy or BMT studies.", ctep_code: 90004040], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2113, term: "Rash/desquamation", ctep_term: "Rash desquamating", ctep_code: 10037853], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2114, term: "Rash/desquamation associated with graft versus host disease (GVHD) for BMT studies, if specified in the protocol.", ctep_code: 90004044], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2115, term: "Urticaria (hives, welts, wheals)", ctep_term: "Urticaria", ctep_code: 10046735], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2116, term: "Wound-infectious", ctep_term: "Wound infection", ctep_code: 10048038], primaryKey: false)
        insert('ctc_terms', [category_id: 210, id: 2117, term: "Wound-non-infectious", ctep_term: "Wound dehiscence", ctep_code: 10048031], primaryKey: false)
    }

    void m10() {
        // ENDOCRINE (8 terms)
        insert('ctc_categories', [version_id: 2, id: 211, name: 'ENDOCRINE'], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2118, term: "Cushingoid appearance (e.g., moon face, buffalo hump, centripetal obesity, cutaneous striae)", ctep_term: "Cushingoid", ctep_code: 10011655], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2119, term: "Endocrine-Other (Specify,_____)", ctep_term: "Endocrine disorder", ctep_code: 10014695, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2120, term: "Feminization of male", ctep_term: "Feminization", ctep_code: 10016424], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2121, term: "Gynecomastia", ctep_term: "Gynecomastia", ctep_code: 10018801], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2122, term: "Hot flashes/flushes", ctep_term: "Hot flashes", ctep_code: 10020407], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2123, term: "Hypothyroidism", ctep_term: "Hypothyroidism", ctep_code: 10021114], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2124, term: "Masculinization of female", ctep_term: "Masculinization", ctep_code: 10026859], primaryKey: false)
        insert('ctc_terms', [category_id: 211, id: 2125, term: "SIADH (syndrome of inappropriate antidiuretic hormone)", ctep_term: "ADH abnormal", ctep_code: 10001266], primaryKey: false)
    }

    void m11() {
        // GASTROINTESTINAL (35 terms)
        insert('ctc_categories', [version_id: 2, id: 212, name: 'GASTROINTESTINAL'], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2126, term: "Anorexia", ctep_term: "Anorexia", ctep_code: 10002646], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2127, term: "Ascites (non-malignant)", ctep_term: "Ascites", ctep_code: 10003445], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2128, term: "Colitis", ctep_term: "Colitis", ctep_code: 10009887], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2129, term: "Constipation", ctep_term: "Constipation", ctep_code: 10010774], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2130, term: "Dehydration", ctep_term: "Dehydration", ctep_code: 10012174], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2131, term: "Diarrhea associated with graft versus host disease (GVHD) for BMT studies, if specified in the protocol.", ctep_code: 90004052], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2132, term: "Diarrhea for pediatric BMT studies, if specified in the protocol.", ctep_code: 90004056], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2133, term: "Diarrhea patients with a colostomy", ctep_code: 90004048], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2134, term: "Diarrhea patients without colostomy", ctep_term: "Diarrhea", ctep_code: 10012727], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2135, term: "Duodenal ulcer (requires radiographic or endoscopic documentation)", ctep_term: "Duodenal ulcer", ctep_code: 10013836], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2136, term: "Dyspepsia/heartburn", ctep_term: "Dyspepsia", ctep_code: 10013946], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2137, term: "Dysphagia, esophagitis, odynophagia (painful swallowing)", ctep_term: "Esophagitis", ctep_code: 10015461], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2138, term: "Dysphagia-esophageal related to radiation", ctep_term: "Radiation oesophagitis", ctep_code: 10048899], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2139, term: "Dysphagia-pharyngeal related to radiation", ctep_term: "Dysphagia", ctep_code: 10013950], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2140, term: "Fistula-esophageal", ctep_term: "Acquired tracheo-oesophageal fistula", ctep_code: 10000582], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2141, term: "Fistula-intestinal", ctep_term: "Fistula of small intestine", ctep_code: 10065850], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2142, term: "Fistula-pharyngeal", ctep_term: "Pharyngeal fistula", ctep_code: 10034825], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2143, term: "Fistula-rectal/anal", ctep_term: "Anal fistula", ctep_code: 10002156], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2144, term: "Flatulence", ctep_term: "Flatulence", ctep_code: 10016766], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2145, term: "Gastric ulcer (requires radiographic or endoscopic documentation)", ctep_term: "Gastric ulcer", ctep_code: 10017822], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2146, term: "Gastritis", ctep_term: "Gastritis", ctep_code: 10017853], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2147, term: "Gastrointestinal-Other (Specify,_____)", ctep_term: "Gastrointestinal disorder", ctep_code: 10017944, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2148, term: "Ileus (or neuroconstipation)", ctep_term: "Ileus", ctep_code: 10021328], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2149, term: "Mouth dryness", ctep_term: "Dry mouth", ctep_code: 10013781], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2150, term: "Mucositis due to radiation", ctep_term: "Radiation mucositis", ctep_code: 10037763], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2151, term: "Nausea", ctep_term: "Nausea", ctep_code: 10028813], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2152, term: "Pancreatitis", ctep_term: "Pancreatitis", ctep_code: 10033645], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2153, term: "Proctitis", ctep_term: "Proctitis", ctep_code: 10036774], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2154, term: "Salivary gland changes", ctep_term: "Salivary gland disorder", ctep_code: 10061935], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2155, term: "Sense of smell", ctep_term: "Olfactory nerve disorder", ctep_code: 10056388], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2156, term: "Stomatitis/pharyngitis (oral/pharyngeal mucositis)", ctep_term: "Mucositis oral", ctep_code: 10028130], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2157, term: "Stomatitis/pharyngitis (oral/pharyngeal mucositis) for BMT studies, if specified in the protocol.", ctep_code: 90004054], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2158, term: "Taste disturbance (dysgeusia)", ctep_term: "Taste alteration", ctep_code: 10043125], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2159, term: "Typhlitis (inflammation of cecum)", ctep_term: "Typhlitis", ctep_code: 10045271], primaryKey: false)
        insert('ctc_terms', [category_id: 212, id: 2160, term: "Vomiting", ctep_term: "Vomiting", ctep_code: 10047700], primaryKey: false)
    }

    void m12() {
        // HEMORRHAGE (13 terms)
        insert('ctc_categories', [version_id: 2, id: 213, name: 'HEMORRHAGE'], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2161, term: "CNS hemorrhage/bleeding", ctep_term: "Intracranial hemorrhage", ctep_code: 10022763], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2162, term: "Epistaxis", ctep_term: "Hemorrhage nasal", ctep_code: 10019561], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2163, term: "Hematemesis", ctep_term: "Haematemesis", ctep_code: 10018830], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2164, term: "Hematuria (in the absence of vaginal bleeding)", ctep_term: "Blood urine present", ctep_code: 10018870], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2165, term: "Hemoptysis", ctep_term: "Haemoptysis", ctep_code: 10018964], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2166, term: "Hemorrhage-Other (Specify,_____)", ctep_term: "Hemorrhage", ctep_code: 10019524, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2167, term: "Hemorrhage/bleeding associated with surgery", ctep_term: "Postoperative hemorrhage", ctep_code: 10055322], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2168, term: "Hemorrhage/bleeding with grade 3 or 4 thrombocytopenia", ctep_code: 90004060], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2169, term: "Hemorrhage/bleeding without grade 3 or 4 thrombocytopenia", ctep_term: "Haemorrhage NOS", ctep_code: 10018988], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2170, term: "Melena/GI bleeding", ctep_term: "Melaena", ctep_code: 10027141], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2171, term: "Petechiae/purpura (hemorrhage/bleeding into skin or mucosa)", ctep_term: "Petechiae", ctep_code: 10034754], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2172, term: "Rectal bleeding/hematochezia", ctep_term: "Haematochezia", ctep_code: 10018836], primaryKey: false)
        insert('ctc_terms', [category_id: 213, id: 2173, term: "Vaginal bleeding", ctep_term: "Vaginal hemorrhage", ctep_code: 10046912], primaryKey: false)
    }

    void m13() {
        // HEPATIC (11 terms)
        insert('ctc_categories', [version_id: 2, id: 214, name: 'HEPATIC'], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2174, term: "Alkaline phosphatase", ctep_term: "Alkaline phosphatase increased", ctep_code: 10001675], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2175, term: "Bilirubin", ctep_term: "Hyperbilirubinemia", ctep_code: 10020582], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2176, term: "Bilirubin associated with graft versus host disease (GVHD) for BMT studies, if specified in the protocol.", ctep_code: 90004064], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2177, term: "GGT (Gamma-Glutamyl transpeptidase)", ctep_term: "Gamma-glutamyltransferase increased", ctep_code: 10017693], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2178, term: "Hepatic enlargement", ctep_term: "Hepatomegaly", ctep_code: 10019842], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2179, term: "Hepatic-Other (Specify,_____)", ctep_term: "Hepatobiliary disease", ctep_code: 10062000, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2180, term: "Hypoalbuminemia", ctep_term: "Hypoalbuminemia", ctep_code: 10020943], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2181, term: "Liver dysfunction/failure (clinical)", ctep_term: "Hepatic failure", ctep_code: 10019663], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2182, term: "Portal vein flow", ctep_term: "Portal hypertension", ctep_code: 10036200], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2183, term: "SGOT (AST) (serum glutamic oxaloacetic transaminase)", ctep_term: "Aspartate aminotransferase increased", ctep_code: 10003481], primaryKey: false)
        insert('ctc_terms', [category_id: 214, id: 2184, term: "SGPT (ALT) (serum glutamic pyruvic transaminase)", ctep_term: "Alanine aminotransferase increased", ctep_code: 10001551], primaryKey: false)
    }

    void m14() {
        // INFECTION/FEBRILE NEUTROPENIA (6 terms)
        insert('ctc_categories', [version_id: 2, id: 215, name: 'INFECTION/FEBRILE NEUTROPENIA'], primaryKey: false)
        insert('ctc_terms', [category_id: 215, id: 2185, term: "Catheter-related infection", ctep_term: "Catheter related infection", ctep_code: 10007810], primaryKey: false)
        insert('ctc_terms', [category_id: 215, id: 2186, term: "Febrile neutropenia (fever of unknown origin without clinically or microbiologically documented infection) (ANC <1.0 x 10e9/L, fever >=38.5 degrees C)", ctep_term: "Febrile neutropenia", ctep_code: 10016288], primaryKey: false)
        insert('ctc_terms', [category_id: 215, id: 2187, term: "Infection (documented clinically or microbiologically) with grade 3 or 4 neutropenia (ANC <1.0 x 10e9/L)", ctep_code: 90004070], primaryKey: false)
        insert('ctc_terms', [category_id: 215, id: 2188, term: "Infection with unknown ANC", ctep_code: 90004066], primaryKey: false)
        insert('ctc_terms', [category_id: 215, id: 2189, term: "Infection without neutropenia", ctep_term: "Infection NOS", ctep_code: 10021842], primaryKey: false)
        insert('ctc_terms', [category_id: 215, id: 2190, term: "Infection/Febrile Neutropenia-Other (Specify,____)", ctep_term: "Infection", ctep_code: 10021789, other_required: "1"], primaryKey: false)
    }

    void m15() {
        // LYMPHATICS (2 terms)
        insert('ctc_categories', [version_id: 2, id: 216, name: 'LYMPHATICS'], primaryKey: false)
        insert('ctc_terms', [category_id: 216, id: 2191, term: "Lymphatics", ctep_term: "Lymphangiopathy NOS", ctep_code: 10025222], primaryKey: false)
        insert('ctc_terms', [category_id: 216, id: 2192, term: "Lymphatics-Other (Specify,___)", ctep_term: "Lymphatic disorder", ctep_code: 10052314, other_required: "1"], primaryKey: false)
    }

    void m16() {
        // METABOLIC/LABORATORY (21 terms)
        insert('ctc_categories', [version_id: 2, id: 217, name: 'METABOLIC/LABORATORY'], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2193, term: "Acidosis (metabolic or respiratory)", ctep_term: "Acidosis", ctep_code: 10000486], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2194, term: "Alkalosis (metabolic or respiratory)", ctep_term: "Alkalosis", ctep_code: 10001680], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2195, term: "Amylase", ctep_term: "Amylase increased", ctep_code: 10002016], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2196, term: "Bicarbonate", ctep_term: "Blood bicarbonate decreased", ctep_code: 10005359], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2197, term: "CPK (creatine phosphokinase)", ctep_term: "Creatine phosphokinase increased", ctep_code: 10011349], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2198, term: "Hypercalcemia", ctep_term: "Hypercalcemia", ctep_code: 10020587], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2199, term: "Hypercholesterolemia", ctep_term: "Hypercholesterolemia", ctep_code: 10020604], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2200, term: "Hyperglycemia", ctep_term: "Hyperglycemia", ctep_code: 10020639], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2201, term: "Hyperkalemia", ctep_term: "Hyperkalemia", ctep_code: 10020647], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2202, term: "Hypermagnesemia", ctep_term: "Hypermagnesemia", ctep_code: 10020670], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2203, term: "Hypernatremia", ctep_term: "Hypernatremia", ctep_code: 10020680], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2204, term: "Hypertriglyceridemia", ctep_term: "Hypertriglyceridemia", ctep_code: 10020870], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2205, term: "Hyperuricemia", ctep_term: "Hyperuricemia", ctep_code: 10020907], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2206, term: "Hypocalcemia", ctep_term: "Hypocalcemia", ctep_code: 10020949], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2207, term: "Hypoglycemia", ctep_term: "Hypoglycemia", ctep_code: 10021005], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2208, term: "Hypokalemia", ctep_term: "Hypokalemia", ctep_code: 10021018], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2209, term: "Hypomagnesemia", ctep_term: "Hypomagnesemia", ctep_code: 10021028], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2210, term: "Hyponatremia", ctep_term: "Hyponatremia", ctep_code: 10021038], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2211, term: "Hypophosphatemia", ctep_term: "Hypophosphatemia", ctep_code: 10021059], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2212, term: "Lipase", ctep_term: "Lipase increased", ctep_code: 10024574], primaryKey: false)
        insert('ctc_terms', [category_id: 217, id: 2213, term: "Metabolic/Laboratory-Other (Specify,_____)", ctep_term: "Laboratory test abnormal", ctep_code: 10023547, other_required: "1"], primaryKey: false)
    }

    void m17() {
        // MUSCULOSKELETAL (5 terms)
        insert('ctc_categories', [version_id: 2, id: 218, name: 'MUSCULOSKELETAL'], primaryKey: false)
        insert('ctc_terms', [category_id: 218, id: 2214, term: "Arthritis", ctep_term: "Arthritis", ctep_code: 10003246], primaryKey: false)
        insert('ctc_terms', [category_id: 218, id: 2215, term: "Muscle weakness (not due to neuropathy)", ctep_term: "Muscle weakness", ctep_code: 10028350], primaryKey: false)
        insert('ctc_terms', [category_id: 218, id: 2216, term: "Musculoskeletal-Other (Specify,______)", ctep_term: "Musculoskeletal disorder", ctep_code: 10048592, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 218, id: 2217, term: "Myositis (inflammation/damage of muscle)", ctep_term: "Myositis", ctep_code: 10028653], primaryKey: false)
        insert('ctc_terms', [category_id: 218, id: 2218, term: "Osteonecrosis (avascular necrosis)", ctep_term: "Osteonecrosis", ctep_code: 10031264], primaryKey: false)
    }

    void m18() {
        // NEUROLOGY (29 terms)
        insert('ctc_categories', [version_id: 2, id: 219, name: 'NEUROLOGY'], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2219, term: "Arachnoiditis/meningismus/radiculitis", ctep_term: "Arachnoiditis", ctep_code: 10003074], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2220, term: "Ataxia (incoordination)", ctep_term: "Ataxia", ctep_code: 10003591], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2221, term: "CNS cerebrovascular ischemia", ctep_term: "Ischemia cerebrovascular", ctep_code: 10023030], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2222, term: "Cognitive disturbance/learning problems (for pediatrics)", ctep_term: "Cognitive disturbance", ctep_code: 10009845], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2223, term: "Confusion", ctep_term: "Confusion", ctep_code: 10010300], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2224, term: "Delusions", ctep_term: "Psychosis", ctep_code: 10037234], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2225, term: "Depressed level of consciousness", ctep_term: "Depressed level of consciousness", ctep_code: 10012373], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2226, term: "Dizziness/lightheadedness", ctep_term: "Dizziness", ctep_code: 10013573], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2227, term: "Extrapyramidal/involuntary movement/restlessness", ctep_term: "Extrapyramidal disorder", ctep_code: 10015832], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2228, term: "Hallucinations", ctep_term: "Hallucination NOS", ctep_code: 10019066], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2229, term: "Insomnia", ctep_term: "Insomnia", ctep_code: 10022437], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2230, term: "Irritability (children <3 years of age)", ctep_term: "Irritability", ctep_code: 10022998], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2231, term: "Leukoencephalopathy associated with radiological findings", ctep_term: "Leukoencephalopathy", ctep_code: 10024382], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2232, term: "Memory loss", ctep_term: "Memory impairment", ctep_code: 10027175], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2233, term: "Mood alteration-anxiety, agitation", ctep_term: "Anxiety", ctep_code: 10002855], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2234, term: "Mood alteration-depression", ctep_term: "Depression", ctep_code: 10012378], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2235, term: "Mood alteration-euphoria", ctep_term: "Euphoria", ctep_code: 10015533], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2236, term: "Neurology-Other (Specify,______)", ctep_term: "Neurological disorder NOS", ctep_code: 10029298, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2237, term: "Neuropathy - cranial", ctep_term: "Cranial neuropathy NOS", ctep_code: 10048658], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2238, term: "Neuropathy - motor", ctep_term: "Peripheral motor neuropathy", ctep_code: 10034580], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2239, term: "Neuropathy-sensory", ctep_term: "Peripheral sensory neuropathy", ctep_code: 10034620], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2240, term: "Nystagmus", ctep_term: "Nystagmus", ctep_code: 10029864], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2241, term: "Personality/behavioral", ctep_term: "Personality change", ctep_code: 10034719], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2242, term: "Pyramidal tract dysfunction (e.g., increased tone, hyperreflexia, positive Babinski, decreased fine motor coordination)", ctep_term: "Pyramidal tract syndrome", ctep_code: 10063636], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2243, term: "Seizure(s)", ctep_term: "Seizure", ctep_code: 10039906], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2244, term: "Speech impairment (e.g., dysphasia or aphasia)", ctep_term: "Speech disorder", ctep_code: 10041466], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2245, term: "Syncope (fainting)", ctep_term: "Syncope", ctep_code: 10042772], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2246, term: "Tremor", ctep_term: "Tremor", ctep_code: 10044565], primaryKey: false)
        insert('ctc_terms', [category_id: 219, id: 2247, term: "Vertigo", ctep_term: "Vertigo", ctep_code: 10047340], primaryKey: false)
    }

    void m19() {
        // OCULAR/VISUAL (12 terms)
        insert('ctc_categories', [version_id: 2, id: 220, name: 'OCULAR/VISUAL'], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2248, term: "Cataract", ctep_term: "Cataract", ctep_code: 10007739], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2249, term: "Conjunctivitis", ctep_term: "Conjunctival disorder", ctep_code: 10061446], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2250, term: "Dry eye", ctep_term: "Dry eye syndrome", ctep_code: 10013777], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2251, term: "Glaucoma", ctep_term: "Glaucoma", ctep_code: 10018304], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2252, term: "Keratitis (corneal inflammation/corneal ulceration)", ctep_term: "Keratitis", ctep_code: 10023332], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2253, term: "Ocular/Visual-Other (Specify,___)", ctep_term: "Eye disorder", ctep_code: 10015916, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2254, term: "Tearing (watery eyes)", ctep_term: "Watering eyes", ctep_code: 10047848], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2255, term: "Vision-blurred vision", ctep_term: "Vision blurred", ctep_code: 10047513], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2256, term: "Vision-double vision (diplopia)", ctep_term: "Diplopia", ctep_code: 10013036], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2257, term: "Vision-flashing lights/floaters", ctep_term: "Flashing vision", ctep_code: 10016758], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2258, term: "Vision-night blindness (nyctalopia)", ctep_term: "Night blindness", ctep_code: 10029404], primaryKey: false)
        insert('ctc_terms', [category_id: 220, id: 2259, term: "Vision-photophobia", ctep_term: "Photophobia", ctep_code: 10034960], primaryKey: false)
    }

    void m20() {
        // PAIN (17 terms)
        insert('ctc_categories', [version_id: 2, id: 221, name: 'PAIN'], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2260, term: "Abdominal pain or cramping", ctep_term: "Abdominal pain", ctep_code: 10000081], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2261, term: "Arthralgia (joint pain)", ctep_term: "Joint pain", ctep_code: 10023222], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2262, term: "Bone pain", ctep_term: "Bone pain", ctep_code: 10006002], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2263, term: "Chest pain (non-cardiac and non-pleuritic)", ctep_term: "Chest pain", ctep_code: 10008479], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2264, term: "Dysmenorrhea", ctep_term: "Dysmenorrhoea", ctep_code: 10013935], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2265, term: "Dyspareunia", ctep_term: "Dyspareunia", ctep_code: 10013941], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2266, term: "Earache (otalgia)", ctep_term: "Ear pain", ctep_code: 10014020], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2267, term: "Headache", ctep_term: "Headache", ctep_code: 10019211], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2268, term: "Hepatic pain", ctep_term: "Hepatic pain", ctep_code: 10019705], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2269, term: "Myalgia (muscle pain)", ctep_term: "Myalgia", ctep_code: 10028411], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2270, term: "Neuropathic pain (e.g., jaw pain, neurologic pain, phantom limb pain, post-infectious neuralgia, or painful neuropathies)", ctep_term: "Neuralgia", ctep_code: 10029223], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2271, term: "Pain due to radiation", ctep_term: "Radiation associated pain", ctep_code: 10037755], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2272, term: "Pain-Other (Specify,___)", ctep_term: "Pain", ctep_code: 90004082, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2273, term: "Pelvic pain", ctep_term: "Pelvic pain", ctep_code: 10034263], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2274, term: "Pleuritic pain", ctep_term: "Pleuritic pain", ctep_code: 10035623], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2275, term: "Rectal or perirectal pain (proctalgia)", ctep_term: "Rectal pain", ctep_code: 10038072], primaryKey: false)
        insert('ctc_terms', [category_id: 221, id: 2276, term: "Tumor pain (onset or exacerbation of tumor pain due to treatment)", ctep_term: "Tumor pain", ctep_code: 10045158], primaryKey: false)
    }

    void m21() {
        // PULMONARY (14 terms)
        insert('ctc_categories', [version_id: 2, id: 222, name: 'PULMONARY'], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2277, term: "Adult respiratory distress syndrome (ARDS)", ctep_term: "Adult respiratory distress syndrome", ctep_code: 10001409], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2278, term: "Apnea", ctep_term: "Apnea", ctep_code: 10002972], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2279, term: "Carbon monoxide diffusion capacity (DL(co))", ctep_term: "Carbon monoxide diffusing capacity decreased", ctep_code: 10065906], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2280, term: "Cough", ctep_term: "Cough", ctep_code: 10011224], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2281, term: "Dyspnea (shortness of breath)", ctep_term: "Dyspnea", ctep_code: 10013963], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2282, term: "FEV (1)", ctep_term: "Forced expiratory volume decreased", ctep_code: 10016987], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2283, term: "Hiccoughs (hiccups, singultus)", ctep_term: "Hiccough", ctep_code: 10020037], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2284, term: "Hypoxia", ctep_term: "Hypoxia", ctep_code: 10021143], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2285, term: "Pleural effusion (non-malignant)", ctep_term: "Pleural effusion", ctep_code: 10035598], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2286, term: "Pneumonitis/pulmonary infiltrates", ctep_term: "Pneumonitis", ctep_code: 10035742], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2287, term: "Pneumothorax", ctep_term: "Pneumothorax", ctep_code: 10035759], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2288, term: "Pulmonary fibrosis", ctep_term: "Pulmonary fibrosis", ctep_code: 10037383], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2289, term: "Pulmonary-Other (Specify,___)", ctep_term: "Respiratory disorder", ctep_code: 10038683, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 222, id: 2290, term: "Voice changes/stridor/larynx (e.g., hoarseness, loss of voice, laryngitis)", ctep_term: "Voice alteration", ctep_code: 10047681], primaryKey: false)
    }

    void m22() {
        // RENAL/GENITOURINARY (16 terms)
        insert('ctc_categories', [version_id: 2, id: 223, name: 'RENAL/GENITOURINARY'], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2291, term: "Bladder spasms", ctep_term: "Bladder spasm", ctep_code: 10048994], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2292, term: "Creatinine", ctep_term: "Creatinine increased", ctep_code: 10011368], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2293, term: "Dysuria (painful urination)", ctep_term: "Bladder pain", ctep_code: 10005063], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2294, term: "Fistula or GU fistula (e.g., vaginal, vesicovaginal)", ctep_term: "Urogenital fistula", ctep_code: 10046696], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2295, term: "Hemoglobinuria", ctep_term: "Hemoglobinuria", ctep_code: 10019489], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2296, term: "Incontinence", ctep_term: "Incontinence NOS", ctep_code: 10048555], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2297, term: "Operative injury to bladder and/or ureter", ctep_term: "Bladder perforation postoperative", ctep_code: 10005066], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2298, term: "Proteinuria", ctep_term: "Proteinuria", ctep_code: 10037032], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2299, term: "Renal failure", ctep_term: "Renal failure", ctep_code: 10038435], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2300, term: "Renal/Genitourinary-Other (Specify,____)", ctep_term: "Urogenital disorder", ctep_code: 10046694, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2301, term: "Ureteral obstruction", ctep_term: "Ureteric obstruction", ctep_code: 10046406], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2302, term: "Urinary electrolyte wasting (e.g., Fanconi's syndrome, renal tubular acidosis)", ctep_term: "Renal tubular disorder", ctep_code: 10038537], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2303, term: "Urinary frequency/urgency", ctep_term: "Urinary frequency", ctep_code: 10046539], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2304, term: "Urinary retention", ctep_term: "Urinary retention", ctep_code: 10046555], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2305, term: "Urine color change (not related to other dietary or physiologic cause e.g., bilirubin, concentrated urine, hematuria)", ctep_term: "Urine discoloration", ctep_code: 10046628], primaryKey: false)
        insert('ctc_terms', [category_id: 223, id: 2306, term: "Vaginitis (not due to infection)", ctep_term: "Vaginal inflammation", ctep_code: 10046916], primaryKey: false)
    }

    void m23() {
        // SECONDARY MALIGNANCY (1 terms)
        insert('ctc_categories', [version_id: 2, id: 224, name: 'SECONDARY MALIGNANCY'], primaryKey: false)
        insert('ctc_terms', [category_id: 224, id: 2307, term: "Secondary Malignancy-Other (Specify,____) excludes metastasis from  initial primary", ctep_term: "Treatment related secondary malignancy", ctep_code: 10049737, other_required: "1"], primaryKey: false)
    }

    void m24() {
        // SEXUAL/REPRODUCTIVE FUNCTION (7 terms)
        insert('ctc_categories', [version_id: 2, id: 225, name: 'SEXUAL/REPRODUCTIVE FUNCTION'], primaryKey: false)
        insert('ctc_terms', [category_id: 225, id: 2308, term: "Erectile impotence", ctep_term: "Erectile dysfunction", ctep_code: 10061461], primaryKey: false)
        insert('ctc_terms', [category_id: 225, id: 2309, term: "Female sterility", ctep_term: "Infertility female", ctep_code: 10021928], primaryKey: false)
        insert('ctc_terms', [category_id: 225, id: 2310, term: "Irregular menses (change from baseline)", ctep_term: "Irregular menstruation", ctep_code: 10022992], primaryKey: false)
        insert('ctc_terms', [category_id: 225, id: 2311, term: "Libido", ctep_term: "Libido decreased", ctep_code: 10024419], primaryKey: false)
        insert('ctc_terms', [category_id: 225, id: 2312, term: "Male infertility", ctep_term: "Infertility male", ctep_code: 10021929], primaryKey: false)
        insert('ctc_terms', [category_id: 225, id: 2313, term: "Sexual/Reproductive Function-Other (Specify,___)", ctep_term: "Reproductive tract disorder", ctep_code: 10061483, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 225, id: 2314, term: "Vaginal dryness", ctep_term: "Vaginal dryness", ctep_code: 10046904], primaryKey: false)
    }

    void m25() {
        // SYNDROMES (3 terms)
        insert('ctc_categories', [version_id: 2, id: 226, name: 'SYNDROMES'], primaryKey: false)
        insert('ctc_terms', [category_id: 226, id: 2315, term: "Syndromes-Other (Specify,_____)", ctep_term: "Ill-defined disorder", ctep_code: 10061520, other_required: "1"], primaryKey: false)
        insert('ctc_terms', [category_id: 226, id: 2316, term: "Tumor flare", ctep_term: "Tumor flare", ctep_code: 10045150], primaryKey: false)
        insert('ctc_terms', [category_id: 226, id: 2317, term: "Tumor lysis syndrome", ctep_term: "Tumor lysis syndrome", ctep_code: 10045152], primaryKey: false)
    }

    void down() {
        execute("DELETE FROM ctc_terms WHERE category_id > 200 AND category_id < 300")
        execute("DELETE FROM ctc_categories WHERE version_id=2")
    }
}
