package gov.nih.nci.cabig.ctms.createcandidateadverseeventservice.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface CreateCandidateAdverseEventServiceI {

    public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

    public java.lang.String processMessage(gov.nih.nci.caaers.grid.beans.AdverseEvent adverseEvent) throws RemoteException, gov.nih.nci.cabig.ctms.createcandidateadverseeventservice.stubs.types.CandidateAdverseEventCreationException ;

}

