package gov.nih.nci.cabig.ctms.grid.ae.service.globus;

import gov.nih.nci.cabig.ctms.grid.ae.service.AdverseEventConsumerImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the AdverseEventConsumerImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class AdverseEventConsumerProviderImpl{
	
	AdverseEventConsumerImpl impl;
	
	public AdverseEventConsumerProviderImpl() throws RemoteException {
		impl = new AdverseEventConsumerImpl();
	}
	

    public gov.nih.nci.cabig.ctms.grid.ae.stubs.RegisterResponse register(gov.nih.nci.cabig.ctms.grid.ae.stubs.RegisterRequest params) throws RemoteException {
    gov.nih.nci.cabig.ctms.grid.ae.stubs.RegisterResponse boxedResult = new gov.nih.nci.cabig.ctms.grid.ae.stubs.RegisterResponse();
    impl.register(params.getAeNotification().getAeNotification());
    return boxedResult;
  }

}
