package gov.nih.nci.ess.sr.service.safetyreportreview.service.globus;

import gov.nih.nci.ess.sr.service.safetyreportreview.service.SafetyReportReviewImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the SafetyReportingImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correctly mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportReviewProviderImpl{
	
	SafetyReportReviewImpl impl;
	
	public SafetyReportReviewProviderImpl() throws RemoteException {
		impl = new SafetyReportReviewImpl();
	}
	

    public gov.nih.nci.ess.sr.service.safetyreportreview.stubs.CreateSafetyReportReviewProcessResponse createSafetyReportReviewProcess(gov.nih.nci.ess.sr.service.safetyreportreview.stubs.CreateSafetyReportReviewProcessRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportreview.stubs.CreateSafetyReportReviewProcessResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportreview.stubs.CreateSafetyReportReviewProcessResponse();
    impl.createSafetyReportReviewProcess();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportreview.stubs.UpdateSafetyReportReviewProcessResponse updateSafetyReportReviewProcess(gov.nih.nci.ess.sr.service.safetyreportreview.stubs.UpdateSafetyReportReviewProcessRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportreview.stubs.UpdateSafetyReportReviewProcessResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportreview.stubs.UpdateSafetyReportReviewProcessResponse();
    impl.updateSafetyReportReviewProcess();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportreview.stubs.DeactivateSafetyReportReviewProcessResponse deactivateSafetyReportReviewProcess(gov.nih.nci.ess.sr.service.safetyreportreview.stubs.DeactivateSafetyReportReviewProcessRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportreview.stubs.DeactivateSafetyReportReviewProcessResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportreview.stubs.DeactivateSafetyReportReviewProcessResponse();
    impl.deactivateSafetyReportReviewProcess();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportreview.stubs.GetSafetyReportReviewProcessResponse getSafetyReportReviewProcess(gov.nih.nci.ess.sr.service.safetyreportreview.stubs.GetSafetyReportReviewProcessRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportreview.stubs.GetSafetyReportReviewProcessResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportreview.stubs.GetSafetyReportReviewProcessResponse();
    impl.getSafetyReportReviewProcess();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportreview.stubs.ReviewSafetyReportResponse reviewSafetyReport(gov.nih.nci.ess.sr.service.safetyreportreview.stubs.ReviewSafetyReportRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportreview.stubs.ReviewSafetyReportResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportreview.stubs.ReviewSafetyReportResponse();
    impl.reviewSafetyReport();
    return boxedResult;
  }

}
