package gov.nih.nci.cabig.caaers.grid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface ProtocolServiceI {

    public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

    public gov.nih.nci.cabig.caaers.grid.beans.IdentifierType registerParticipant(gov.nih.nci.cabig.caaers.grid.beans.RegistrationType registration) throws RemoteException, gov.nih.nci.cabig.caaers.grid.stubs.types.InvalidRegistration, gov.nih.nci.cabig.caaers.grid.stubs.types.RegistrationError ;

}

