/*******************************************************************************
 * Copyright SemanticBits, Northwestern University and Akaza Research
 * 
 * Distributed under the OSI-approved BSD 3-Clause License.
 * See http://ncip.github.com/caaers/LICENSE.txt for details.
 ******************************************************************************/
package gov.nih.nci.ess.safetyreporting.notification.service;

import gov.nih.nci.ess.safetyreporting.misc.SpringContextCreator;
import gov.nih.nci.ess.safetyreporting.notification.common.SafetyReportNotificationI;

import java.rmi.RemoteException;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class SafetyReportNotificationImpl extends SafetyReportNotificationImplBase {

	private static final String BEAN_NAME = "safetyReportNotificationImpl";
	
	private SafetyReportNotificationI safetyReportNotificationI; 
	
	public SafetyReportNotificationImpl() throws RemoteException {
		super();
	}
	
	/**
	 * @throws BeansException
	 */
	private void initialize() throws BeansException {
		if (safetyReportNotificationI == null) {
			ApplicationContext ctx = SpringContextCreator.getApplicationContext();
			safetyReportNotificationI = (SafetyReportNotificationI) ctx.getBean(BEAN_NAME);
		}
	}
	
	
  public void createSafetyReportDefinitionNotification(gov.nih.nci.ess.safetyreporting.types.SafetyReportDefinitionNotification safetyReportDefinitionNotification,ess.caaers.nci.nih.gov.Id reportDefinitionId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
	  initialize();
	  safetyReportNotificationI.createSafetyReportDefinitionNotification(safetyReportDefinitionNotification, reportDefinitionId);
  }

  public void updateSafetyReportDefinitionNotification(gov.nih.nci.ess.safetyreporting.types.SafetyReportDefinitionNotification safetyReportDefinitionNotification) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void deactivateSafetyReportDefinitionNotification(ess.caaers.nci.nih.gov.Id notificationId,_21090.org.iso.ST reasonForDeactivation) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

