package gov.nih.nci.ess.sr.service.safetyreportreview.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportReviewImpl extends SafetyReportReviewImplBase {

	
	public SafetyReportReviewImpl() throws RemoteException {
		super();
	}
	
  public void createSafetyReportReviewProcess() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void updateSafetyReportReviewProcess() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void deactivateSafetyReportReviewProcess() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void getSafetyReportReviewProcess() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void reviewSafetyReport() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

