package gov.nih.nci.cabig.ctms.createcandidateadverseeventservice.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class CreateCandidateAdverseEventServiceImpl extends CreateCandidateAdverseEventServiceImplBase {

	
	public CreateCandidateAdverseEventServiceImpl() throws RemoteException {
		super();
	}
	

	public java.lang.String processMessage(gov.nih.nci.caaers.grid.beans.AdverseEvent adverseEvent) throws RemoteException, gov.nih.nci.cabig.ctms.createcandidateadverseeventservice.stubs.types.CandidateAdverseEventCreationException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

}

