package gov.nih.nci.ccts.grid.client;

import gov.nih.nci.cabig.ccts.domain.loadlabs.Acknowledgement;
import gov.nih.nci.cabig.ccts.domain.loadlabs.LoadLabsRequest;
import gov.nih.nci.cabig.ccts.domain.loadlabs.WsError;
import gov.nih.nci.ccts.grid.common.LabConsumerServiceI;

import java.io.FileInputStream;
import java.rmi.RemoteException;

import org.apache.axis.client.Stub;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.globus.gsi.GlobusCredential;
import org.globus.wsrf.encoding.ObjectDeserializer;
import org.xml.sax.InputSource;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.2
 */
public class LabConsumerServiceClient extends LabConsumerServiceClientBase implements LabConsumerServiceI {	

	public LabConsumerServiceClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public LabConsumerServiceClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public LabConsumerServiceClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public LabConsumerServiceClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(LabConsumerServiceClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
		
	    System.out.println("Running the Grid Service Client");
	    
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
				LabConsumerServiceClient client = new LabConsumerServiceClient(args[1]);
			    java.lang.Object obj = ObjectDeserializer.deserialize(new InputSource(new FileInputStream("/Users/sakkala/tech/caaers/lab-viewer/caaers-lab-message.xml")),LoadLabsRequest.class);
				
			  
			   Acknowledgement ack = client.loadLabs((LoadLabsRequest)obj);
			  
			  System.out.println ("Status " +ack.getStatus());
			  WsError[] errors = ack.getErrors().getWsError();
			  System.out.println ("Status " +errors.length);
			  if (errors != null) {
				  for (int i=0;i<errors.length;i++) {
					  System.out.println(errors[i].getErrorCode() + " - " + errors[i].getErrorDesc());
				  }
			  }
			  
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
		
		
	}

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getMultipleResourceProperties");
    return portType.getMultipleResourceProperties(params);
    }
  }

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getResourceProperty");
    return portType.getResourceProperty(params);
    }
  }

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryResourceProperties");
    return portType.queryResourceProperties(params);
    }
  }

  public gov.nih.nci.cabig.ccts.domain.loadlabs.Acknowledgement loadLabs(gov.nih.nci.cabig.ccts.domain.loadlabs.LoadLabsRequest loadLabsRequest) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"loadLabs");
    gov.nih.nci.ccts.grid.stubs.LoadLabsRequest params = new gov.nih.nci.ccts.grid.stubs.LoadLabsRequest();
    gov.nih.nci.ccts.grid.stubs.LoadLabsRequestLoadLabsRequest loadLabsRequestContainer = new gov.nih.nci.ccts.grid.stubs.LoadLabsRequestLoadLabsRequest();
    loadLabsRequestContainer.setLoadLabsRequest(loadLabsRequest);
    params.setLoadLabsRequest(loadLabsRequestContainer);
    gov.nih.nci.ccts.grid.stubs.LoadLabsResponse boxedResult = portType.loadLabs(params);
    return boxedResult.getAcknowledgementMessage();
    }
  }

}
