package gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.SafetyReportDefinitionManagementPortType;
import gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.service.SafetyReportDefinitionManagementServiceAddressingLocator;
import gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.common.SafetyReportDefinitionManagementI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.4
 */
public class SafetyReportDefinitionManagementClient extends SafetyReportDefinitionManagementClientBase implements SafetyReportDefinitionManagementI {	

	public SafetyReportDefinitionManagementClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public SafetyReportDefinitionManagementClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public SafetyReportDefinitionManagementClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public SafetyReportDefinitionManagementClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(SafetyReportDefinitionManagementClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  SafetyReportDefinitionManagementClient client = new SafetyReportDefinitionManagementClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"destroy");
    return portType.destroy(params);
    }
  }

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"setTerminationTime");
    return portType.setTerminationTime(params);
    }
  }

  public void createSafetyReportDefinition() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"createSafetyReportDefinition");
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.CreateSafetyReportDefinitionRequest params = new gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.CreateSafetyReportDefinitionRequest();
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.CreateSafetyReportDefinitionResponse boxedResult = portType.createSafetyReportDefinition(params);
    }
  }

  public void updateSafetyReportDefinitionDetails() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"updateSafetyReportDefinitionDetails");
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionDetailsRequest params = new gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionDetailsRequest();
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionDetailsResponse boxedResult = portType.updateSafetyReportDefinitionDetails(params);
    }
  }

  public void updateSafetyReportDefinitionDeliveryDetails() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"updateSafetyReportDefinitionDeliveryDetails");
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionDeliveryDetailsRequest params = new gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionDeliveryDetailsRequest();
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionDeliveryDetailsResponse boxedResult = portType.updateSafetyReportDefinitionDeliveryDetails(params);
    }
  }

  public void updateSafetyReportDefinitionMandatoryFields() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"updateSafetyReportDefinitionMandatoryFields");
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionMandatoryFieldsRequest params = new gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionMandatoryFieldsRequest();
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportDefinitionMandatoryFieldsResponse boxedResult = portType.updateSafetyReportDefinitionMandatoryFields(params);
    }
  }

  public void deactivateSafetyReportDefinition() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"deactivateSafetyReportDefinition");
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.DeactivateSafetyReportDefinitionRequest params = new gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.DeactivateSafetyReportDefinitionRequest();
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.DeactivateSafetyReportDefinitionResponse boxedResult = portType.deactivateSafetyReportDefinition(params);
    }
  }

  public void updateSafetyReportTerminologyForStudy() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"updateSafetyReportTerminologyForStudy");
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportTerminologyForStudyRequest params = new gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportTerminologyForStudyRequest();
    gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.stubs.UpdateSafetyReportTerminologyForStudyResponse boxedResult = portType.updateSafetyReportTerminologyForStudy(params);
    }
  }

}
