package gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportDefinitionManagementImpl extends SafetyReportDefinitionManagementImplBase {

	
	public SafetyReportDefinitionManagementImpl() throws RemoteException {
		super();
	}
	
  public void createSafetyReportDefinition() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void updateSafetyReportDefinitionDetails() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void updateSafetyReportDefinitionDeliveryDetails() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void updateSafetyReportDefinitionMandatoryFields() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void deactivateSafetyReportDefinition() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void updateSafetyReportTerminologyForStudy() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

