package gov.nih.nci.ess.sr.service.safetyreportmanagement.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessible on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public interface SafetyReportManagementI {

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

  public sr.SafetyReportVersion initiateSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,ess.caaers.nci.nih.gov.Id studyIdentifier,ess.caaers.nci.nih.gov.Id subjectIdentifier,ess.caaers.nci.nih.gov.Id patientIdentifier,ess.caaers.nci.nih.gov.Id adverseEventIdentifier,ess.caaers.nci.nih.gov.Id performedProductInvestigationResultIdentifier) throws RemoteException ;

  public sr.SafetyReportVersion associateAEToSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,_21090.org.iso.DSET_II adverseEventIdentifiers) throws RemoteException ;

  public void associateProblemToSafetyReport() throws RemoteException ;

  public void dissociateAEFromSafetyReport() throws RemoteException ;

  public void dissociateProblemFromSafetyReport() throws RemoteException ;

  public void updateAdverseEventInformationInSafetyReport() throws RemoteException ;

  public void updateProblemInformationInSafetyReport() throws RemoteException ;

  public void associateStudyToSafetyReport() throws RemoteException ;

  public void associateAdditionalInformationToSafetyReport() throws RemoteException ;

  public void associateSubjectToSafetyReport() throws RemoteException ;

  public void dissociateStudyFromSafetyReport() throws RemoteException ;

  public void dissociatePersonFromSafetyReport() throws RemoteException ;

  public void updateAttributionInSafetyReport() throws RemoteException ;

  public void updateInterventionInSafetyReport() throws RemoteException ;

  public void updateLabTestResultsInSafetyReport() throws RemoteException ;

  public void updateOtherPossibleCausesInSafetyReport() throws RemoteException ;

  public void updatePatientClinicalMeasurementsInSafetyReport() throws RemoteException ;

  public void updatePatientDiseaseHistoryInSafetyReport() throws RemoteException ;

  public void updatePatientConMedsInSafetyReport() throws RemoteException ;

  public void updatePatientPriorTherapiesInSafetyReport() throws RemoteException ;

  public void updatePatientDemographicsInSafetyReport() throws RemoteException ;

  public void updateReporterInSafetyReport() throws RemoteException ;

  public void updateHealthcareProviderInSafetyReport() throws RemoteException ;

  public void updateSubmitterInSafetyReport() throws RemoteException ;

  public void updateProductProblemInformationInSafetyReport() throws RemoteException ;

  public void updatePatientStatusInSafetyReport() throws RemoteException ;

  public void updatePlannedInterventionInformationInSafetyReport() throws RemoteException ;

  public void updateNarrativeInSafetyReport() throws RemoteException ;

  public void updateTreatmentInformationInSafetyReport() throws RemoteException ;

}

