package gov.nih.nci.ess.ae.service.protocol.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class AEProtocolImpl extends AEProtocolImplBase {

	
	public AEProtocolImpl() throws RemoteException {
		super();
	}
	
  public void updateCodingTerminologyForStudy(ess.caaers.nci.nih.gov.Id id,ess.caaers.nci.nih.gov.Oid oid) throws RemoteException, gov.nih.nci.ess.ae.service.management.stubs.types.AdverseEventServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

