CREATE SEQUENCE CSM_FILTER_CLAUSE_FILTE_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE SEQUENCE CSM_MAPPING_MAPPING_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CSM_PG_PE_PG_PE_ID_SEQ;

CREATE SEQUENCE CSM_PG_PE_PG_PE_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CSM_PRIVILEGE_PRIVILEGE_ID_SEQ;

CREATE SEQUENCE CSM_PRIVILEGE_PRIVILEGE_ID_SEQ
  START WITH 192
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CSM_PROTECTIO_PROTECTION_E_SEQ;

CREATE SEQUENCE CSM_PROTECTIO_PROTECTION_E_SEQ
  START WITH 3
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CSM_PROTECTIO_PROTECTION_G_SEQ;

CREATE SEQUENCE CSM_PROTECTIO_PROTECTION_G_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CSM_ROLE_PRIV_ROLE_PRIVILE_SEQ;

CREATE SEQUENCE CSM_ROLE_PRIV_ROLE_PRIVILE_SEQ
  START WITH 139
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CSM_ROLE_ROLE_ID_SEQ;

CREATE SEQUENCE CSM_ROLE_ROLE_ID_SEQ
  START WITH 166
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP SEQUENCE CSM_USER_GROU_USER_GROUP_R_SEQ;

CREATE SEQUENCE CSM_USER_GROU_USER_GROUP_R_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE CSM_USER_PE_USER_PROTECTIO_SEQ;

CREATE SEQUENCE CSM_USER_PE_USER_PROTECTIO_SEQ
  START WITH 3
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE CSM_APPLICATION ADD ( CSM_VERSION VARCHAR(20));
UPDATE CSM_APPLICATION set UPDATE_DATE = SYSDATE;
ALTER TABLE CSM_APPLICATION MODIFY UPDATE_DATE DATE DEFAULT SYSDATE;

CREATE TABLE CSM_FILTER_CLAUSE
(
  FILTER_CLAUSE_ID              NUMBER(38)      NOT NULL,
  CLASS_NAME                    VARCHAR2(100 BYTE) NOT NULL,
  FILTER_CHAIN                  VARCHAR2(2000 BYTE) NOT NULL,
  TARGET_CLASS_NAME             VARCHAR2(100 BYTE) NOT NULL,
  TARGET_CLASS_ATTRIBUTE_NAME   VARCHAR2(100 BYTE) NOT NULL,
  TARGET_CLASS_ATTRIBUTE_TYPE   VARCHAR2(100 BYTE) NOT NULL,
  TARGET_CLASS_ALIAS            VARCHAR2(100 BYTE),
  TARGET_CLASS_ATTRIBUTE_ALIAS  VARCHAR2(100 BYTE),
  GENERATED_SQL_USER            VARCHAR2(4000 BYTE) NOT NULL,
  GENERATED_SQL_GROUP           VARCHAR2(4000 BYTE) NOT NULL,
  APPLICATION_ID                NUMBER(38)      NOT NULL,
  UPDATE_DATE                   DATE            DEFAULT SYSDATE               NOT NULL
);

UPDATE CSM_GROUP set UPDATE_DATE = SYSDATE;
ALTER TABLE CSM_GROUP MODIFY UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL;

CREATE TABLE CSM_MAPPING
(
  MAPPING_ID           NUMBER(38)               NOT NULL,
  APPLICATION_ID       NUMBER(38)               NOT NULL,
  OBJECT_NAME          VARCHAR2(100 BYTE)       NOT NULL,
  ATTRIBUTE_NAME       VARCHAR2(100 BYTE)       NOT NULL,
  OBJECT_PACKAGE_NAME  VARCHAR2(100 BYTE),
  TABLE_NAME           VARCHAR2(100 BYTE),
  TABLE_NAME_GROUP     VARCHAR2(100 BYTE),
  TABLE_NAME_USER      VARCHAR2(100 BYTE),
  VIEW_NAME_GROUP      VARCHAR2(100 BYTE),
  VIEW_NAME_USER       VARCHAR2(100 BYTE),
  ACTIVE_FLAG          NUMBER(1)                DEFAULT 0                     NOT NULL,
  MAINTAINED_FLAG      NUMBER(1)                DEFAULT 0                     NOT NULL,
  UPDATE_DATE          DATE                     DEFAULT SYSDATE
);

DROP TABLE CSM_PG_PE CASCADE CONSTRAINTS;

CREATE TABLE CSM_PG_PE
(
  PG_PE_ID               NUMBER(38)             NOT NULL,
  PROTECTION_GROUP_ID    NUMBER(38)             NOT NULL,
  PROTECTION_ELEMENT_ID  NUMBER(38)             NOT NULL,
  UPDATE_DATE            DATE                   DEFAULT SYSDATE
);

DROP TABLE CSM_PRIVILEGE CASCADE CONSTRAINTS;

CREATE TABLE CSM_PRIVILEGE
(
  PRIVILEGE_ID           NUMBER(38)             NOT NULL,
  PRIVILEGE_NAME         VARCHAR2(100 BYTE)     NOT NULL,
  PRIVILEGE_DESCRIPTION  VARCHAR2(200 BYTE),
  UPDATE_DATE            DATE                   DEFAULT SYSDATE               NOT NULL
);

DROP TABLE CSM_PROTECTION_ELEMENT CASCADE CONSTRAINTS;

CREATE TABLE CSM_PROTECTION_ELEMENT
(
  PROTECTION_ELEMENT_ID           NUMBER(38)    NOT NULL,
  PROTECTION_ELEMENT_NAME         VARCHAR2(100 BYTE) NOT NULL,
  PROTECTION_ELEMENT_DESCRIPTION  VARCHAR2(200 BYTE),
  OBJECT_ID                       VARCHAR2(100 BYTE) NOT NULL,
  ATTRIBUTE                       VARCHAR2(100 BYTE),
  ATTRIBUTE_VALUE                 VARCHAR2(100 BYTE),
  PROTECTION_ELEMENT_TYPE         VARCHAR2(100 BYTE),
  APPLICATION_ID                  NUMBER(38)    NOT NULL,
  UPDATE_DATE                     DATE          DEFAULT SYSDATE               NOT NULL
);

DROP TABLE CSM_PROTECTION_GROUP CASCADE CONSTRAINTS;

CREATE TABLE CSM_PROTECTION_GROUP
(
  PROTECTION_GROUP_ID           NUMBER(38)      NOT NULL,
  PROTECTION_GROUP_NAME         VARCHAR2(100 BYTE) NOT NULL,
  PROTECTION_GROUP_DESCRIPTION  VARCHAR2(200 BYTE),
  APPLICATION_ID                NUMBER(38)      NOT NULL,
  LARGE_ELEMENT_COUNT_FLAG      NUMBER(1)       NOT NULL,
  UPDATE_DATE                   DATE            DEFAULT SYSDATE               NOT NULL,
  PARENT_PROTECTION_GROUP_ID    NUMBER(38)
);

DROP TABLE CSM_ROLE CASCADE CONSTRAINTS;

CREATE TABLE CSM_ROLE
(
  ROLE_ID           NUMBER(38)                  NOT NULL,
  ROLE_NAME         VARCHAR2(100 BYTE)          NOT NULL,
  ROLE_DESCRIPTION  VARCHAR2(200 BYTE),
  APPLICATION_ID    NUMBER(38)                  NOT NULL,
  ACTIVE_FLAG       NUMBER(1)                   NOT NULL,
  UPDATE_DATE       DATE                        DEFAULT SYSDATE               NOT NULL
);

DROP TABLE CSM_ROLE_PRIVILEGE CASCADE CONSTRAINTS;

CREATE TABLE CSM_ROLE_PRIVILEGE
(
  ROLE_PRIVILEGE_ID  NUMBER(38)                 NOT NULL,
  ROLE_ID            NUMBER(38)                 NOT NULL,
  PRIVILEGE_ID       NUMBER(38)                 NOT NULL
);

ALTER TABLE CSM_USER ADD MIGRATED_FLAG NUMBER(1) DEFAULT 0 NOT NULL ;
ALTER TABLE CSM_USER ADD PREMGRT_LOGIN_NAME VARCHAR(100);
UPDATE CSM_USER set UPDATE_DATE = SYSDATE;
ALTER TABLE CSM_USER MODIFY UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL;

DROP TABLE CSM_USER_GROUP_ROLE_PG CASCADE CONSTRAINTS;

CREATE TABLE CSM_USER_GROUP_ROLE_PG
(
  USER_GROUP_ROLE_PG_ID  NUMBER(38)             NOT NULL,
  USER_ID                NUMBER(38),
  GROUP_ID               NUMBER(38),
  ROLE_ID                NUMBER(38)             NOT NULL,
  PROTECTION_GROUP_ID    NUMBER(38)             NOT NULL,
  UPDATE_DATE            DATE                   DEFAULT SYSDATE               NOT NULL
);

DROP TABLE CSM_USER_PE CASCADE CONSTRAINTS;

CREATE TABLE CSM_USER_PE
(
  USER_PROTECTION_ELEMENT_ID  NUMBER(38)        NOT NULL,
  PROTECTION_ELEMENT_ID       NUMBER(38)        NOT NULL,
  USER_ID                     NUMBER(38)        NOT NULL
);

CREATE UNIQUE INDEX PK_FILTER_CLAUSE ON CSM_FILTER_CLAUSE
(FILTER_CLAUSE_ID);

CREATE INDEX IDX_APPLICATION_ID ON CSM_GROUP
(APPLICATION_ID);

CREATE UNIQUE INDEX UQ_MP_OBJ_NAM_ATTRI_NAM_APP_ID ON CSM_MAPPING
(OBJECT_NAME, ATTRIBUTE_NAME, APPLICATION_ID);


CREATE UNIQUE INDEX UQ_PG_PE_PG_PE_ID ON CSM_PG_PE
(PROTECTION_ELEMENT_ID, PROTECTION_GROUP_ID);


CREATE INDEX IDX_PGPE_PE_ID ON CSM_PG_PE
(PROTECTION_ELEMENT_ID);


CREATE INDEX IDX_PGPE_PG_ID ON CSM_PG_PE
(PROTECTION_GROUP_ID);


CREATE UNIQUE INDEX PK_PG_PE ON CSM_PG_PE
(PG_PE_ID);


CREATE UNIQUE INDEX UQ_PRIVILEGE_NAME ON CSM_PRIVILEGE
(PRIVILEGE_NAME);


CREATE UNIQUE INDEX PK_PRIVILEGE ON CSM_PRIVILEGE
(PRIVILEGE_ID);


CREATE UNIQUE INDEX UQ_PE_OBJ_ATT_APP_ID ON CSM_PROTECTION_ELEMENT
(OBJECT_ID, ATTRIBUTE, APPLICATION_ID);


CREATE INDEX IDX_CSM_PE_APPLICATION_ID ON CSM_PROTECTION_ELEMENT
(APPLICATION_ID);


CREATE UNIQUE INDEX UQ_PE_OBJ_ATTR_ATTR_VAL_APP_ID ON CSM_PROTECTION_ELEMENT
(OBJECT_ID, ATTRIBUTE, ATTRIBUTE_VALUE, APPLICATION_ID);


CREATE UNIQUE INDEX PK_PROTECTION_ELEMENT ON CSM_PROTECTION_ELEMENT
(PROTECTION_ELEMENT_ID);


CREATE UNIQUE INDEX UQ_PG_PG_NAME ON CSM_PROTECTION_GROUP
(APPLICATION_ID, PROTECTION_GROUP_NAME);


CREATE INDEX IDX_PG_APP_ID ON CSM_PROTECTION_GROUP
(APPLICATION_ID);


CREATE INDEX IDX_PG_PARNT_PG_ID ON CSM_PROTECTION_GROUP
(PARENT_PROTECTION_GROUP_ID);


CREATE UNIQUE INDEX PK_PROTECTION_GROUP ON CSM_PROTECTION_GROUP
(PROTECTION_GROUP_ID);


CREATE UNIQUE INDEX UQ_ROLE_ROLE_NAME ON CSM_ROLE
(APPLICATION_ID, ROLE_NAME);


CREATE INDEX IDX_R_APP_ID ON CSM_ROLE
(APPLICATION_ID);


CREATE UNIQUE INDEX PK_ROLE ON CSM_ROLE
(ROLE_ID);


CREATE UNIQUE INDEX PK_ROLE_PRIVILEGE ON CSM_ROLE_PRIVILEGE
(ROLE_PRIVILEGE_ID);


CREATE UNIQUE INDEX UQ_ROLE_ID_PRIVILEGE_ID ON CSM_ROLE_PRIVILEGE
(PRIVILEGE_ID, ROLE_ID);


CREATE INDEX IDX_RP_PRIV_ID ON CSM_ROLE_PRIVILEGE
(PRIVILEGE_ID);


CREATE INDEX IDX_RP_ROLE_ID ON CSM_ROLE_PRIVILEGE
(ROLE_ID);

CREATE INDEX IDX_UG_USER_ID ON CSM_USER_GROUP
(USER_ID);


CREATE INDEX IDX_UG_GROUP_ID ON CSM_USER_GROUP
(GROUP_ID);


CREATE UNIQUE INDEX PK_USER_GROUP_ROLE_PG ON CSM_USER_GROUP_ROLE_PG
(USER_GROUP_ROLE_PG_ID);


CREATE INDEX IDX_UGRPG_GROUP_ID ON CSM_USER_GROUP_ROLE_PG
(GROUP_ID);


CREATE INDEX IDX_UGRPG_ROLE_ID ON CSM_USER_GROUP_ROLE_PG
(ROLE_ID);


CREATE INDEX IDX_UGRPG_PG_ID ON CSM_USER_GROUP_ROLE_PG
(PROTECTION_GROUP_ID);


CREATE INDEX IDX_UGRPG_USER_ID ON CSM_USER_GROUP_ROLE_PG
(USER_ID);


CREATE UNIQUE INDEX PK_USER_PROTECTION_ELEMENT ON CSM_USER_PE
(USER_PROTECTION_ELEMENT_ID);


CREATE UNIQUE INDEX UQ_USER_PE_PE_ID ON CSM_USER_PE
(USER_ID, PROTECTION_ELEMENT_ID);


CREATE INDEX IDX_UPE_USER_ID ON CSM_USER_PE
(USER_ID);


CREATE INDEX IDX_UPE_PE_ID ON CSM_USER_PE
(PROTECTION_ELEMENT_ID);

ALTER TABLE CSM_FILTER_CLAUSE ADD (
  CONSTRAINT PK_FILTER_CLAUSE
 PRIMARY KEY
 (FILTER_CLAUSE_ID));

ALTER TABLE CSM_MAPPING ADD (
  PRIMARY KEY
 (MAPPING_ID));

ALTER TABLE CSM_MAPPING ADD (
  CONSTRAINT UQ_MP_OBJ_NAM_ATTRI_NAM_APP_ID
 UNIQUE (OBJECT_NAME, ATTRIBUTE_NAME, APPLICATION_ID));


ALTER TABLE CSM_PG_PE ADD (
  CONSTRAINT PK_PG_PE
 PRIMARY KEY
 (PG_PE_ID));

ALTER TABLE CSM_PG_PE ADD (
  CONSTRAINT UQ_PG_PE_PG_PE_ID
 UNIQUE (PROTECTION_ELEMENT_ID, PROTECTION_GROUP_ID));


ALTER TABLE CSM_PRIVILEGE ADD (
  CONSTRAINT PK_PRIVILEGE
 PRIMARY KEY
 (PRIVILEGE_ID));

ALTER TABLE CSM_PRIVILEGE ADD (
  CONSTRAINT UQ_PRIVILEGE_NAME
 UNIQUE (PRIVILEGE_NAME));


ALTER TABLE CSM_PROTECTION_ELEMENT ADD (
  CONSTRAINT PK_PROTECTION_ELEMENT
 PRIMARY KEY
 (PROTECTION_ELEMENT_ID));

ALTER TABLE CSM_PROTECTION_ELEMENT ADD (
  CONSTRAINT UQ_PE_OBJ_ATT_APP_ID
 UNIQUE (OBJECT_ID, ATTRIBUTE, APPLICATION_ID));


ALTER TABLE CSM_PROTECTION_GROUP ADD (
  CONSTRAINT PK_PROTECTION_GROUP
 PRIMARY KEY
 (PROTECTION_GROUP_ID));

ALTER TABLE CSM_PROTECTION_GROUP ADD (
  CONSTRAINT UQ_PG_PG_NAME
 UNIQUE (APPLICATION_ID, PROTECTION_GROUP_NAME));


ALTER TABLE CSM_ROLE ADD (
  CONSTRAINT PK_ROLE
 PRIMARY KEY
 (ROLE_ID));

ALTER TABLE CSM_ROLE ADD (
  CONSTRAINT UQ_ROLE_ROLE_NAME
 UNIQUE (APPLICATION_ID, ROLE_NAME));


ALTER TABLE CSM_ROLE_PRIVILEGE ADD (
  CONSTRAINT PK_ROLE_PRIVILEGE
 PRIMARY KEY
 (ROLE_PRIVILEGE_ID));

ALTER TABLE CSM_ROLE_PRIVILEGE ADD (
  CONSTRAINT UQ_ROLE_ID_PRIVILEGE_ID
 UNIQUE (PRIVILEGE_ID, ROLE_ID));


ALTER TABLE CSM_USER_GROUP_ROLE_PG ADD (
  CONSTRAINT PK_USER_GROUP_ROLE_PG
 PRIMARY KEY
 (USER_GROUP_ROLE_PG_ID));


ALTER TABLE CSM_USER_PE ADD (
  CONSTRAINT PK_USER_PROTECTION_ELEMENT
 PRIMARY KEY
 (USER_PROTECTION_ELEMENT_ID));

ALTER TABLE CSM_USER_PE ADD (
  CONSTRAINT UQ_USER_PE_PE_ID
 UNIQUE (USER_ID, PROTECTION_ELEMENT_ID));


ALTER TABLE CSM_FILTER_CLAUSE ADD (
  CONSTRAINT FK_CSM_FC_CSM_APPLICATION
 FOREIGN KEY (APPLICATION_ID)
 REFERENCES CSM_APPLICATION (APPLICATION_ID)
    ON DELETE CASCADE);


ALTER TABLE CSM_MAPPING ADD (
  FOREIGN KEY (APPLICATION_ID)
 REFERENCES CSM_APPLICATION (APPLICATION_ID)
    ON DELETE CASCADE);


ALTER TABLE CSM_PG_PE ADD (
  CONSTRAINT FK_PG_PE_PE
 FOREIGN KEY (PROTECTION_ELEMENT_ID)
 REFERENCES CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_PG_PE ADD (
  CONSTRAINT FK_PG_PE_PG
 FOREIGN KEY (PROTECTION_GROUP_ID)
 REFERENCES CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID)
    ON DELETE CASCADE);


ALTER TABLE CSM_PROTECTION_ELEMENT ADD (
  CONSTRAINT FK_PE_APPLICATION
 FOREIGN KEY (APPLICATION_ID)
 REFERENCES CSM_APPLICATION (APPLICATION_ID)
    ON DELETE CASCADE);


ALTER TABLE CSM_PROTECTION_GROUP ADD (
  CONSTRAINT FK_PG_APPLICATION
 FOREIGN KEY (APPLICATION_ID)
 REFERENCES CSM_APPLICATION (APPLICATION_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_PROTECTION_GROUP ADD (
  CONSTRAINT FK_PG_PG
 FOREIGN KEY (PARENT_PROTECTION_GROUP_ID)
 REFERENCES CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID));


ALTER TABLE CSM_ROLE ADD (
  CONSTRAINT FK_ROLE_APPLICATION
 FOREIGN KEY (APPLICATION_ID)
 REFERENCES CSM_APPLICATION (APPLICATION_ID)
    ON DELETE CASCADE);


ALTER TABLE CSM_ROLE_PRIVILEGE ADD (
  CONSTRAINT FK_ROLE_PRIVILEGE_PRIVILEGE
 FOREIGN KEY (PRIVILEGE_ID)
 REFERENCES CSM_PRIVILEGE (PRIVILEGE_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_ROLE_PRIVILEGE ADD (
  CONSTRAINT FK_ROLE_PRIVILEGE_ROLE
 FOREIGN KEY (ROLE_ID)
 REFERENCES CSM_ROLE (ROLE_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_USER_GROUP_ROLE_PG ADD (
  CONSTRAINT FK_USER_GROUP_ROLE_PG_GROUP
 FOREIGN KEY (GROUP_ID)
 REFERENCES CSM_GROUP (GROUP_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_USER_GROUP_ROLE_PG ADD (
  CONSTRAINT FK_USER_GROUP_ROLE_PG_PG
 FOREIGN KEY (PROTECTION_GROUP_ID)
 REFERENCES CSM_PROTECTION_GROUP (PROTECTION_GROUP_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_USER_GROUP_ROLE_PG ADD (
  CONSTRAINT FK_USER_GROUP_ROLE_PG_ROLE
 FOREIGN KEY (ROLE_ID)
 REFERENCES CSM_ROLE (ROLE_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_USER_GROUP_ROLE_PG ADD (
  CONSTRAINT FK_USER_GROUP_ROLE_PG_USER
 FOREIGN KEY (USER_ID)
 REFERENCES CSM_USER (USER_ID)
    ON DELETE CASCADE);


ALTER TABLE CSM_USER_PE ADD (
  CONSTRAINT FK_USER_PE_PE
 FOREIGN KEY (PROTECTION_ELEMENT_ID)
 REFERENCES CSM_PROTECTION_ELEMENT (PROTECTION_ELEMENT_ID)
    ON DELETE CASCADE);

ALTER TABLE CSM_USER_PE ADD (
  CONSTRAINT FK_USER_PE_USER
 FOREIGN KEY (USER_ID)
 REFERENCES CSM_USER (USER_ID)
    ON DELETE CASCADE)
    

