package gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportRulesEvaluationImpl extends SafetyReportRulesEvaluationImplBase {

	
	public SafetyReportRulesEvaluationImpl() throws RemoteException {
		super();
	}
	
  public void evaluateAgainstSafetyReportingRules() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

