package gov.nih.nci.ess.sr.service.safetyreportnotification.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportNotificationImpl extends SafetyReportNotificationImplBase {

	
	public SafetyReportNotificationImpl() throws RemoteException {
		super();
	}
	
  public void createSafetyReportDefinitionNotification() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void updateSafetyReportDefinitionNotification() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void deactivateSafetyReportDefinitionNotification() throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

