package gov.nih.nci.ess.sr.service.safetyreportnotification.service;

import gov.nih.nci.ess.sr.service.safetyreportnotification.service.globus.resource.SafetyReportNotificationResource;
import  gov.nih.nci.ess.sr.service.service.SafetyReportingConfiguration;

import java.rmi.RemoteException;

import javax.naming.InitialContext;
import javax.xml.namespace.QName;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;
import org.globus.wsrf.ResourceContext;
import org.globus.wsrf.ResourceContextException;
import org.globus.wsrf.ResourceException;
import org.globus.wsrf.ResourceHome;
import org.globus.wsrf.ResourceProperty;
import org.globus.wsrf.ResourcePropertySet;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * Provides some simple accessors for the Impl.
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public abstract class SafetyReportNotificationImplBase {
	
	public SafetyReportNotificationImplBase() throws RemoteException {
	
	}
	
	public SafetyReportingConfiguration getConfiguration() throws Exception {
		return SafetyReportingConfiguration.getConfiguration();
	}
	
	
	public gov.nih.nci.ess.sr.service.safetyreportnotification.service.globus.resource.SafetyReportNotificationResourceHome getResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("home");
		return (gov.nih.nci.ess.sr.service.safetyreportnotification.service.globus.resource.SafetyReportNotificationResourceHome)resource;
	}

	
	
	
	public gov.nih.nci.ess.sr.service.service.globus.resource.SafetyReportingResourceHome getSafetyReportingResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportingHome");
		return (gov.nih.nci.ess.sr.service.service.globus.resource.SafetyReportingResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportquery.service.globus.resource.SafetyReportQueryResourceHome getSafetyReportQueryResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportQueryHome");
		return (gov.nih.nci.ess.sr.service.safetyreportquery.service.globus.resource.SafetyReportQueryResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportmanagement.service.globus.resource.SafetyReportManagementResourceHome getSafetyReportManagementResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportManagementHome");
		return (gov.nih.nci.ess.sr.service.safetyreportmanagement.service.globus.resource.SafetyReportManagementResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.service.globus.resource.SafetyReportDefinitionManagementResourceHome getSafetyReportDefinitionManagementResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportDefinitionManagementHome");
		return (gov.nih.nci.ess.sr.service.safetyreportdefinitionmanagement.service.globus.resource.SafetyReportDefinitionManagementResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.service.globus.resource.SafetyReportRulesManagementResourceHome getSafetyReportRulesManagementResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportRulesManagementHome");
		return (gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.service.globus.resource.SafetyReportRulesManagementResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportreview.service.globus.resource.SafetyReportReviewResourceHome getSafetyReportReviewResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportReviewHome");
		return (gov.nih.nci.ess.sr.service.safetyreportreview.service.globus.resource.SafetyReportReviewResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportadvancedquery.service.globus.resource.SafetyReportAdvancedQueryResourceHome getSafetyReportAdvancedQueryResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportAdvancedQueryHome");
		return (gov.nih.nci.ess.sr.service.safetyreportadvancedquery.service.globus.resource.SafetyReportAdvancedQueryResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.service.globus.resource.SafetyReportRulesEvaluationResourceHome getSafetyReportRulesEvaluationResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportRulesEvaluationHome");
		return (gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.service.globus.resource.SafetyReportRulesEvaluationResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreportdefinitionquery.service.globus.resource.SafetyReportDefinitionQueryResourceHome getSafetyReportDefinitionQueryResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportDefinitionQueryHome");
		return (gov.nih.nci.ess.sr.service.safetyreportdefinitionquery.service.globus.resource.SafetyReportDefinitionQueryResourceHome)resource;
	}
	
	public gov.nih.nci.ess.sr.service.safetyreporttransaction.service.globus.resource.SafetyReportTransactionResourceHome getSafetyReportTransactionResourceHome() throws Exception {
		ResourceHome resource = getResourceHome("safetyReportTransactionHome");
		return (gov.nih.nci.ess.sr.service.safetyreporttransaction.service.globus.resource.SafetyReportTransactionResourceHome)resource;
	}
	
	
	protected ResourceHome getResourceHome(String resourceKey) throws Exception {
		MessageContext ctx = MessageContext.getCurrentContext();

		ResourceHome resourceHome = null;
		
		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/" + resourceKey;
		try {
			javax.naming.Context initialContext = new InitialContext();
			resourceHome = (ResourceHome) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate resource home. : " + resourceKey, e);
		}

		return resourceHome;
	}


}

