package gov.nih.nci.ess.sr.service.safetyreportnotification.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessible on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public interface SafetyReportNotificationI {

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

  public void createSafetyReportDefinitionNotification() throws RemoteException ;

  public void updateSafetyReportDefinitionNotification() throws RemoteException ;

  public void deactivateSafetyReportDefinitionNotification() throws RemoteException ;

}

