package gov.nih.nci.ess.ae.service.protocol.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface AEProtocolI {

  /**
   * Retrieves the terminology system used for encoding adverse events on a study.
   *
   * @param studyId
   * @throws AdverseEventServiceException
   *	
   */
  public ess.caaers.nci.nih.gov.AeTerminology getCodingTerminologyForStudy(ess.caaers.nci.nih.gov.Id studyId) throws RemoteException, gov.nih.nci.ess.ae.service.management.stubs.types.AdverseEventServiceException ;

  /**
   * Updates the terminology system to be used for encoding adverse events on a study.
   *
   * @param aeTerminology
   * @throws AdverseEventServiceException
   *	
   */
  public void updateCodingTerminologyForStudy(ess.caaers.nci.nih.gov.AeTerminology aeTerminology) throws RemoteException, gov.nih.nci.ess.ae.service.management.stubs.types.AdverseEventServiceException ;

}

