package gov.nih.nci.ess.ae.service.protocol.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface AEProtocolI {

  /**
   * Updates the terminology system to be used for encoding adverse events on a study.
   *
   * @param id
   * @param oid
   * @throws AdverseEventServiceException
   *	
   */
  public void updateCodingTerminologyForStudy(ess.caaers.nci.nih.gov.Id id,ess.caaers.nci.nih.gov.Oid oid) throws RemoteException, gov.nih.nci.ess.ae.service.management.stubs.types.AdverseEventServiceException ;

}

