ALTER TABLE CSM_APPLICATION MODIFY  DECLARATIVE_FLAG NUMBER(1) DEFAULT NULL NULL ;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD PROTECTION_ELEMENT_TYPE_ID NUMBER(10);
ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE;
ALTER TABLE CSM_PROTECTION_ELEMENT DROP CONSTRAINT UQ_PE_OBJ_ID_ATTR_APP_ID;

ALTER TABLE CSM_USER_GROUP_ROLE_PG DROP CONSTRAINT FK_USER_GROUP_ROLE_PG_GROUP;

ALTER TABLE CSM_USER_GROUP_ROLE_PG ADD CONSTRAINT FK_USER_GROUP_ROLE_PG_GROUP
    FOREIGN KEY (GROUP_ID) REFERENCES CSM_GROUP (GROUP_ID);

ALTER TABLE CSM_APPLICATION MODIFY APPLICATION_NAME varchar2(100) ;
ALTER TABLE CSM_GROUP MODIFY GROUP_NAME varchar2(100) ;
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_URL;
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_USER_NAME;
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_PASSWORD;
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_DIALECT;
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_DRIVER;

UPDATE csm_application SET csm_application.DECLARATIVE_FLAG=null;
UPDATE csm_pg_pe SET UPDATE_DATE=NULL;
