class InsertNIHNCIOrgs extends edu.northwestern.bioinformatics.bering.Migration {
	void up() {
		if (databaseMatches('postgresql')){
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Eye Institute',0,'NEI')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NEI','NEI.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NEI','gov.nih.nci.cabig.caaers.domain.Organization.NEI',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NEI',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Human Genome Research Institute',0,'NHGRI')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NHGRI','NHGRI.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NHGRI','gov.nih.nci.cabig.caaers.domain.Organization.NHGRI',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NHGRI',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute on Aging',0,'NIA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIA','NIA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIA','gov.nih.nci.cabig.caaers.domain.Organization.NIA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute on Alcohol Abuse and Alcoholism',0,'NIAAA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIAAA','NIAAA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIAAA','gov.nih.nci.cabig.caaers.domain.Organization.NIAAA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIAAA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute of Biomedical Imaging and Bioengineering',0,'NIBIB')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIBIB','NIBIB.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIBIB','gov.nih.nci.cabig.caaers.domain.Organization.NIBIB',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIBIB',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Eunice Kennedy Shriver National Institute of Child Health and Human Development',0,'NICHD')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NICHD','NICHD.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NICHD','gov.nih.nci.cabig.caaers.domain.Organization.NICHD',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NICHD',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute of Dental and Craniofacial Research',0,'NIDCR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDCR','NIDCR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDCR','gov.nih.nci.cabig.caaers.domain.Organization.NIDCR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDCR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute of Diabetes and Digestive and Kidney Diseases',0,'NIDDK')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDDK','NIDDK.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDDK','gov.nih.nci.cabig.caaers.domain.Organization.NIDDK',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDDK',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute on Drug Abuse',0,'NIDA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDA','NIDA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDA','gov.nih.nci.cabig.caaers.domain.Organization.NIDA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIDA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute of Environmental Health Sciences',0,'NIEHS')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIEHS','NIEHS.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIEHS','gov.nih.nci.cabig.caaers.domain.Organization.NIEHS',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIEHS',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute of General Medical Sciences',0,'NIGMS')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIGMS','NIGMS.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIGMS','gov.nih.nci.cabig.caaers.domain.Organization.NIGMS',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIGMS',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute of Mental Health',0,'NIMH')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIMH','NIMH.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIMH','gov.nih.nci.cabig.caaers.domain.Organization.NIMH',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NIMH',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Institute of Nursing Research',0,'NINR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NINR','NINR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NINR','gov.nih.nci.cabig.caaers.domain.Organization.NINR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NINR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Library of Medicine',0,'NLM')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NLM','NLM.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NLM','gov.nih.nci.cabig.caaers.domain.Organization.NLM',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NLM',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Center for Information Technology',0,'CIT')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CIT','CIT.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CIT','gov.nih.nci.cabig.caaers.domain.Organization.CIT',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CIT',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Center for Scientific Review',0,'CSR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CSR','CSR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CSR','gov.nih.nci.cabig.caaers.domain.Organization.CSR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CSR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'John E. Fogarty International Center for Advanced Study in the Health Sciences',0,'FIC')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.FIC','FIC.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.FIC','gov.nih.nci.cabig.caaers.domain.Organization.FIC',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.FIC',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Center for Complementary and Alternative Medicine',0,'NCCAM')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCCAM','NCCAM.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCCAM','gov.nih.nci.cabig.caaers.domain.Organization.NCCAM',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCCAM',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Center on Minority Health and Health Disparities',0,'NCMHD')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCMHD','NCMHD.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCMHD','gov.nih.nci.cabig.caaers.domain.Organization.NCMHD',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCMHD',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'National Center for Research Resources',0,'NCRR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCRR','NCRR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCRR','gov.nih.nci.cabig.caaers.domain.Organization.NCRR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.NCRR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'NIH Clinical Center',0,'CC')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CC','CC.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CC','gov.nih.nci.cabig.caaers.domain.Organization.CC',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CC',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Office of the Director',0,'OD')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.OD','OD.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.OD','gov.nih.nci.cabig.caaers.domain.Organization.OD',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.OD',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Center for Cancer Research',0,'CCR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CCR','CCR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CCR','gov.nih.nci.cabig.caaers.domain.Organization.CCR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CCR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Division of Cancer Biology',0,'DCB')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCB','DCB.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCB','gov.nih.nci.cabig.caaers.domain.Organization.DCB',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCB',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Division of Cancer Control and Population Sciences',0,'DCCPS')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCCPS','DCCPS.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCCPS','gov.nih.nci.cabig.caaers.domain.Organization.DCCPS',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCCPS',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Division of Cancer Epidemiology and Genetics',0,'DCEG')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCEG','DCEG.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCEG','gov.nih.nci.cabig.caaers.domain.Organization.DCEG',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DCEG',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Developmental Therapeutics Program',0,'DTP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DTP','DTP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DTP','gov.nih.nci.cabig.caaers.domain.Organization.DTP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DTP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Division of Extramural Activities',0,'DEA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DEA','DEA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DEA','gov.nih.nci.cabig.caaers.domain.Organization.DEA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DEA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Organ Systems Branch (OSB) /Specialized Programs of Research Excellence (SPOREs)',0,'OSB/SPOREs')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs','OSB/SPOREs.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs','gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Cancer Imaging Program',0,'CIP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CIP','CIP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CIP','gov.nih.nci.cabig.caaers.domain.Organization.CIP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CIP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Cancer Diagnosis Program',0,'CDP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CDP','CDP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CDP','gov.nih.nci.cabig.caaers.domain.Organization.CDP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.CDP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Translational Research Program',0,'TRP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.TRP','TRP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.TRP','gov.nih.nci.cabig.caaers.domain.Organization.TRP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.TRP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values ((select nextval('organizations_id_seq')),'Radiation Research Program',0,'RRP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.RRP','RRP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.RRP','gov.nih.nci.cabig.caaers.domain.Organization.RRP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.RRP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (-1111,'Dummy Organization',0,'DUMMY')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values ((select nextval('csm_group_group_id_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DUMMY','DUMMY.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values ((select nextval('csm_protectio_protection_e_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DUMMY','gov.nih.nci.cabig.caaers.domain.Organization.DUMMY',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values ((select nextval('csm_protectio_protection_g_seq')),'gov.nih.nci.cabig.caaers.domain.Organization.DUMMY',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values ((select nextval('csm_pg_pe_id_seq')),(select currval('csm_protectio_protection_g_seq')),(select currval('csm_protectio_protection_e_seq')))")
		
		}else if(databaseMatches('oracle')){
		
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Eye Institute',0,'NEI')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NEI','NEI.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NEI','gov.nih.nci.cabig.caaers.domain.Organization.NEI',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NEI',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Human Genome Research Institute',0,'NHGRI')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NHGRI','NHGRI.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NHGRI','gov.nih.nci.cabig.caaers.domain.Organization.NHGRI',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NHGRI',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute on Aging',0,'NIA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIA','NIA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIA','gov.nih.nci.cabig.caaers.domain.Organization.NIA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute on Alcohol Abuse and Alcoholism',0,'NIAAA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIAAA','NIAAA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIAAA','gov.nih.nci.cabig.caaers.domain.Organization.NIAAA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIAAA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute of Biomedical Imaging and Bioengineering',0,'NIBIB')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIBIB','NIBIB.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIBIB','gov.nih.nci.cabig.caaers.domain.Organization.NIBIB',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIBIB',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Eunice Kennedy Shriver National Institute of Child Health and Human Development',0,'NICHD')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NICHD','NICHD.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NICHD','gov.nih.nci.cabig.caaers.domain.Organization.NICHD',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NICHD',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute of Dental and Craniofacial Research',0,'NIDCR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDCR','NIDCR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDCR','gov.nih.nci.cabig.caaers.domain.Organization.NIDCR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDCR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute of Diabetes and Digestive and Kidney Diseases',0,'NIDDK')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDDK','NIDDK.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDDK','gov.nih.nci.cabig.caaers.domain.Organization.NIDDK',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDDK',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute on Drug Abuse',0,'NIDA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDA','NIDA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDA','gov.nih.nci.cabig.caaers.domain.Organization.NIDA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIDA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute of Environmental Health Sciences',0,'NIEHS')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIEHS','NIEHS.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIEHS','gov.nih.nci.cabig.caaers.domain.Organization.NIEHS',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIEHS',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute of General Medical Sciences',0,'NIGMS')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIGMS','NIGMS.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIGMS','gov.nih.nci.cabig.caaers.domain.Organization.NIGMS',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIGMS',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute of Mental Health',0,'NIMH')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIMH','NIMH.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIMH','gov.nih.nci.cabig.caaers.domain.Organization.NIMH',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NIMH',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Institute of Nursing Research',0,'NINR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NINR','NINR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NINR','gov.nih.nci.cabig.caaers.domain.Organization.NINR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NINR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Library of Medicine',0,'NLM')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NLM','NLM.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NLM','gov.nih.nci.cabig.caaers.domain.Organization.NLM',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NLM',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Center for Information Technology',0,'CIT')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CIT','CIT.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CIT','gov.nih.nci.cabig.caaers.domain.Organization.CIT',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CIT',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Center for Scientific Review',0,'CSR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CSR','CSR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CSR','gov.nih.nci.cabig.caaers.domain.Organization.CSR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CSR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'John E. Fogarty International Center for Advanced Study in the Health Sciences',0,'FIC')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.FIC','FIC.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.FIC','gov.nih.nci.cabig.caaers.domain.Organization.FIC',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.FIC',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Center for Complementary and Alternative Medicine',0,'NCCAM')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCCAM','NCCAM.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCCAM','gov.nih.nci.cabig.caaers.domain.Organization.NCCAM',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCCAM',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Center on Minority Health and Health Disparities',0,'NCMHD')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCMHD','NCMHD.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCMHD','gov.nih.nci.cabig.caaers.domain.Organization.NCMHD',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCMHD',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'National Center for Research Resources',0,'NCRR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCRR','NCRR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCRR','gov.nih.nci.cabig.caaers.domain.Organization.NCRR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.NCRR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'NIH Clinical Center',0,'CC')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CC','CC.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CC','gov.nih.nci.cabig.caaers.domain.Organization.CC',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CC',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Office of the Director',0,'OD')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.OD','OD.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.OD','gov.nih.nci.cabig.caaers.domain.Organization.OD',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.OD',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Center for Cancer Research',0,'CCR')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CCR','CCR.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CCR','gov.nih.nci.cabig.caaers.domain.Organization.CCR',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CCR',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Division of Cancer Biology',0,'DCB')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCB','DCB.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCB','gov.nih.nci.cabig.caaers.domain.Organization.DCB',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCB',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Division of Cancer Control and Population Sciences',0,'DCCPS')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCCPS','DCCPS.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCCPS','gov.nih.nci.cabig.caaers.domain.Organization.DCCPS',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCCPS',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Division of Cancer Epidemiology and Genetics',0,'DCEG')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCEG','DCEG.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCEG','gov.nih.nci.cabig.caaers.domain.Organization.DCEG',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DCEG',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Developmental Therapeutics Program',0,'DTP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DTP','DTP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DTP','gov.nih.nci.cabig.caaers.domain.Organization.DTP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DTP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Division of Extramural Activities',0,'DEA')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DEA','DEA.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DEA','gov.nih.nci.cabig.caaers.domain.Organization.DEA',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DEA',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Organ Systems Branch (OSB) /Specialized Programs of Research Excellence (SPOREs)',0,'OSB/SPOREs')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs','OSB/SPOREs.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs','gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.OSB/SPOREs',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Cancer Imaging Program',0,'CIP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CIP','CIP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CIP','gov.nih.nci.cabig.caaers.domain.Organization.CIP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CIP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Cancer Diagnosis Program',0,'CDP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CDP','CDP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CDP','gov.nih.nci.cabig.caaers.domain.Organization.CDP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.CDP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Translational Research Program',0,'TRP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.TRP','TRP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.TRP','gov.nih.nci.cabig.caaers.domain.Organization.TRP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.TRP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (SEQ_ORGANIZATIONS_ID.nextval,'Radiation Research Program',0,'RRP')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.RRP','RRP.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.RRP','gov.nih.nci.cabig.caaers.domain.Organization.RRP',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.RRP',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
			
			execute("insert into organizations (id,name,version,nci_institute_code) values (-1111,'Dummy Organization',0,'DUMMY')")
			execute("insert into csm_group (group_id,group_name,group_desc,application_id) values (CSM_GROUP_GROUP_ID_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DUMMY','DUMMY.group',-1)")
			execute("insert into csm_protection_element (protection_element_id,protection_element_name,object_id,application_id) values (CSM_PROTECTIO_PROTECTION_E_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DUMMY','gov.nih.nci.cabig.caaers.domain.Organization.DUMMY',-1)")
			execute("insert into csm_protection_group (protection_group_id,protection_group_name,application_id,parent_protection_group_id,large_element_count_flag) values (CSM_PROTECTIO_PROTECTION_G_SEQ.nextval,'gov.nih.nci.cabig.caaers.domain.Organization.DUMMY',-1,-5,0)")
			execute("insert into csm_pg_pe (pg_pe_id,protection_group_id,protection_element_id) values (CSM_PG_PE_PG_PE_ID_SEQ.nextval,CSM_PROTECTIO_PROTECTION_G_SEQ.currval,CSM_PROTECTIO_PROTECTION_E_SEQ.currval)")
		}
	}

	void down() {
		//nothing here
	}
}