package gov.nih.nci.ess.safetyreporting.management.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface SafetyReportManagementConstantsBase {
	public static final String SERVICE_NS = "http://safetyreporting.ess.nci.nih.gov/SafetyReportingEnterpriseService/SafetyReportManagement";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "SafetyReportManagementKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "SafetyReportManagementResourceProperties");
	
}
