class InterventionSites extends edu.northwestern.bioinformatics.bering.Migration {
    void up() {
        // Have to break up the inserts so as not to exceed the java max method length
        m0()
        m1()
        m2()
        m3()
        m4()
        m5()
    }

    void m0() {
        // all0 (25 terms)
        insert('intervention_sites', [ id: 1000, name: "Abdomen NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1001, name: "Adrenal gland"], primaryKey: false)
        insert('intervention_sites', [ id: 1002, name: "Anal sphincter"], primaryKey: false)
        insert('intervention_sites', [ id: 1003, name: "Anus"], primaryKey: false)
        insert('intervention_sites', [ id: 1004, name: "Appendix"], primaryKey: false)
        insert('intervention_sites', [ id: 1005, name: "Artery NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1006, name: "Artery-aorta"], primaryKey: false)
        insert('intervention_sites', [ id: 1007, name: "Artery-carotid"], primaryKey: false)
        insert('intervention_sites', [ id: 1008, name: "Artery-cerebral"], primaryKey: false)
        insert('intervention_sites', [ id: 1009, name: "Artery-extremity (lower)"], primaryKey: false)
        insert('intervention_sites', [ id: 1010, name: "Artery-extremity (upper)"], primaryKey: false)
        insert('intervention_sites', [ id: 1011, name: "Artery-hepatic"], primaryKey: false)
        insert('intervention_sites', [ id: 1012, name: "Artery-major visceral artery"], primaryKey: false)
        insert('intervention_sites', [ id: 1013, name: "Artery-pulmonary"], primaryKey: false)
        insert('intervention_sites', [ id: 1014, name: "Biliary tree NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1015, name: "Biliary tree-common bile duct"], primaryKey: false)
        insert('intervention_sites', [ id: 1016, name: "Biliary tree-common hepatic duct"], primaryKey: false)
        insert('intervention_sites', [ id: 1017, name: "Biliary tree-left hepatic duct"], primaryKey: false)
        insert('intervention_sites', [ id: 1018, name: "Biliary tree-right hepatic duct"], primaryKey: false)
        insert('intervention_sites', [ id: 1019, name: "Bladder"], primaryKey: false)
        insert('intervention_sites', [ id: 1020, name: "Bone"], primaryKey: false)
        insert('intervention_sites', [ id: 1021, name: "Brain"], primaryKey: false)
        insert('intervention_sites', [ id: 1022, name: "Breast"], primaryKey: false)
        insert('intervention_sites', [ id: 1023, name: "Bronchus"], primaryKey: false)
        insert('intervention_sites', [ id: 1024, name: "Cartilage"], primaryKey: false)
    }

    void m1() {
        // all1 (25 terms)
        insert('intervention_sites', [ id: 1025, name: "Cecum"], primaryKey: false)
        insert('intervention_sites', [ id: 1026, name: "Cervix"], primaryKey: false)
        insert('intervention_sites', [ id: 1027, name: "Colon"], primaryKey: false)
        insert('intervention_sites', [ id: 1028, name: "Conjunctiva"], primaryKey: false)
        insert('intervention_sites', [ id: 1029, name: "Cornea"], primaryKey: false)
        insert('intervention_sites', [ id: 1030, name: "Duodenum"], primaryKey: false)
        insert('intervention_sites', [ id: 1031, name: "Esophagus"], primaryKey: false)
        insert('intervention_sites', [ id: 1032, name: "Extremity-lower"], primaryKey: false)
        insert('intervention_sites', [ id: 1033, name: "Extremity-upper"], primaryKey: false)
        insert('intervention_sites', [ id: 1034, name: "Eye NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1035, name: "Face NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1036, name: "Fallopian tube"], primaryKey: false)
        insert('intervention_sites', [ id: 1037, name: "Foot"], primaryKey: false)
        insert('intervention_sites', [ id: 1038, name: "Gallbladder"], primaryKey: false)
        insert('intervention_sites', [ id: 1039, name: "Gingiva"], primaryKey: false)
        insert('intervention_sites', [ id: 1040, name: "Hand"], primaryKey: false)
        insert('intervention_sites', [ id: 1041, name: "Heart"], primaryKey: false)
        insert('intervention_sites', [ id: 1042, name: "Hip"], primaryKey: false)
        insert('intervention_sites', [ id: 1043, name: "Ileum"], primaryKey: false)
        insert('intervention_sites', [ id: 1044, name: "Inner ear"], primaryKey: false)
        insert('intervention_sites', [ id: 1045, name: "Jejunum"], primaryKey: false)
        insert('intervention_sites', [ id: 1046, name: "Joint"], primaryKey: false)
        insert('intervention_sites', [ id: 1047, name: "Kidney"], primaryKey: false)
        insert('intervention_sites', [ id: 1048, name: "Knee"], primaryKey: false)
        insert('intervention_sites', [ id: 1049, name: "Larynx"], primaryKey: false)
    }

    void m2() {
        // all2 (25 terms)
        insert('intervention_sites', [ id: 1050, name: "Lens"], primaryKey: false)
        insert('intervention_sites', [ id: 1051, name: "Ligament"], primaryKey: false)
        insert('intervention_sites', [ id: 1052, name: "Lip/perioral area"], primaryKey: false)
        insert('intervention_sites', [ id: 1053, name: "Liver"], primaryKey: false)
        insert('intervention_sites', [ id: 1054, name: "Lower Arm"], primaryKey: false)
        insert('intervention_sites', [ id: 1055, name: "Lung"], primaryKey: false)
        insert('intervention_sites', [ id: 1056, name: "Mediastinum"], primaryKey: false)
        insert('intervention_sites', [ id: 1057, name: "Meninges"], primaryKey: false)
        insert('intervention_sites', [ id: 1058, name: "Middle ear"], primaryKey: false)
        insert('intervention_sites', [ id: 1059, name: "Muscle"], primaryKey: false)
        insert('intervention_sites', [ id: 1060, name: "NERVES: Brachial plexus"], primaryKey: false)
        insert('intervention_sites', [ id: 1061, name: "NERVES: CN I (olfactory)"], primaryKey: false)
        insert('intervention_sites', [ id: 1062, name: "NERVES: CN II (optic)"], primaryKey: false)
        insert('intervention_sites', [ id: 1063, name: "NERVES: CN III (oculomotor)"], primaryKey: false)
        insert('intervention_sites', [ id: 1064, name: "NERVES: CN IV (trochlear)"], primaryKey: false)
        insert('intervention_sites', [ id: 1065, name: "NERVES: CN IX (glossopharyngeal) motor pharynx"], primaryKey: false)
        insert('intervention_sites', [ id: 1066, name: "NERVES: CN IX (glossopharyngeal) sensory ear-pharynx-tongue"], primaryKey: false)
        insert('intervention_sites', [ id: 1067, name: "NERVES: CN V (trigeminal) motor"], primaryKey: false)
        insert('intervention_sites', [ id: 1068, name: "NERVES: CN V (trigeminal) sensory"], primaryKey: false)
        insert('intervention_sites', [ id: 1069, name: "NERVES: CN VI (abducens)"], primaryKey: false)
        insert('intervention_sites', [ id: 1070, name: "NERVES: CN VII (facial) motor-face"], primaryKey: false)
        insert('intervention_sites', [ id: 1071, name: "NERVES: CN VII (facial) sensory-taste"], primaryKey: false)
        insert('intervention_sites', [ id: 1072, name: "NERVES: CN VIII (vestibulocochlear)"], primaryKey: false)
        insert('intervention_sites', [ id: 1073, name: "NERVES: CN X (vagus)"], primaryKey: false)
        insert('intervention_sites', [ id: 1074, name: "NERVES: CN XI (spinal accessory)"], primaryKey: false)
    }

    void m3() {
        // all3 (25 terms)
        insert('intervention_sites', [ id: 1075, name: "NERVES: CN XII (hypoglossal)"], primaryKey: false)
        insert('intervention_sites', [ id: 1076, name: "NERVES: Cranial nerve or branch NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1077, name: "NERVES: Lingual"], primaryKey: false)
        insert('intervention_sites', [ id: 1078, name: "NERVES: Lung thoracic"], primaryKey: false)
        insert('intervention_sites', [ id: 1079, name: "NERVES: Peripheral motor NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1080, name: "NERVES: Peripheral sensory NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1081, name: "NERVES: Recurrent laryngeal"], primaryKey: false)
        insert('intervention_sites', [ id: 1082, name: "NERVES: Sacral plexus"], primaryKey: false)
        insert('intervention_sites', [ id: 1083, name: "NERVES: Sciatic"], primaryKey: false)
        insert('intervention_sites', [ id: 1084, name: "NERVES: Thoracodorsal"], primaryKey: false)
        insert('intervention_sites', [ id: 1085, name: "Nails"], primaryKey: false)
        insert('intervention_sites', [ id: 1086, name: "Nasal cavity"], primaryKey: false)
        insert('intervention_sites', [ id: 1087, name: "Nasopharynx"], primaryKey: false)
        insert('intervention_sites', [ id: 1088, name: "Neck NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1089, name: "Nose"], primaryKey: false)
        insert('intervention_sites', [ id: 1090, name: "Oral"], primaryKey: false)
        insert('intervention_sites', [ id: 1091, name: "Oral cavity NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1092, name: "Outer ear NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1093, name: "Outer ear-Pinna"], primaryKey: false)
        insert('intervention_sites', [ id: 1094, name: "Ovary"], primaryKey: false)
        insert('intervention_sites', [ id: 1095, name: "Pancreas"], primaryKey: false)
        insert('intervention_sites', [ id: 1096, name: "Pancreatic duct"], primaryKey: false)
        insert('intervention_sites', [ id: 1097, name: "Parathyroid"], primaryKey: false)
        insert('intervention_sites', [ id: 1098, name: "Parotid gland"], primaryKey: false)
        insert('intervention_sites', [ id: 1099, name: "Pelvis NOS"], primaryKey: false)
    }

    void m4() {
        // all4 (25 terms)
        insert('intervention_sites', [ id: 1100, name: "Penis"], primaryKey: false)
        insert('intervention_sites', [ id: 1101, name: "Peritoneal cavity"], primaryKey: false)
        insert('intervention_sites', [ id: 1102, name: "Pharynx"], primaryKey: false)
        insert('intervention_sites', [ id: 1103, name: "Pituitary"], primaryKey: false)
        insert('intervention_sites', [ id: 1104, name: "Pleura"], primaryKey: false)
        insert('intervention_sites', [ id: 1105, name: "Prostate"], primaryKey: false)
        insert('intervention_sites', [ id: 1106, name: "Rectum"], primaryKey: false)
        insert('intervention_sites', [ id: 1107, name: "Retina"], primaryKey: false)
        insert('intervention_sites', [ id: 1108, name: "Retroperitoneum"], primaryKey: false)
        insert('intervention_sites', [ id: 1109, name: "Salivary duct"], primaryKey: false)
        insert('intervention_sites', [ id: 1110, name: "Salivary gland"], primaryKey: false)
        insert('intervention_sites', [ id: 1111, name: "Scrotum"], primaryKey: false)
        insert('intervention_sites', [ id: 1112, name: "Sinus"], primaryKey: false)
        insert('intervention_sites', [ id: 1113, name: "Skin"], primaryKey: false)
        insert('intervention_sites', [ id: 1114, name: "Small bowel NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1115, name: "Soft tissue NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1116, name: "Spinal cord"], primaryKey: false)
        insert('intervention_sites', [ id: 1117, name: "Spleen"], primaryKey: false)
        insert('intervention_sites', [ id: 1118, name: "Stoma (GI)"], primaryKey: false)
        insert('intervention_sites', [ id: 1119, name: "Stomach"], primaryKey: false)
        insert('intervention_sites', [ id: 1120, name: "Teeth"], primaryKey: false)
        insert('intervention_sites', [ id: 1121, name: "Tendon"], primaryKey: false)
        insert('intervention_sites', [ id: 1122, name: "Testis"], primaryKey: false)
        insert('intervention_sites', [ id: 1123, name: "Thoracic duct"], primaryKey: false)
        insert('intervention_sites', [ id: 1124, name: "Thyroid"], primaryKey: false)
    }

    void m5() {
        // all5 (22 terms)
        insert('intervention_sites', [ id: 1125, name: "Tongue"], primaryKey: false)
        insert('intervention_sites', [ id: 1126, name: "Trachea"], primaryKey: false)
        insert('intervention_sites', [ id: 1127, name: "Upper Arm"], primaryKey: false)
        insert('intervention_sites', [ id: 1128, name: "Upper aerodigestive NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1129, name: "Upper airway NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1130, name: "Ureter"], primaryKey: false)
        insert('intervention_sites', [ id: 1131, name: "Urethra"], primaryKey: false)
        insert('intervention_sites', [ id: 1132, name: "Urinary conduit"], primaryKey: false)
        insert('intervention_sites', [ id: 1133, name: "Urinary tract NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1134, name: "Uterus"], primaryKey: false)
        insert('intervention_sites', [ id: 1135, name: "Vagina"], primaryKey: false)
        insert('intervention_sites', [ id: 1136, name: "Vein NOS"], primaryKey: false)
        insert('intervention_sites', [ id: 1137, name: "Vein-extremity (lower)"], primaryKey: false)
        insert('intervention_sites', [ id: 1138, name: "Vein-extremity (upper)"], primaryKey: false)
        insert('intervention_sites', [ id: 1139, name: "Vein-hepatic"], primaryKey: false)
        insert('intervention_sites', [ id: 1140, name: "Vein-inferior vena cava"], primaryKey: false)
        insert('intervention_sites', [ id: 1141, name: "Vein-jugular"], primaryKey: false)
        insert('intervention_sites', [ id: 1142, name: "Vein-major visceral vein"], primaryKey: false)
        insert('intervention_sites', [ id: 1143, name: "Vein-portal vein"], primaryKey: false)
        insert('intervention_sites', [ id: 1144, name: "Vein-pulmonary"], primaryKey: false)
        insert('intervention_sites', [ id: 1145, name: "Vein-superior vena cava"], primaryKey: false)
        insert('intervention_sites', [ id: 1146, name: "Vulva"], primaryKey: false)
    }

    void down() {
        execute("DELETE FROM intervention_sites")
    }
}
