class CreateCtcLookups extends edu.northwestern.bioinformatics.bering.Migration {
    void up() {
        createTable("ctc_categories") { t->
            t.setIncludePrimaryKey(false)
            t.addColumn("id", "integer", nullable: false, primaryKey: true)
            t.addColumn("name", "string", nullable: false)
        }

        createTable("ctc_versions") { t->
            t.setIncludePrimaryKey(false)
            t.addColumn("id", "integer", nullable: false, primaryKey: true)
            t.addColumn("name", "string", nullable: false)
        }

        createTable("ctc_version_categories") { t ->
            t.setIncludePrimaryKey(false)
            t.addColumn("version_id", "integer", nullable: false)
            t.addColumn("category_id", "integer", nullable: false)
        }

        insert("ctc_versions", [ id: 2, name: "CTC v2.0" ], primaryKey: false)
        insert("ctc_versions", [ id: 3, name: "CTCAE v3.0" ], primaryKey: false)

        insert("ctc_categories", [ id:  1, name: "allergy/immunology" ], primaryKey: false)
        insert("ctc_categories", [ id:  2, name: "auditory/ear" ], primaryKey: false)
        insert("ctc_categories", [ id:  3, name: "blood/bone marrow" ], primaryKey: false)
        insert("ctc_categories", [ id:  4, name: "cardiac arrythmia" ], primaryKey: false)
        insert("ctc_categories", [ id:  5, name: "cardiac general" ], primaryKey: false)
        insert("ctc_categories", [ id:  6, name: "coagulation" ], primaryKey: false)
        insert("ctc_categories", [ id:  7, name: "constitutional symptoms" ], primaryKey: false)
        insert("ctc_categories", [ id:  8, name: "death" ], primaryKey: false)
        insert("ctc_categories", [ id:  9, name: "dermatology/skin" ], primaryKey: false)
        insert("ctc_categories", [ id: 10, name: "endocrine" ], primaryKey: false)
        insert("ctc_categories", [ id: 11, name: "gastrointestinal" ], primaryKey: false)
        insert("ctc_categories", [ id: 12, name: "growth and development" ], primaryKey: false)
        insert("ctc_categories", [ id: 13, name: "hemorrage/bleeding" ], primaryKey: false)
        insert("ctc_categories", [ id: 14, name: "hepatobiliary/pancreas" ], primaryKey: false)
        insert("ctc_categories", [ id: 15, name: "infection" ], primaryKey: false)
        insert("ctc_categories", [ id: 16, name: "lymphatics" ], primaryKey: false)
        insert("ctc_categories", [ id: 17, name: "metabolic/laboratory" ], primaryKey: false)
        insert("ctc_categories", [ id: 18, name: "musculoskeletal/soft tissue" ], primaryKey: false)
        insert("ctc_categories", [ id: 19, name: "neurology" ], primaryKey: false)
        insert("ctc_categories", [ id: 20, name: "ocular/visual" ], primaryKey: false)
        insert("ctc_categories", [ id: 21, name: "pain" ], primaryKey: false)
        insert("ctc_categories", [ id: 22, name: "pulmonary/upper respiratory" ], primaryKey: false)
        insert("ctc_categories", [ id: 23, name: "renal/genitourinary" ], primaryKey: false)
        insert("ctc_categories", [ id: 24, name: "secondary malignancy" ], primaryKey: false)
        insert("ctc_categories", [ id: 25, name: "sexual/reproductive function" ], primaryKey: false)
        insert("ctc_categories", [ id: 26, name: "surgery/intra-operative injury" ], primaryKey: false)
        insert("ctc_categories", [ id: 27, name: "syndromes" ], primaryKey: false)
        insert("ctc_categories", [ id: 28, name: "vascular" ], primaryKey: false)

        // all are in v3.0
        insert("ctc_version_categories", [ version_id: 3, category_id:  1 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  2 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  3 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  4 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  5 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  6 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  7 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  8 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id:  9 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 10 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 11 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 12 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 13 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 14 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 15 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 16 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 17 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 18 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 19 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 20 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 21 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 22 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 23 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 24 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 25 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 26 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 27 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 3, category_id: 28 ], primaryKey: false)

        // v2.0 doesn't include death (8), growth (12), surgery (26), or vascular (28)
        insert("ctc_version_categories", [ version_id: 2, category_id:  1 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id:  2 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id:  3 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id:  4 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id:  5 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id:  6 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id:  7 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id:  9 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 10 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 11 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 13 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 14 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 15 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 16 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 17 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 18 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 19 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 20 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 21 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 22 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 23 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 24 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 25 ], primaryKey: false)
        insert("ctc_version_categories", [ version_id: 2, category_id: 27 ], primaryKey: false)

        // FKs
        execute('ALTER TABLE ctc_version_categories ADD CONSTRAINT fk_ctc_ver_cat_ver FOREIGN KEY (version_id) REFERENCES ctc_versions')
        execute('ALTER TABLE ctc_version_categories ADD CONSTRAINT fk_ctc_ver_cat_cat FOREIGN KEY (category_id) REFERENCES ctc_categories')
    }

    void down() {
        dropTable("ctc_version_categories", primaryKey: false)
        dropTable("ctc_categories", primaryKey: false)
        dropTable("ctc_versions", primaryKey: false)
    }
}