package gov.nih.nci.ess.sr.service.safetyreporttransaction.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessible on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public interface SafetyReportTransactionI {

  public sr.SafetyReportVersion amendSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,ess.caaers.nci.nih.gov.Id amendmentIdentifier,_21090.org.iso.ST reasonForAmend) throws RemoteException ;

  public sr.SafetyReportVersion submitSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,ess.caaers.nci.nih.gov.Id submitterIdentifier,_21090.org.iso.DSET_II additionalRecipientIdentifiers) throws RemoteException ;

  public sr.SafetyReportVersion withdrawSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,ess.caaers.nci.nih.gov.Id withdrawerIdentifier) throws RemoteException ;

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

}

