package gov.nih.nci.ess.ae.service.aeadvancedquery.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.AEAdvancedQueryPortType;
import gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.service.AEAdvancedQueryServiceAddressingLocator;
import gov.nih.nci.ess.ae.service.aeadvancedquery.common.AEAdvancedQueryI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class AEAdvancedQueryClient extends AEAdvancedQueryClientBase implements AEAdvancedQueryI {	

	public AEAdvancedQueryClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public AEAdvancedQueryClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public AEAdvancedQueryClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public AEAdvancedQueryClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(AEAdvancedQueryClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  AEAdvancedQueryClient client = new AEAdvancedQueryClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public ess.caaers.nci.nih.gov.AdverseEvent[] queryAdverseEvents(ess.caaers.nci.nih.gov.AdverseEventQuery adverseEventQuery,ess.caaers.nci.nih.gov.LimitOffset limitOffset) throws RemoteException, gov.nih.nci.ess.ae.service.management.stubs.types.AdverseEventServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"queryAdverseEvents");
    gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.QueryAdverseEventsRequest params = new gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.QueryAdverseEventsRequest();
    gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.QueryAdverseEventsRequestAdverseEventQuery adverseEventQueryContainer = new gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.QueryAdverseEventsRequestAdverseEventQuery();
    adverseEventQueryContainer.setAdverseEventQuery(adverseEventQuery);
    params.setAdverseEventQuery(adverseEventQueryContainer);
    gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.QueryAdverseEventsRequestLimitOffset limitOffsetContainer = new gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.QueryAdverseEventsRequestLimitOffset();
    limitOffsetContainer.setLimitOffset(limitOffset);
    params.setLimitOffset(limitOffsetContainer);
    gov.nih.nci.ess.ae.service.aeadvancedquery.stubs.QueryAdverseEventsResponse boxedResult = portType.queryAdverseEvents(params);
    return boxedResult.getAdverseEvent();
    }
  }

}
