package gov.nih.nci.ess.sr.service.safetyreportadvancedquery.service.globus;

import gov.nih.nci.ess.sr.service.safetyreportadvancedquery.service.SafetyReportAdvancedQueryImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the SafetyReportingImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correctly mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportAdvancedQueryProviderImpl{
	
	SafetyReportAdvancedQueryImpl impl;
	
	public SafetyReportAdvancedQueryProviderImpl() throws RemoteException {
		impl = new SafetyReportAdvancedQueryImpl();
	}
	

    public gov.nih.nci.ess.sr.service.safetyreportadvancedquery.stubs.GetSafetyReportSummaryDataResponse getSafetyReportSummaryData(gov.nih.nci.ess.sr.service.safetyreportadvancedquery.stubs.GetSafetyReportSummaryDataRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportadvancedquery.stubs.GetSafetyReportSummaryDataResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportadvancedquery.stubs.GetSafetyReportSummaryDataResponse();
    impl.getSafetyReportSummaryData();
    return boxedResult;
  }

}
