package gov.nih.nci.ess.safetyreporting.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface SafetyReportingEnterpriseServiceConstantsBase {
	public static final String SERVICE_NS = "http://safetyreporting.ess.nci.nih.gov/SafetyReportingEnterpriseService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "SafetyReportingEnterpriseServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "SafetyReportingEnterpriseServiceResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
