package gov.nih.nci.cabig.caaers.grid.service.globus;

import gov.nih.nci.cabig.caaers.grid.service.StudyServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the StudyServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class StudyServiceProviderImpl{
	
	StudyServiceImpl impl;
	
	public StudyServiceProviderImpl() throws RemoteException {
		impl = new StudyServiceImpl();
	}
	

	public gov.nih.nci.cabig.caaers.grid.stubs.AssignParticipantResponse assignParticipant(gov.nih.nci.cabig.caaers.grid.stubs.AssignParticipantRequest params) throws RemoteException {
		StudyServiceAuthorization.authorizeAssignParticipant();
		gov.nih.nci.cabig.caaers.grid.stubs.AssignParticipantResponse boxedResult = new gov.nih.nci.cabig.caaers.grid.stubs.AssignParticipantResponse();
		boxedResult.setStudyParticipantAssignment(impl.assignParticipant(params.getStudy().getStudy(),params.getParticipant().getParticipant(),params.getSite().getSite()));
		return boxedResult;
	}

}
