connect schema_user/schema_user
drop user caaers_selenium cascade;
CREATE USER "CAAERS_SELENIUM" PROFILE "DEFAULT" IDENTIFIED BY 
"CAAERS_SELENIUM" DEFAULT TABLESPACE "CAAERSDATA" TEMPORARY TABLESPACE 
"TEMP" QUOTA UNLIMITED ON "CAAERSDATA" QUOTA UNLIMITED ON "CAAERSINDEX" 
ACCOUNT UNLOCK;
GRANT "CAAERS_ROLE" TO "CAAERS_SELENIUM";
GRANT "CONNECT" TO "CAAERS_SELENIUM";
exit;
 /
