package gov.nih.nci.cabig.caaers.domain.workflow;

import gov.nih.nci.cabig.ctms.domain.AbstractMutableDomainObject;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
 

/**
 * This class represents a review comment added by the user.
 *
 * @author biju
 */
@Entity
@Table(name = "wf_review_comments")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "dtype", discriminatorType = DiscriminatorType.STRING)
@DiscriminatorValue("dtype")
@GenericGenerator(name = "id-generator", strategy = "native", parameters = {@Parameter(name = "sequence", value = "seq_wf_review_comments_id")})

public class ReviewComment extends AbstractMutableDomainObject{
	
	/** The comment. */
	private String comment;
	
	/** The date. */
	private Date date;
	
	/** The auto generated text. */
	private String autoGeneratedText;
	
	/** The editable. */
	private Boolean editable;
	
	/** The user id. */
	private String userId;
	
	/**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
	@Column(name="user_id")
	public String getUserId(){
		return userId;
	}
	
	/**
	 * Sets the user id.
	 *
	 * @param userId the new user id
	 */
	public void setUserId(String userId){
		this.userId = userId;
	}
	
	/**
	 * Gets the editable.
	 *
	 * @return the editable
	 */
	@Column(name="editable")
	public Boolean getEditable(){
		return editable;
	}
	
	/**
	 * Sets the editable.
	 *
	 * @param editable the new editable
	 */
	public void setEditable(Boolean editable){
		this.editable = editable;
	}
	
	/**
	 * Gets the user comment.
	 *
	 * @return the user comment
	 */
	@Column(name="user_comment")
	public String getUserComment() {
		return comment;
	}
	
	/**
	 * Sets the user comment.
	 *
	 * @param comment the new user comment
	 */
	public void setUserComment(String comment) {
		this.comment = comment;
	}
	
	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Column(name="created_date")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getCreatedDate() {
		return date;
	}
	
	/**
	 * Sets the created date.
	 *
	 * @param date the new created date
	 */
	public void setCreatedDate(Date date) {
		this.date = date;
	}
	
	/**
	 * Gets the auto generated text.
	 *
	 * @return the auto generated text
	 */
	@Column(name="auto_text")
	public String getAutoGeneratedText() {
		return autoGeneratedText;
	}
	
	/**
	 * Sets the auto generated text.
	 *
	 * @param autoGeneratedText the new auto generated text
	 */
	public void setAutoGeneratedText(String autoGeneratedText) {
		this.autoGeneratedText = autoGeneratedText;
	}
	
	/**
	 * Gets the full comment.
	 *
	 * @return the full comment
	 */
	@Transient
	public String getFullComment() {
		StringBuilder sb = new StringBuilder();
		if(autoGeneratedText != null) sb.append(autoGeneratedText);
		if(comment != null) sb.append(" : " +  comment);
		return sb.toString();
		
	}

}
