class ModifyChemoAgent extends edu.northwestern.bioinformatics.bering.Migration {
    void up() {
      	addColumn("chemo_agents","generic_name", "string");
      	
      	execute("update chemo_agents set generic_name='Interferon Gamma' where name = 'Actimmune'")
		execute("update chemo_agents set generic_name='Doxorubicin' where name = 'Adriamycin, RUBEX'")
		execute("update chemo_agents set generic_name='Fluorouracil' where name = 'Adrucil, Efudex, Fluroplex'")
	execute("update chemo_agents set generic_name='Melphalan' where name = 'Alkeran'")
	execute("update chemo_agents set generic_name='Anastrozole' where name = 'Arimidex'")
	execute("update chemo_agents set generic_name='Carmustine (BCNU)' where name = 'BiCNU'")
	execute("update chemo_agents set generic_name='Bleomycin' where name = 'Blenoxane'")
	execute("update chemo_agents set generic_name='Irinotecan (CPT-11)' where name = 'Camptosar'")
	execute("update chemo_agents set generic_name='Bicalutamide' where name = 'Casodex'")
	execute("update chemo_agents set generic_name='Lomustine (CCNU)' where name = 'CeeNU'")
	execute("update chemo_agents set generic_name='Daunorubicin (Daunomycin)' where name = 'Cerubidine'")
	execute("update chemo_agents set generic_name='Dactinomycin (Actinomycin D)' where name = 'Cosmegen'")
	execute("update chemo_agents set generic_name='Aminoglutethimide' where name = 'Cytadren'")
	execute("update chemo_agents set generic_name='Cytarabine (Cytosine Arabinoside, Ara-C)' where name = 'Cytosar-U'")
	execute("update chemo_agents set generic_name='Cyclophosphamide' where name = 'Cytoxan, Neosar'")
	execute("update chemo_agents set generic_name='Diethylstilbesterol (DES)' where name = 'DES'")
	execute("update chemo_agents set generic_name='Dacarbazine' where name = 'DTIC-Dome'")
	execute("update chemo_agents set generic_name='Hydroxyprogesterone' where name = 'Delalutin'")
	execute("update chemo_agents set generic_name='Prednisone' where name = 'Deltasone'")
	execute("update chemo_agents set generic_name='Doxorubicin Liposome Injection' where name = 'Doxil'")
	execute("update chemo_agents set generic_name='Dromostanolone' where name = 'Drolban'")
	execute("update chemo_agents set generic_name='L-Asparaginase' where name = 'Elspar'")
	execute("update chemo_agents set generic_name='Estramustine' where name = 'Emcyt'")
	execute("update chemo_agents set generic_name='Levamisole' where name = 'Ergamisol'")
	execute("update chemo_agents set generic_name='Ethinyl Estradiol' where name = 'Estinyl'")
	execute("update chemo_agents set generic_name='Flutamide' where name = 'Eulexin'")
	execute("update chemo_agents set generic_name='Floxuridine' where name = 'FUDR'")
	execute("update chemo_agents set generic_name='Toremifene' where name = 'Fareston'")
	execute("update chemo_agents set generic_name='Letrozole' where name = 'Femara'")
	execute("update chemo_agents set generic_name='Fludarabine Phosphate' where name = 'Fludara'")
	execute("update chemo_agents set generic_name='Methotrexate' where name = 'Folex, Mexate'")
	execute("update chemo_agents set generic_name='Gemcitabine' where name = 'Gemzar'")
	execute("update chemo_agents set generic_name='Carmustine Wafers' where name = 'Gliadel Wafers'")
	execute("update chemo_agents set generic_name='Fluoxymesterone' where name = 'Halotestin'")
	execute("update chemo_agents set generic_name='Trastuzumab' where name = 'Herceptin'")
	execute("update chemo_agents set generic_name='Altretamine (Hexamethylmelamine)' where name = 'Hexalen'")
	execute("update chemo_agents set generic_name='Topotecan' where name = 'Hycamtin'")
	execute("update chemo_agents set generic_name='Hydroxyurea' where name = 'Hydrea'")
	execute("update chemo_agents set generic_name='Idarubicin' where name = 'Idamycin'")
	execute("update chemo_agents set generic_name='Ifosfamide' where name = 'Ifex'")
	execute("update chemo_agents set generic_name='Interferon Alpha' where name = 'Intron A, Roferon A'")
	execute("update chemo_agents set generic_name='Chlorambucil' where name = 'Leukeran'")
	execute("update chemo_agents set generic_name='Sargramostim (GM-CSF)' where name = 'Leukine'")
	execute("update chemo_agents set generic_name='Cladribine, (Chlorodeoxyadenosine)' where name = 'Leustatin'")
	execute("update chemo_agents set generic_name='Leuprolide' where name = 'Lupron'")
	execute("update chemo_agents set generic_name='Mitotane (o-p-DDD)' where name = 'Lysodren'")
	execute("update chemo_agents set generic_name='Procarbazine' where name = 'Matulane'")
	execute("update chemo_agents set generic_name='Megestrol Acetate' where name = 'Megace'")
	execute("update chemo_agents set generic_name='Mithramycin (Plicamycin)' where name = 'Mithracin'")
	execute("update chemo_agents set generic_name='Mechlorethamine' where name = 'Mustargen'")
	execute("update chemo_agents set generic_name='Mitomycin C' where name = 'Mutamycin'")
	execute("update chemo_agents set generic_name='Busulfan' where name = 'Myleran'")
	execute("update chemo_agents set generic_name='Vinorelbine' where name = 'Navelbine'")
	execute("update chemo_agents set generic_name='Oprelvekin (Interleukin-11)' where name = 'Neumaga'")
	execute("update chemo_agents set generic_name='Filgrastim (G-CSF)' where name = 'Neuprogen'")
	execute("update chemo_agents set generic_name='Nilutamide' where name = 'Nilandron'")
	execute("update chemo_agents set generic_name='Pentostatin' where name = 'Nipent'")
	execute("update chemo_agents set generic_name='Tamoxifen' where name = 'Nolvadex'")
	execute("update chemo_agents set generic_name='Mitoxantrone' where name = 'Novantrone'")
	execute("update chemo_agents set generic_name='Vincristine' where name = 'Oncovin, Vincasar'")
	execute("update chemo_agents set generic_name='Carboplatin' where name = 'Paraplatin'")
	execute("update chemo_agents set generic_name='Porfimer Sodium' where name = 'Photofrin'")
	execute("update chemo_agents set generic_name='Cisplatin' where name = 'Platinol'")
	execute("update chemo_agents set generic_name='Aldesleukin (Interleukin-2, IL-2)' where name = 'Proleukin'")
	execute("update chemo_agents set generic_name='Medroxyprogesterone Acetate' where name = 'Provera, Depo-Provera'")
	execute("update chemo_agents set generic_name='Mercaptopurine' where name = 'Purinethol'")
	execute("update chemo_agents set generic_name='Rituximab' where name = 'Rituxan'")
	execute("update chemo_agents set generic_name='Talc (Intrapleural)' where name = 'Sclerosol'")
	execute("update chemo_agents set generic_name='Chlorotrianisene' where name = 'TACE'")
	execute("update chemo_agents set generic_name='Paclitaxel' where name = 'Taxol'")
	execute("update chemo_agents set generic_name='Docetaxel' where name = 'Taxotere'")
	execute("update chemo_agents set generic_name='Testolactone' where name = 'Teslac'")
	execute("update chemo_agents set generic_name='BCG' where name = 'TheraCys, TICE'")
	execute("update chemo_agents set generic_name='Thioguanine' where name = 'Thioguanine'")
	execute("update chemo_agents set generic_name='Thiotepa' where name = 'Thiotepa'")
	execute("update chemo_agents set generic_name='TEM' where name = 'Triethyl Melamine'")
	execute("update chemo_agents set generic_name='Uracil Mustard' where name = 'Uracil Mustard'")
	execute("update chemo_agents set generic_name='Valrubicin' where name = 'Valstar'")
	execute("update chemo_agents set generic_name='Methyl Prednisolone' where name = 'Various' and id=1055")
	execute("update chemo_agents set generic_name='Methyltestosterone' where name = 'Various' and id=1056")
	execute("update chemo_agents set generic_name='Prednisolone' where name = 'Various' and id=1067")
	execute("update chemo_agents set generic_name='Testosterone' where name = 'Various' and id=1078")
	execute("update chemo_agents set generic_name='Triamcinolone' where name = 'Various' and id=1085")
	execute("update chemo_agents set generic_name='Etoposide (VP-16)' where name = 'VePesid'")
	execute("update chemo_agents set generic_name='Vinblastine' where name = 'Velban'")
	execute("update chemo_agents set generic_name='Pipobroman' where name = 'Vercyte'")
	execute("update chemo_agents set generic_name='Tretinoin (All-Trans Retinoic Acid)' where name = 'Vesanoid'")
	execute("update chemo_agents set generic_name='Teniposide (VM-26)' where name = 'Vumon'")
	execute("update chemo_agents set generic_name='Capecitabine' where name = 'Xeloda'")
	execute("update chemo_agents set generic_name='Streptozotocin' where name = 'Zanosar'")
	execute("update chemo_agents set generic_name='Goserelin' where name = 'Zoladex'")
	
    }

    void down() {
    	 dropColumn("chemo_agents", "start_date");
    }
}