DROP SEQUENCE CSM_APPLICATI_APPLICATION__SEQ;
DROP TABLE CSM_APPLICATION CASCADE;

DROP SEQUENCE CSM_GROUP_GROUP_ID_SEQ;
DROP TABLE CSM_GROUP CASCADE;

DROP SEQUENCE CSM_PRIVILEGE_PRIVILEGE_ID_SEQ;
DROP TABLE CSM_PRIVILEGE CASCADE;

DROP SEQUENCE CSM_PROTECTIO_PROTECTION_E_SEQ;
DROP TABLE CSM_PROTECTION_ELEMENT CASCADE;

DROP SEQUENCE CSM_PROTECTIO_PROTECTION_G_SEQ;
DROP TABLE CSM_PROTECTION_GROUP CASCADE;

DROP SEQUENCE CSM_PG_PE_ID_SEQ;
DROP TABLE CSM_PG_PE CASCADE;

DROP SEQUENCE CSM_ROLE_ROLE_ID_SEQ;
DROP TABLE CSM_ROLE CASCADE;

DROP SEQUENCE CSM_ROLE_PRIV_SEQ;
DROP TABLE CSM_ROLE_PRIVILEGE CASCADE;

DROP SEQUENCE CSM_USER_USER_ID_SEQ;
DROP TABLE CSM_USER CASCADE;

DROP SEQUENCE CSM_USER_GROUP_ID_SEQ;
DROP TABLE CSM_USER_GROUP CASCADE;

DROP SEQUENCE CSM_USER_GROU_USER_GROUP_R_SEQ;
DROP TABLE CSM_USER_GROUP_ROLE_PG CASCADE;

DROP SEQUENCE CSM_USER_PE_USER_PROTECTIO_SEQ;
DROP TABLE CSM_USER_PE CASCADE;