package gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.service.globus;

import gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.service.SafetyReportRulesManagementImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the SafetyReportingImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correctly mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportRulesManagementProviderImpl{
	
	SafetyReportRulesManagementImpl impl;
	
	public SafetyReportRulesManagementProviderImpl() throws RemoteException {
		impl = new SafetyReportRulesManagementImpl();
	}
	

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateOrganizationSafetyReportingRulesResponse createOrganizationSafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateOrganizationSafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateOrganizationSafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateOrganizationSafetyReportingRulesResponse();
    impl.createOrganizationSafetyReportingRules();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateOrganizationSafetyReportingRulesResponse updateOrganizationSafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateOrganizationSafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateOrganizationSafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateOrganizationSafetyReportingRulesResponse();
    impl.updateOrganizationSafetyReportingRules();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateOrganizationSafetyReportingRulesResponse deactivateOrganizationSafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateOrganizationSafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateOrganizationSafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateOrganizationSafetyReportingRulesResponse();
    impl.deactivateOrganizationSafetyReportingRules();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateStudySafetyReportingRulesResponse createStudySafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateStudySafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateStudySafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.CreateStudySafetyReportingRulesResponse();
    impl.createStudySafetyReportingRules();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateStudySafetyReportingRulesResponse updateStudySafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateStudySafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateStudySafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.UpdateStudySafetyReportingRulesResponse();
    impl.updateStudySafetyReportingRules();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateStudySafetyReportingRulesResponse deactivateStudySafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateStudySafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateStudySafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.DeactivateStudySafetyReportingRulesResponse();
    impl.deactivateStudySafetyReportingRules();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.QuerySafetyReportingRulesResponse querySafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.QuerySafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.QuerySafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.QuerySafetyReportingRulesResponse();
    impl.querySafetyReportingRules();
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.GetSafetyReportingRulesResponse getSafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.GetSafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.GetSafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.stubs.GetSafetyReportingRulesResponse();
    impl.getSafetyReportingRules();
    return boxedResult;
  }

}
