#!/bin/sh
# Developer shortcut script for doing mvn install in core.  Set up so it can be run from any
# directory.  E.g.:
#
#  web$ ../core/install
#
# Ensures that you don't accidentally burn your deploy database (e.g., by running tests in 
# your IDE) by immediately doing a compile using the hsqldb database configuration if the
# install succeeds.

cd `dirname $0`
mvn -o clean install && mvn -o -Ddb=hsqldb clean bering:hsqldb test-compile
