package gov.nih.nci.ess.safetyreporting.ruleseval.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class SafetyReportRulesEvaluationImpl extends SafetyReportRulesEvaluationImplBase {

	
	public SafetyReportRulesEvaluationImpl() throws RemoteException {
		super();
	}
	
  public gov.nih.nci.ess.safetyreporting.types.DSET_ReportDefinition evaluateAgainstSafetyReportingRules(ess.caaers.nci.nih.gov.Id adverseEventId,ess.caaers.nci.nih.gov.Id problemId,ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Id organizationId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

