#created on: Jan 10, 2007
package gov.nih.nci.cabig.caaers.rules

import gov.nih.nci.cabig.caaers.domain.Study;
#list any import classes here.



#declare any global variables here




rule "Decide AE Type"
	
	when
		$study1 : Study($primarySponsorCode1 : primarySponsorCode)
		$study2 : Study($primarySponsorCode2 : primarySponsorCode)
		eval( $primarySponsorCode1 == "SC_1" )
		#conditions
	then 
		System.out.println("Found a SAE with SponsorCode = " + $study1.getPrimarySponsorCode());
		#actions
		
end

rule "Second Rule"
	#include attributes such as "salience" here...
	when
		#conditions
	then 
		#actions
		
end
