package gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.service.globus;

import gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.service.SafetyReportRulesEvaluationImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the SafetyReportingImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correctly mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportRulesEvaluationProviderImpl{
	
	SafetyReportRulesEvaluationImpl impl;
	
	public SafetyReportRulesEvaluationProviderImpl() throws RemoteException {
		impl = new SafetyReportRulesEvaluationImpl();
	}
	

    public gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.stubs.EvaluateAgainstSafetyReportingRulesResponse evaluateAgainstSafetyReportingRules(gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.stubs.EvaluateAgainstSafetyReportingRulesRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.stubs.EvaluateAgainstSafetyReportingRulesResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreportrulesevaluation.stubs.EvaluateAgainstSafetyReportingRulesResponse();
    impl.evaluateAgainstSafetyReportingRules();
    return boxedResult;
  }

}
