class PopulateChemoAgents extends edu.northwestern.bioinformatics.bering.Migration {
    void up() {
        // Have to break up the inserts so as not to exceed the java max method length
        m0()
        m1()
        m2()
        m3()
    }

    void m0() {
        // all0 (25 terms)
        insert('chemo_agents', [ id: 1000, name: "Hexalen"], primaryKey: false)
        insert('chemo_agents', [ id: 1001, name: "Proleukin"], primaryKey: false)
        insert('chemo_agents', [ id: 1002, name: "Cytadren"], primaryKey: false)
        insert('chemo_agents', [ id: 1003, name: "Arimidex"], primaryKey: false)
        insert('chemo_agents', [ id: 1004, name: "TheraCys, TICE"], primaryKey: false)
        insert('chemo_agents', [ id: 1005, name: "Casodex"], primaryKey: false)
        insert('chemo_agents', [ id: 1006, name: "Blenoxane"], primaryKey: false)
        insert('chemo_agents', [ id: 1007, name: "Myleran"], primaryKey: false)
        insert('chemo_agents', [ id: 1008, name: "Xeloda"], primaryKey: false)
        insert('chemo_agents', [ id: 1009, name: "Paraplatin"], primaryKey: false)
        insert('chemo_agents', [ id: 1010, name: "BiCNU"], primaryKey: false)
        insert('chemo_agents', [ id: 1011, name: "Gliadel Wafers"], primaryKey: false)
        insert('chemo_agents', [ id: 1012, name: "Leukeran"], primaryKey: false)
        insert('chemo_agents', [ id: 1013, name: "Leustatin"], primaryKey: false)
        insert('chemo_agents', [ id: 1014, name: "TACE"], primaryKey: false)
        insert('chemo_agents', [ id: 1015, name: "Platinol"], primaryKey: false)
        insert('chemo_agents', [ id: 1016, name: "Cytoxan, Neosar"], primaryKey: false)
        insert('chemo_agents', [ id: 1017, name: "Cytosar-U"], primaryKey: false)
        insert('chemo_agents', [ id: 1018, name: "DTIC-Dome"], primaryKey: false)
        insert('chemo_agents', [ id: 1019, name: "Cosmegen"], primaryKey: false)
        insert('chemo_agents', [ id: 1020, name: "Cerubidine"], primaryKey: false)
        insert('chemo_agents', [ id: 1021, name: "DES"], primaryKey: false)
        insert('chemo_agents', [ id: 1022, name: "Taxotere"], primaryKey: false)
        insert('chemo_agents', [ id: 1023, name: "Adriamycin, RUBEX"], primaryKey: false)
        insert('chemo_agents', [ id: 1024, name: "Doxil"], primaryKey: false)
    }

    void m1() {
        // all1 (25 terms)
        insert('chemo_agents', [ id: 1025, name: "Drolban"], primaryKey: false)
        insert('chemo_agents', [ id: 1026, name: "Emcyt"], primaryKey: false)
        insert('chemo_agents', [ id: 1027, name: "Estinyl"], primaryKey: false)
        insert('chemo_agents', [ id: 1028, name: "VePesid"], primaryKey: false)
        insert('chemo_agents', [ id: 1029, name: "Neuprogen"], primaryKey: false)
        insert('chemo_agents', [ id: 1030, name: "FUDR"], primaryKey: false)
        insert('chemo_agents', [ id: 1031, name: "Fludara"], primaryKey: false)
        insert('chemo_agents', [ id: 1032, name: "Adrucil, Efudex, Fluroplex"], primaryKey: false)
        insert('chemo_agents', [ id: 1033, name: "Halotestin"], primaryKey: false)
        insert('chemo_agents', [ id: 1034, name: "Eulexin"], primaryKey: false)
        insert('chemo_agents', [ id: 1035, name: "Gemzar"], primaryKey: false)
        insert('chemo_agents', [ id: 1036, name: "Zoladex"], primaryKey: false)
        insert('chemo_agents', [ id: 1037, name: "Hydrea"], primaryKey: false)
        insert('chemo_agents', [ id: 1038, name: "Delalutin"], primaryKey: false)
        insert('chemo_agents', [ id: 1039, name: "Idamycin"], primaryKey: false)
        insert('chemo_agents', [ id: 1040, name: "Ifex"], primaryKey: false)
        insert('chemo_agents', [ id: 1041, name: "Intron A, Roferon A"], primaryKey: false)
        insert('chemo_agents', [ id: 1042, name: "Actimmune"], primaryKey: false)
        insert('chemo_agents', [ id: 1043, name: "Camptosar"], primaryKey: false)
        insert('chemo_agents', [ id: 1044, name: "Elspar"], primaryKey: false)
        insert('chemo_agents', [ id: 1045, name: "Femara"], primaryKey: false)
        insert('chemo_agents', [ id: 1046, name: "Lupron"], primaryKey: false)
        insert('chemo_agents', [ id: 1047, name: "Ergamisol"], primaryKey: false)
        insert('chemo_agents', [ id: 1048, name: "CeeNU"], primaryKey: false)
        insert('chemo_agents', [ id: 1049, name: "Mustargen"], primaryKey: false)
    }

    void m2() {
        // all2 (25 terms)
        insert('chemo_agents', [ id: 1050, name: "Provera, Depo-Provera"], primaryKey: false)
        insert('chemo_agents', [ id: 1051, name: "Megace"], primaryKey: false)
        insert('chemo_agents', [ id: 1052, name: "Alkeran"], primaryKey: false)
        insert('chemo_agents', [ id: 1053, name: "Purinethol"], primaryKey: false)
        insert('chemo_agents', [ id: 1054, name: "Folex, Mexate"], primaryKey: false)
        insert('chemo_agents', [ id: 1055, name: "Various"], primaryKey: false)
        insert('chemo_agents', [ id: 1056, name: "Various"], primaryKey: false)
        insert('chemo_agents', [ id: 1057, name: "Mithracin"], primaryKey: false)
        insert('chemo_agents', [ id: 1058, name: "Mutamycin"], primaryKey: false)
        insert('chemo_agents', [ id: 1059, name: "Lysodren"], primaryKey: false)
        insert('chemo_agents', [ id: 1060, name: "Novantrone"], primaryKey: false)
        insert('chemo_agents', [ id: 1061, name: "Nilandron"], primaryKey: false)
        insert('chemo_agents', [ id: 1062, name: "Neumaga"], primaryKey: false)
        insert('chemo_agents', [ id: 1063, name: "Taxol"], primaryKey: false)
        insert('chemo_agents', [ id: 1064, name: "Nipent"], primaryKey: false)
        insert('chemo_agents', [ id: 1065, name: "Vercyte"], primaryKey: false)
        insert('chemo_agents', [ id: 1066, name: "Photofrin"], primaryKey: false)
        insert('chemo_agents', [ id: 1067, name: "Various"], primaryKey: false)
        insert('chemo_agents', [ id: 1068, name: "Deltasone"], primaryKey: false)
        insert('chemo_agents', [ id: 1069, name: "Matulane"], primaryKey: false)
        insert('chemo_agents', [ id: 1070, name: "Rituxan"], primaryKey: false)
        insert('chemo_agents', [ id: 1071, name: "Leukine"], primaryKey: false)
        insert('chemo_agents', [ id: 1072, name: "Zanosar"], primaryKey: false)
        insert('chemo_agents', [ id: 1073, name: "Sclerosol"], primaryKey: false)
        insert('chemo_agents', [ id: 1074, name: "Nolvadex"], primaryKey: false)
    }

    void m3() {
        // all3 (16 terms)
        insert('chemo_agents', [ id: 1075, name: "Triethyl Melamine"], primaryKey: false)
        insert('chemo_agents', [ id: 1076, name: "Vumon"], primaryKey: false)
        insert('chemo_agents', [ id: 1077, name: "Teslac"], primaryKey: false)
        insert('chemo_agents', [ id: 1078, name: "Various"], primaryKey: false)
        insert('chemo_agents', [ id: 1079, name: "Thioguanine"], primaryKey: false)
        insert('chemo_agents', [ id: 1080, name: "Thiotepa"], primaryKey: false)
        insert('chemo_agents', [ id: 1081, name: "Hycamtin"], primaryKey: false)
        insert('chemo_agents', [ id: 1082, name: "Fareston"], primaryKey: false)
        insert('chemo_agents', [ id: 1083, name: "Herceptin"], primaryKey: false)
        insert('chemo_agents', [ id: 1084, name: "Vesanoid"], primaryKey: false)
        insert('chemo_agents', [ id: 1085, name: "Various"], primaryKey: false)
        insert('chemo_agents', [ id: 1086, name: "Uracil Mustard"], primaryKey: false)
        insert('chemo_agents', [ id: 1087, name: "Valstar"], primaryKey: false)
        insert('chemo_agents', [ id: 1088, name: "Velban"], primaryKey: false)
        insert('chemo_agents', [ id: 1089, name: "Oncovin, Vincasar"], primaryKey: false)
        insert('chemo_agents', [ id: 1090, name: "Navelbine"], primaryKey: false)
    }

    void down() {
        execute("DELETE * FROM chemo_agents")
    }
}
