package gov.nih.nci.ess.sr.service.safetyreportquery.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessible on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public interface SafetyReportQueryI {

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

  public sr.DSET_SafetyReportVersion querySafetyReports(sr.SafetyReportVersion safetyReportVersion) throws RemoteException, gov.nih.nci.ess.sr.service.safetyreportquery.stubs.types.SafetyReportException ;

  public sr.DSET_SafetyReportVersion getSafetyReports(_21090.org.iso.DSET_II safetyReportIdentifiers) throws RemoteException, gov.nih.nci.ess.sr.service.safetyreportquery.stubs.types.SafetyReportException ;

  public sr.SafetyReportFormat viewSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,_21090.org.iso.ST desiredFormat) throws RemoteException, gov.nih.nci.ess.sr.service.safetyreportquery.stubs.types.SafetyReportException ;

}

