package gov.nih.nci.ess.sr.service.safetyreportquery.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.4
 */
public interface SafetyReportQueryConstantsBase {
	public static final String SERVICE_NS = "http://service.sr.ess.nci.nih.gov/SafetyReporting/SafetyReportQuery";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "SafetyReportQueryKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "SafetyReportQueryResourceProperties");
	public static final QName CURRENTTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "CurrentTime");
	public static final QName TERMINATIONTIME = new QName("http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd", "TerminationTime");
	
}
