package gov.nih.nci.ess.ae.service.aeadvancedquery.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface AEAdvancedQueryConstantsBase {
	public static final String SERVICE_NS = "http://service.ae.ess.nci.nih.gov/AdverseEventEnterpriseService/AEAdvancedQuery";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "AEAdvancedQueryKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "AEAdvancedQueryResourceProperties");
	
}
