package gov.nih.nci.ess.safetyreporting.review.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class SafetyReportReviewImpl extends SafetyReportReviewImplBase {

	
	public SafetyReportReviewImpl() throws RemoteException {
		super();
	}
	
  public gov.nih.nci.ess.safetyreporting.types.SafetyReportReview createSafetyReportReviewProcess(gov.nih.nci.ess.safetyreporting.types.SafetyReportReview safetyReportReview,ess.caaers.nci.nih.gov.Id reportDefinitionId,ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Id organizationId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.ess.safetyreporting.types.SafetyReportReview updateSafetyReportReviewProcess(gov.nih.nci.ess.safetyreporting.types.SafetyReportReview safetyReportReview,ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Id organizationId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public ess.caaers.nci.nih.gov.Bl deactivateSafetyReportReviewProcess(ess.caaers.nci.nih.gov.Id reviewProcessId,_21090.org.iso.ST reasonForDeactivation) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.ess.safetyreporting.types.SafetyReportReview getSafetyReportReviewProcess(ess.caaers.nci.nih.gov.Id reviewProcessId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.ess.safetyreporting.types.SafetyReportReview reviewSafetyReport(ess.caaers.nci.nih.gov.Id reviewProcessId,_21090.org.iso.ST reviewDispostion,ess.caaers.nci.nih.gov.Id reviewerid,ess.caaers.nci.nih.gov.TsDateTime timeOdReview,_21090.org.iso.ST comments) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

