package gov.nih.nci.ess.sr.service.safetyreportrulesmanagement.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessible on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public interface SafetyReportRulesManagementI {

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException ;

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException ;

  public void createOrganizationSafetyReportingRules() throws RemoteException ;

  public void updateOrganizationSafetyReportingRules() throws RemoteException ;

  public void deactivateOrganizationSafetyReportingRules() throws RemoteException ;

  public void createStudySafetyReportingRules() throws RemoteException ;

  public void updateStudySafetyReportingRules() throws RemoteException ;

  public void deactivateStudySafetyReportingRules() throws RemoteException ;

  public void querySafetyReportingRules() throws RemoteException ;

  public void getSafetyReportingRules() throws RemoteException ;

}

