OPTIONS (SKIP=1)
LOAD DATA
	INFILE 'course_agents.csv'
	DISCARDMAX 9999
	APPEND INTO TABLE course_agents
	fields terminated by ','
	optionally enclosed by '"' AND '"'
	trailing NULLCOLS
	(
		ID					    INTEGER EXTERNAL(10),
		GRID_ID					    CHAR,
		VERSION				    INTEGER EXTERNAL(10),
		TREATMENT_ID				    INTEGER EXTERNAL(10),
		LIST_INDEX				    INTEGER EXTERNAL(10),
		STUDY_AGENT_ID 				    INTEGER EXTERNAL(10),
		ADMINISTRATION_DELAY_MINUTES			    INTEGER EXTERNAL,
		DOSE_AMOUNT					    CHAR,
		DOSE_UNITS					    CHAR,
		DOSE_ROUTE					    CHAR,
		TOTAL_DOSE_THIS_COURSE 			    INTEGER EXTERNAL,
		DURATION_AND_SCHEDULE				    CHAR,
		LAST_ADMINISTERED_DATE 			   DATE "YYYY-MM-DD" NULLIF LAST_ADMINISTERED_DATE="",
		MODIFIED_DOSE_AMOUNT				    CHAR,
		MODIFIED_DOSE_UNITS				    CHAR,
		MODIFIED_DOSE_ROUTE				    CHAR,
		COMMENTS					    CHAR,
		LOT_NUMBER					    CHAR,
		FORMULATION					    CHAR,
		AGENT_ADJUSTMENT_CODE				    INTEGER EXTERNAL(10),
		DOSE_CODE				    INTEGER EXTERNAL(10),
		MODIFIED_DOSE_CODE			    INTEGER EXTERNAL(10),
		FIRST_ADMINISTERED_DATE			   DATE "YYYY-MM-DD" NULLIF FIRST_ADMINISTERED_DATE=""
	)

