
LOAD DATA
	INFILE 'csm_role.txt'
	DISCARDMAX 9999
	TRUNCATE INTO TABLE csm_role
	fields terminated by '\t'
	
	trailing NULLCOLS
	(
		ROLE_ID				    INTEGER EXTERNAL(38),
		ROLE_NAME				    CHAR(2000),
		ROLE_DESCRIPTION				    CHAR(2000),
		APPLICATION_ID 			    INTEGER EXTERNAL(38),
		ACTIVE_FLAG				    INTEGER EXTERNAL(1),
		UPDATE_DATE				   DATE "YYYY-MM-DD" NULLIF UPDATE_DATE=""
	)

