
LOAD DATA
	INFILE 'csm_pg_pe.txt'
	DISCARDMAX 9999
	TRUNCATE INTO TABLE csm_pg_pe
	fields terminated by '\t'
	
	trailing NULLCOLS
	(
		PG_PE_ID				    INTEGER EXTERNAL(38),
		PROTECTION_GROUP_ID			    INTEGER EXTERNAL(38),
		PROTECTION_ELEMENT_ID			    INTEGER EXTERNAL(38),
		UPDATE_DATE					   DATE "YYYY-MM-DD" NULLIF UPDATE_DATE=""
	)

