
LOAD DATA
CHARACTERSET UTF8
	INFILE 'searches.txt'
	DISCARDMAX 9999
	TRUNCATE INTO TABLE searches
	fields terminated by '\t'
	
	trailing NULLCOLS
	(
		ID					    INTEGER EXTERNAL(10),
		VERSION				    INTEGER EXTERNAL(10),
		LOGIN_ID				    CHAR(2000),
		NAME					    CHAR(2000),
		DESCRIPTION					    CHAR(2000),
		CREATED_DATE				   DATE "YYYY-MM-DD" NULLIF CREATED_DATE="",
		CRITERIA_XML				    CHAR(4000),
		GRID_ID					    CHAR(2000)
	)

