package gov.nih.nci.ess.sr.service.safetyreportmanagement.service.globus;


import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.Map;
import java.io.File;
import javax.security.auth.Subject;
import javax.xml.namespace.QName;
import javax.xml.rpc.handler.MessageContext;

import gov.nih.nci.cagrid.introduce.servicetools.security.AuthorizationExtension;
import org.globus.wsrf.impl.security.authorization.exceptions.AuthorizationException;
import org.globus.wsrf.impl.security.authorization.exceptions.CloseException;
import org.globus.wsrf.impl.security.authorization.exceptions.InitializeException;
import org.globus.wsrf.impl.security.authorization.exceptions.InvalidPolicyException;
import org.globus.wsrf.security.authorization.PDP;
import org.globus.wsrf.security.authorization.PDPConfig;
import org.globus.wsrf.config.ContainerConfig;
import org.w3c.dom.Node;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This is a PDP for use with the globus authorization callout.
 * This class will have a authorize method for each method on this grid service.
 * The method is responsible for making any authorization callouts required to satisfy the 
 * authorization requirements placed on each method call.  Each method will either return
 * upon a successful authorization or will throw an exception upon a failed authorization.
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportManagementAuthorization implements PDP {

	public static final String SERVICE_NAMESPACE = "http://service.sr.ess.nci.nih.gov/SafetyReporting/SafetyReportManagement";
	
	Map authorizationClassMap = new HashMap();
	
	
	public SafetyReportManagementAuthorization() {
	}
	
	protected String getServiceNamespace(){
		return SERVICE_NAMESPACE;
	}
	
	public static String getCallerIdentity() {
		String caller = org.globus.wsrf.security.SecurityManager.getManager().getCaller();
		if ((caller == null) || (caller.equals("<anonymous>"))) {
			return null;
		} else {
			return caller;
		}
	}
					
	public void authorizeGetServiceSecurityMetadata(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeDestroy(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeSetTerminationTime(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeInitiateSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeAssociateAEToSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeAssociateProblemToSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeDissociateAEFromSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeDissociateProblemFromSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateAdverseEventInformationInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateProblemInformationInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeAssociateStudyToSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeAssociateAdditionalInformationToSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeAssociateSubjectToSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeDissociateStudyFromSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeDissociatePersonFromSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateAttributionInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateInterventionInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateLabTestResultsInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateOtherPossibleCausesInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdatePatientClinicalMeasurementsInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdatePatientDiseaseHistoryInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdatePatientConMedsInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdatePatientPriorTherapiesInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdatePatientDemographicsInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateReporterInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateHealthcareProviderInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateSubmitterInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateProductProblemInformationInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdatePatientStatusInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdatePlannedInterventionInformationInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateNarrativeInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   				
	public void authorizeUpdateTreatmentInformationInSafetyReport(Subject peerSubject, MessageContext context, QName operation) throws AuthorizationException {
		
	}
	   
	
	public boolean isPermitted(Subject peerSubject, MessageContext context, QName operation)
		throws AuthorizationException {
		
		if(!operation.getNamespaceURI().equals(getServiceNamespace())){
		  return false;
		}
		if(operation.getLocalPart().equals("getServiceSecurityMetadata")){
			authorizeGetServiceSecurityMetadata(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("destroy")){
			authorizeDestroy(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("setTerminationTime")){
			authorizeSetTerminationTime(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("initiateSafetyReport")){
			authorizeInitiateSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("associateAEToSafetyReport")){
			authorizeAssociateAEToSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("associateProblemToSafetyReport")){
			authorizeAssociateProblemToSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("dissociateAEFromSafetyReport")){
			authorizeDissociateAEFromSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("dissociateProblemFromSafetyReport")){
			authorizeDissociateProblemFromSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateAdverseEventInformationInSafetyReport")){
			authorizeUpdateAdverseEventInformationInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateProblemInformationInSafetyReport")){
			authorizeUpdateProblemInformationInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("associateStudyToSafetyReport")){
			authorizeAssociateStudyToSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("associateAdditionalInformationToSafetyReport")){
			authorizeAssociateAdditionalInformationToSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("associateSubjectToSafetyReport")){
			authorizeAssociateSubjectToSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("dissociateStudyFromSafetyReport")){
			authorizeDissociateStudyFromSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("dissociatePersonFromSafetyReport")){
			authorizeDissociatePersonFromSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateAttributionInSafetyReport")){
			authorizeUpdateAttributionInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateInterventionInSafetyReport")){
			authorizeUpdateInterventionInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateLabTestResultsInSafetyReport")){
			authorizeUpdateLabTestResultsInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateOtherPossibleCausesInSafetyReport")){
			authorizeUpdateOtherPossibleCausesInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updatePatientClinicalMeasurementsInSafetyReport")){
			authorizeUpdatePatientClinicalMeasurementsInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updatePatientDiseaseHistoryInSafetyReport")){
			authorizeUpdatePatientDiseaseHistoryInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updatePatientConMedsInSafetyReport")){
			authorizeUpdatePatientConMedsInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updatePatientPriorTherapiesInSafetyReport")){
			authorizeUpdatePatientPriorTherapiesInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updatePatientDemographicsInSafetyReport")){
			authorizeUpdatePatientDemographicsInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateReporterInSafetyReport")){
			authorizeUpdateReporterInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateHealthcareProviderInSafetyReport")){
			authorizeUpdateHealthcareProviderInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateSubmitterInSafetyReport")){
			authorizeUpdateSubmitterInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateProductProblemInformationInSafetyReport")){
			authorizeUpdateProductProblemInformationInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updatePatientStatusInSafetyReport")){
			authorizeUpdatePatientStatusInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updatePlannedInterventionInformationInSafetyReport")){
			authorizeUpdatePlannedInterventionInformationInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateNarrativeInSafetyReport")){
			authorizeUpdateNarrativeInSafetyReport(peerSubject, context, operation);
			return true;
		} else if(operation.getLocalPart().equals("updateTreatmentInformationInSafetyReport")){
			authorizeUpdateTreatmentInformationInSafetyReport(peerSubject, context, operation);
			return true;
		} 		
		return false;
	}
	

	public Node getPolicy(Node query) throws InvalidPolicyException {
		return null;
	}


	public String[] getPolicyNames() {
		return null;
	}


	public Node setPolicy(Node policy) throws InvalidPolicyException {
		return null;
	}


	public void close() throws CloseException {


	}


	public void initialize(PDPConfig config, String name, String id) throws InitializeException {
    	try{
    		String serviceName = (String)config.getProperty(name, "serviceName");
    	    String etcPath = ContainerConfig.getBaseDirectory() + File.separator + (String)config.getProperty(name, "etcDirectoryPath");

    	
    	} catch (Exception e){
        	throw new InitializeException(e.getMessage(),e);
		}
	}
	
	
}
