package gov.nih.nci.ess.ae.service.protocol.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ess.ae.service.protocol.stubs.AEProtocolPortType;
import gov.nih.nci.ess.ae.service.protocol.stubs.service.AEProtocolServiceAddressingLocator;
import gov.nih.nci.ess.ae.service.protocol.common.AEProtocolI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class AEProtocolClient extends AEProtocolClientBase implements AEProtocolI {	

	public AEProtocolClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public AEProtocolClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public AEProtocolClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public AEProtocolClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(AEProtocolClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  AEProtocolClient client = new AEProtocolClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public void updateCodingTerminologyForStudy(ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Oid termCode,ess.caaers.nci.nih.gov.Oid termVersion,ess.caaers.nci.nih.gov.Oid otherMeddra) throws RemoteException, gov.nih.nci.ess.ae.service.management.stubs.types.AdverseEventServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"updateCodingTerminologyForStudy");
    gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequest params = new gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequest();
    gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestStudyId studyIdContainer = new gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestStudyId();
    studyIdContainer.setId(studyId);
    params.setStudyId(studyIdContainer);
    gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestTermCode termCodeContainer = new gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestTermCode();
    termCodeContainer.setOid(termCode);
    params.setTermCode(termCodeContainer);
    gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestTermVersion termVersionContainer = new gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestTermVersion();
    termVersionContainer.setOid(termVersion);
    params.setTermVersion(termVersionContainer);
    gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestOtherMeddra otherMeddraContainer = new gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyRequestOtherMeddra();
    otherMeddraContainer.setOid(otherMeddra);
    params.setOtherMeddra(otherMeddraContainer);
    gov.nih.nci.ess.ae.service.protocol.stubs.UpdateCodingTerminologyForStudyResponse boxedResult = portType.updateCodingTerminologyForStudy(params);
    }
  }

}
