class InsertReportTypeConfig extends edu.northwestern.bioinformatics.bering.Migration {
    void up(){
        insert("config_properties", [ code: 'billion pfu' , version: '0',name : 'billion pfu', description: 'billion pfu',config_type:'5'])
        insert("config_properties", [ code: 'cells' , version: '0',name : 'cells', description: 'cells',config_type:'5'])
        insert("config_properties", [ code: 'cGy' , version: '0',name : 'cGy', description: 'cGy',config_type:'5'])
        insert("config_properties", [ code: 'Ci' , version: '0',name : 'Ci', description: 'Ci',config_type:'5'])
        insert("config_properties", [ code: 'cm' , version: '0',name : 'cm', description: 'cm',config_type:'5'])
        insert("config_properties", [ code: 'dL' , version: '0',name : 'dL', description: 'dL',config_type:'5'])
        insert("config_properties", [ code: 'dm' , version: '0',name : 'dm', description: 'dm',config_type:'5'])
        insert("config_properties", [ code: 'Eq' , version: '0',name : 'Eq', description: 'Eq',config_type:'5'])
        insert("config_properties", [ code: 'g' , version: '0',name : 'g', description: 'g',config_type:'5'])
        insert("config_properties", [ code: 'gravity' , version: '0',name : 'gravity', description: 'gravity',config_type:'5'])
        insert("config_properties", [ code: 'Gy' , version: '0',name : 'Gy', description: 'Gy',config_type:'5'])
        insert("config_properties", [ code: 'Hz' , version: '0',name : 'Hz', description: 'Hz',config_type:'5'])
        insert("config_properties", [ code: 'IU' , version: '0',name : 'IU', description: 'IU',config_type:'5'])
        insert("config_properties", [ code: 'J/cm^2' , version: '0',name : 'J/cm^2', description: 'J/cm^2',config_type:'5'])
        insert("config_properties", [ code: 'keV' , version: '0',name : 'keV', description: 'keV',config_type:'5'])
        insert("config_properties", [ code: 'kg' , version: '0',name : 'kg', description: 'kg',config_type:'5'])
        insert("config_properties", [ code: 'kHz' , version: '0',name : 'kHz', description: 'kHz',config_type:'5'])
        insert("config_properties", [ code: 'kPa' , version: '0',name : 'kPa', description: 'kPa',config_type:'5'])
        insert("config_properties", [ code: 'L' , version: '0',name : 'L', description: 'L',config_type:'5'])
        insert("config_properties", [ code: 'm' , version: '0',name : 'm', description: 'm',config_type:'5'])
        insert("config_properties", [ code: 'mcCi' , version: '0',name : 'mcCi', description: 'mcCi',config_type:'5'])
        insert("config_properties", [ code: 'mcg' , version: '0',name : 'mcg', description: 'mcg',config_type:'5'])
        insert("config_properties", [ code: 'mCi' , version: '0',name : 'mCi', description: 'mCi',config_type:'5'])
        insert("config_properties", [ code: 'mcL' , version: '0',name : 'mcL', description: 'mcL',config_type:'5'])
        insert("config_properties", [ code: 'mcm' , version: '0',name : 'mcm', description: 'mcm',config_type:'5'])
        insert("config_properties", [ code: 'mEq' , version: '0',name : 'mEq', description: 'mEq',config_type:'5'])
        insert("config_properties", [ code: 'MeV' , version: '0',name : 'MeV', description: 'MeV',config_type:'5'])
        insert("config_properties", [ code: 'mg' , version: '0',name : 'mg', description: 'mg',config_type:'5'])
        insert("config_properties", [ code: 'MHz' , version: '0',name : 'MHz', description: 'MHz',config_type:'5'])
        insert("config_properties", [ code: 'million IU' , version: '0',name : 'million IU', description: 'million IU',config_type:'5'])
        insert("config_properties", [ code: 'million pfu' , version: '0',name : 'million pfu', description: 'million pfu',config_type:'5'])
        insert("config_properties", [ code: 'milliunit' , version: '0',name : 'milliunit', description: 'milliunit',config_type:'5'])
        insert("config_properties", [ code: 'mL' , version: '0',name : 'mL', description: 'mL',config_type:'5'])
        insert("config_properties", [ code: 'mm' , version: '0',name : 'mm', description: 'mm',config_type:'5'])
        insert("config_properties", [ code: 'MMM' , version: '0',name : 'MMM', description: 'MMM',config_type:'5'])
        insert("config_properties", [ code: 'mmol' , version: '0',name : 'mmol', description: 'mmol',config_type:'5'])
        insert("config_properties", [ code: 'mol' , version: '0',name : 'mol', description: 'mol',config_type:'5'])
        insert("config_properties", [ code: 'mOsmol' , version: '0',name : 'mOsmol', description: 'mOsmol',config_type:'5'])
        insert("config_properties", [ code: 'Mrad' , version: '0',name : 'Mrad', description: 'Mrad',config_type:'5'])
        insert("config_properties", [ code: 'MU' , version: '0',name : 'MU', description: 'MU',config_type:'5'])
        insert("config_properties", [ code: 'mV' , version: '0',name : 'mV', description: 'mV',config_type:'5'])
        insert("config_properties", [ code: 'mVP' , version: '0',name : 'mVP', description: 'mVP',config_type:'5'])
        insert("config_properties", [ code: 'N/A' , version: '0',name : 'N/A', description: 'N/A',config_type:'5'])
        insert("config_properties", [ code: 'nCi' , version: '0',name : 'nCi', description: 'nCi',config_type:'5'])
        insert("config_properties", [ code: 'ng' , version: '0',name : 'ng', description: 'ng',config_type:'5'])
        insert("config_properties", [ code: 'nm' , version: '0',name : 'nm', description: 'nm',config_type:'5'])
        insert("config_properties", [ code: 'nm light' , version: '0',name : 'nm light', description: 'nm light',config_type:'5'])
        insert("config_properties", [ code: 'Osmol' , version: '0',name : 'Osmol', description: 'Osmol',config_type:'5'])
        insert("config_properties", [ code: 'Pa' , version: '0',name : 'Pa', description: 'Pa',config_type:'5'])
        insert("config_properties", [ code: 'percent' , version: '0',name : 'percent', description: 'percent',config_type:'5'])
        insert("config_properties", [ code: 'pfu' , version: '0',name : 'pfu', description: 'pfu',config_type:'5'])
        insert("config_properties", [ code: 'pg' , version: '0',name : 'pg', description: 'pg',config_type:'5'])
        insert("config_properties", [ code: 'psi' , version: '0',name : 'psi', description: 'psi',config_type:'5'])
        insert("config_properties", [ code: 'TCID' , version: '0',name : 'TCID', description: 'TCID',config_type:'5'])
        insert("config_properties", [ code: 'unit' , version: '0',name : 'unit', description: 'unit',config_type:'5'])
        insert("config_properties", [ code: 'VP' , version: '0',name : 'VP', description: 'VP',config_type:'5'])
    }
    void down(){
        execute("delete config_properties where config_type = 5")
    }
}