package gov.nih.nci.ess.sr.service.safetyreportquery.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportQueryImpl extends SafetyReportQueryImplBase {

	
	public SafetyReportQueryImpl() throws RemoteException {
		super();
	}
	
  public sr.DSET_SafetyReportVersion querySafetyReports(sr.SafetyReportVersion safetyReportVersion) throws RemoteException, gov.nih.nci.ess.sr.service.safetyreportquery.stubs.types.SafetyReportException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public sr.DSET_SafetyReportVersion getSafetyReports(_21090.org.iso.DSET_II safetyReportIdentifiers) throws RemoteException, gov.nih.nci.ess.sr.service.safetyreportquery.stubs.types.SafetyReportException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public sr.SafetyReportFormat viewSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,_21090.org.iso.ST desiredFormat) throws RemoteException, gov.nih.nci.ess.sr.service.safetyreportquery.stubs.types.SafetyReportException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

