package gov.nih.nci.ess.sr.service.safetyreporttransaction.service.globus;

import gov.nih.nci.ess.sr.service.safetyreporttransaction.service.SafetyReportTransactionImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the SafetyReportingImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correctly mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportTransactionProviderImpl{
	
	SafetyReportTransactionImpl impl;
	
	public SafetyReportTransactionProviderImpl() throws RemoteException {
		impl = new SafetyReportTransactionImpl();
	}
	

    public gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.AmendSafetyReportResponse amendSafetyReport(gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.AmendSafetyReportRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.AmendSafetyReportResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.AmendSafetyReportResponse();
    boxedResult.setSafetyReportVersion(impl.amendSafetyReport(params.getSafetyReportIdentifier().getId(),params.getAmendmentIdentifier().getId(),params.getReasonForAmend().getST()));
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.SubmitSafetyReportResponse submitSafetyReport(gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.SubmitSafetyReportRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.SubmitSafetyReportResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.SubmitSafetyReportResponse();
    boxedResult.setSafetyReportVersion(impl.submitSafetyReport(params.getSafetyReportIdentifier().getId(),params.getSubmitterIdentifier().getId(),params.getAdditionalRecipientIdentifiers().getDSET_II()));
    return boxedResult;
  }

    public gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.WithdrawSafetyReportResponse withdrawSafetyReport(gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.WithdrawSafetyReportRequest params) throws RemoteException {
    gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.WithdrawSafetyReportResponse boxedResult = new gov.nih.nci.ess.sr.service.safetyreporttransaction.stubs.WithdrawSafetyReportResponse();
    boxedResult.setSafetyReportVersion(impl.withdrawSafetyReport(params.getSafetyReportIdentifier().getId(),params.getWithdrawerIdentifier().getId()));
    return boxedResult;
  }

}
