package gov.nih.nci.cabig.caaers.grid.service.globus;

import gov.nih.nci.cabig.caaers.grid.service.ProtocolServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the ProtocolServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class ProtocolServiceProviderImpl{
	
	ProtocolServiceImpl impl;
	
	public ProtocolServiceProviderImpl() throws RemoteException {
		impl = new ProtocolServiceImpl();
	}
	

	public gov.nih.nci.cabig.caaers.grid.stubs.RegisterParticipantResponse registerParticipant(gov.nih.nci.cabig.caaers.grid.stubs.RegisterParticipantRequest params) throws RemoteException, gov.nih.nci.cabig.caaers.grid.stubs.types.InvalidRegistration, gov.nih.nci.cabig.caaers.grid.stubs.types.RegistrationError {
		ProtocolServiceAuthorization.authorizeRegisterParticipant();
		gov.nih.nci.cabig.caaers.grid.stubs.RegisterParticipantResponse boxedResult = new gov.nih.nci.cabig.caaers.grid.stubs.RegisterParticipantResponse();
		boxedResult.setIdentifier(impl.registerParticipant(params.getRegistration().getRegistration()));
		return boxedResult;
	}

}
