ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE;
ALTER TABLE CSM_PROTECTION_ELEMENT DROP CONSTRAINT  UQ_PE_OBJECT_ID_ATTRIBUTE_APP_ID;
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_URL VARCHAR(100);
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_USER_NAME VARCHAR(100);
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_PASSWORD VARCHAR(100);
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_DIALECT VARCHAR(100);
ALTER TABLE CSM_APPLICATION DROP COLUMN DATABASE_DRIVER VARCHAR(100);
