#!/bin/sh
# Developer shortcut script for doing mvn install in rules.  Set up so it can be run from any
# directory.  E.g.:
#
#  web$ ../rules/install
#
# Skips tests because 1) they burn your deploy database and 2) they don't pass.

cd `dirname $0`
mvn -o -Dmaven.test.skip=true clean install