<%@ include file="/WEB-INF/views/taglibs.jsp"%>
<page:applyDecorator name="standardNoHeader">
<html>
<head>
    <title>caAERS || Review Comments Listing</title>
    <tags:includeScriptaculous/>
    <tags:dwrJavascriptLink objects="createAE"/>
	<tags:dwrJavascriptLink objects="createStudy"/>
	<style type="text/css">
		#main{
			text-align: left;
		}
		.cmt {
			margin-left: 10px;
		}
		.standard-buttons{
			text-align: center;
		}
	</style>
</head>
<body>
	<tags:standardForm title="Comments">
		<jsp:attribute name="instructions">
			<tags:instructions code="instruction_wf_review_comments_listing"/>
		</jsp:attribute>
		<jsp:attribute name="singleFields">
			<ui:row path="comment">
				<jsp:attribute name="label">New comment</jsp:attribute>
				<jsp:attribute name="value">
					<ui:textarea path="comment" rows="6" cols="90" required="true">
					</ui:textarea>
				</jsp:attribute>
			</ui:row>
			<div class="content standard-buttons autoclear">
					<div class="standard-nav-buttons">
						<input type="reset" value="Clear" />&nbsp;&nbsp;
						<input type="submit" value="Save"/>
					</div>
			</div>
			<div class="eXtremeTable" >
				<c:forEach items="${command.previousComments}" var="comment" varStatus="cIndex">
					<div class="${cIndex.index % 2 gt 0 ? 'odd' : 'even' } autoclear cmt" >
						<c:set var="dt"><tags:formatDate value="${comment.createdDate}" /></c:set>
						<chrome:division title='${comment.autoGeneratedText } on ${dt }' collapsable="true" id="cmt${cIndex.index}" collapsed="${cIndex.index gt 0}">
						<pre>${comment.userComment}</pre>
						</chrome:division>
						
					</div>
				</c:forEach>
			</div>
		</jsp:attribute>
	</tags:standardForm>

</body>
</html>
</page:applyDecorator>  