package gov.nih.nci.ess.safetyreporting.rdm.service;

import gov.nih.nci.ess.safetyreporting.misc.SpringContextCreator;
import gov.nih.nci.ess.safetyreporting.rdm.common.SafetyReportDefinitionManagementI;
import gov.nih.nci.ess.safetyreporting.rdm.service.SafetyReportDefinitionManagementImplBase;

import java.rmi.RemoteException;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class SafetyReportDefinitionManagementImpl extends SafetyReportDefinitionManagementImplBase {

	private static final String BEAN_NAME = "safetyReportDefinitionManagementImpl";
	
	private SafetyReportDefinitionManagementI safetyReportDefinitionManagementI; 
	
	public SafetyReportDefinitionManagementImpl() throws RemoteException {
		super();
	}
	
	/**
	 * @throws BeansException
	 */
	private void initialize() throws BeansException {
		if (safetyReportDefinitionManagementI == null) {
			ApplicationContext ctx = SpringContextCreator.getApplicationContext();
			safetyReportDefinitionManagementI = (SafetyReportDefinitionManagementI) ctx.getBean(BEAN_NAME);
		}
	}
	
  public void createSafetyReportDefinition(gov.nih.nci.ess.safetyreporting.types.ReportDefinition reportDefinition) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
	  initialize();
	  safetyReportDefinitionManagementI.createSafetyReportDefinition(reportDefinition);
	  
  }

  public void updateSafetyReportDefinitionDetails(gov.nih.nci.ess.safetyreporting.types.ReportDefinition reportDefinition) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
	  initialize();
	  safetyReportDefinitionManagementI.updateSafetyReportDefinitionDeliveryDetails(reportDefinition);
  }

  public void updateSafetyReportDefinitionDeliveryDetails(gov.nih.nci.ess.safetyreporting.types.ReportDefinition reportDefinition) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
	  initialize();
	  safetyReportDefinitionManagementI.updateSafetyReportDefinitionDeliveryDetails(reportDefinition);
  }

  public void updateSafetyReportDefinitionMandatoryFields(gov.nih.nci.ess.safetyreporting.types.ReportDefinition reportDefinition) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
	  initialize();
	  safetyReportDefinitionManagementI.updateSafetyReportDefinitionMandatoryFields(reportDefinition);
  }

  public void deactivateSafetyReportDefinition(ess.caaers.nci.nih.gov.Id reportDefinitionId,_21090.org.iso.ST reasonForDeactivation) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
	  initialize();
	  safetyReportDefinitionManagementI.deactivateSafetyReportDefinition(reportDefinitionId, reasonForDeactivation);
  }

  public void updateSafetyReportTerminologyForStudy(ess.caaers.nci.nih.gov.Id reportDefinitionId,ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Id reportTerminologyId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

