package gov.nih.nci.ess.sr.service.safetyreporttransaction.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.4
 * 
 */
public class SafetyReportTransactionImpl extends SafetyReportTransactionImplBase {

	
	public SafetyReportTransactionImpl() throws RemoteException {
		super();
	}
	
  public sr.SafetyReportVersion amendSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,ess.caaers.nci.nih.gov.Id amendmentIdentifier,_21090.org.iso.ST reasonForAmend) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public sr.SafetyReportVersion submitSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,ess.caaers.nci.nih.gov.Id submitterIdentifier,_21090.org.iso.DSET_II additionalRecipientIdentifiers) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public sr.SafetyReportVersion withdrawSafetyReport(ess.caaers.nci.nih.gov.Id safetyReportIdentifier,ess.caaers.nci.nih.gov.Id withdrawerIdentifier) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

