
INSERT INTO task_configuration (select nextval('task_configuration_id_seq'), null, 0,'SUBMIT_TO_MEDICAL_MONITOR', true, 2, id,'The task "Submit Report To Medical Monitor" is assigned to you. Please use the link ${EXPEDITED_REPORT_LINK} to access the report.','Submit Report To Medical Monitor' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_assignees (select nextval('wf_assignees_id_seq'), null, 0, 'Central Office SAE Coordinator',9,currval('task_configuration_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_configs (select nextval('wf_transition_configs_id_seq'), 0, 'Send to Medical Monitor for Review',currval('task_configuration_id_seq') from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_owners (select nextval('wf_transition_owners_id_seq'), 0, 'Central Office SAE Coordinator',9,currval('wf_transition_configs_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');

INSERT INTO task_configuration (select nextval('task_configuration_id_seq'), null, 0,'MEDICAL_MONITOR_REVIEW', true, 4, id,'The task "Medical Monitor Review" is assigned to you. Please use the link ${EXPEDITED_REPORT_LINK} to access the report.','Medical Monitor Review' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_assignees (select nextval('wf_assignees_id_seq'), null, 0, 'Medical Monitor',11,currval('task_configuration_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_configs (select nextval('wf_transition_configs_id_seq'), 0, 'Approve Report',currval('task_configuration_id_seq') from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_owners (select nextval('wf_transition_owners_id_seq'), 0, 'Medical Monitor',11,currval('wf_transition_configs_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_configs (select nextval('wf_transition_configs_id_seq'), 0, 'Request Additional Information',currval('task_configuration_id_seq') from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_owners (select nextval('wf_transition_owners_id_seq'), 0, 'Medical Monitor',11,currval('wf_transition_configs_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');

INSERT INTO task_configuration (select nextval('task_configuration_id_seq'), null, 0,'MEDICAL_MONITOR_ADDITIONAL_INFO', true, 2, id,'The task "Provide Additional Information To Medical Monitor" is assigned to you. Please use the link ${EXPEDITED_REPORT_LINK} to access the report.','Provide Additional Information To Medical Monitor' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_assignees (select nextval('wf_assignees_id_seq'), null, 0, 'Central Office SAE Coordinator',9,currval('task_configuration_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_configs (select nextval('wf_transition_configs_id_seq'), 0,'Submit to Medical Monitor for Review',currval('task_configuration_id_seq') from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_owners (select nextval('wf_transition_owners_id_seq'), 0, 'Central Office SAE Coordinator',9,currval('wf_transition_configs_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');

INSERT INTO task_configuration (select nextval('task_configuration_id_seq'), null, 0,'COMPILE_COMMENTS', true, 2, id,'The task "Compile Comments" is assigned to you. Please use the link ${EXPEDITED_REPORT_LINK} to access the report.','Compile Comments' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_assignees (select nextval('wf_assignees_id_seq'), null, 0, 'Central Office SAE Coordinator',9,currval('task_configuration_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_configs (select nextval('wf_transition_configs_id_seq'), 0, 'Send feedback, comments and queries to CRA',currval('task_configuration_id_seq') from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_owners (select nextval('wf_transition_owners_id_seq'), 0, 'Central Office SAE Coordinator',9,currval('wf_transition_configs_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');

INSERT INTO task_configuration (select nextval('task_configuration_id_seq'), null, 0,'FINALIZE_REPORT_AND_SUBMIT', true, 1, id, 'The task "Finalize Report and Submit" is assigned to you. Please use the link ${EXPEDITED_REPORT_LINK} to access the report.','Finalize Report and Submit' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_assignees (select nextval('wf_assignees_id_seq'), null, 0, 'Reporter',7,currval('task_configuration_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_configs (select nextval('wf_transition_configs_id_seq'), 0, 'Submit report to External System',currval('task_configuration_id_seq') from workflow_configuration where workflow_definition_name like 'expedited_domestic');
INSERT INTO wf_transition_owners (select nextval('wf_transition_owners_id_seq'), 0, 'Reporter',7,currval('wf_transition_configs_id_seq'),'r' from workflow_configuration where workflow_definition_name like 'expedited_domestic');