package gov.nih.nci.ess.ae.service.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface AdverseEventEnterpriseServiceConstantsBase {
	public static final String SERVICE_NS = "http://service.ae.ess.nci.nih.gov/AdverseEventEnterpriseService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "AdverseEventEnterpriseServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "AdverseEventEnterpriseServiceResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
