package gov.nih.nci.ess.safetyreporting.rules.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.ess.safetyreporting.rules.stubs.SafetyReportRulesManagementPortType;
import gov.nih.nci.ess.safetyreporting.rules.stubs.service.SafetyReportRulesManagementServiceAddressingLocator;
import gov.nih.nci.ess.safetyreporting.rules.common.SafetyReportRulesManagementI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class SafetyReportRulesManagementClient extends SafetyReportRulesManagementClientBase implements SafetyReportRulesManagementI {	

	public SafetyReportRulesManagementClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public SafetyReportRulesManagementClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public SafetyReportRulesManagementClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public SafetyReportRulesManagementClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(SafetyReportRulesManagementClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  SafetyReportRulesManagementClient client = new SafetyReportRulesManagementClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public gov.nih.nci.ess.safetyreporting.types.ReportingRule createOrganizationSafetyReportingRules(gov.nih.nci.ess.safetyreporting.types.ReportingRule reportingRule,ess.caaers.nci.nih.gov.Id organizationId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"createOrganizationSafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateOrganizationSafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.CreateOrganizationSafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateOrganizationSafetyReportingRulesRequestReportingRule reportingRuleContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.CreateOrganizationSafetyReportingRulesRequestReportingRule();
    reportingRuleContainer.setReportingRule(reportingRule);
    params.setReportingRule(reportingRuleContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateOrganizationSafetyReportingRulesRequestOrganizationId organizationIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.CreateOrganizationSafetyReportingRulesRequestOrganizationId();
    organizationIdContainer.setId(organizationId);
    params.setOrganizationId(organizationIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateOrganizationSafetyReportingRulesResponse boxedResult = portType.createOrganizationSafetyReportingRules(params);
    return boxedResult.getReportingRule();
    }
  }

  public gov.nih.nci.ess.safetyreporting.types.ReportingRule updateOrganizationSafetyReportingRules(gov.nih.nci.ess.safetyreporting.types.ReportingRule reportingRule,ess.caaers.nci.nih.gov.Id organizationId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"updateOrganizationSafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateOrganizationSafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateOrganizationSafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateOrganizationSafetyReportingRulesRequestReportingRule reportingRuleContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateOrganizationSafetyReportingRulesRequestReportingRule();
    reportingRuleContainer.setReportingRule(reportingRule);
    params.setReportingRule(reportingRuleContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateOrganizationSafetyReportingRulesRequestOrganizationId organizationIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateOrganizationSafetyReportingRulesRequestOrganizationId();
    organizationIdContainer.setId(organizationId);
    params.setOrganizationId(organizationIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateOrganizationSafetyReportingRulesResponse boxedResult = portType.updateOrganizationSafetyReportingRules(params);
    return boxedResult.getReportingRule();
    }
  }

  public gov.nih.nci.ess.safetyreporting.types.ReportingRule deactivateOrganizationSafetyReportingRules(ess.caaers.nci.nih.gov.Id organizationId,_21090.org.iso.ST reasonForDeactivation) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"deactivateOrganizationSafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateOrganizationSafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateOrganizationSafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateOrganizationSafetyReportingRulesRequestOrganizationId organizationIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateOrganizationSafetyReportingRulesRequestOrganizationId();
    organizationIdContainer.setId(organizationId);
    params.setOrganizationId(organizationIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateOrganizationSafetyReportingRulesRequestReasonForDeactivation reasonForDeactivationContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateOrganizationSafetyReportingRulesRequestReasonForDeactivation();
    reasonForDeactivationContainer.setST(reasonForDeactivation);
    params.setReasonForDeactivation(reasonForDeactivationContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateOrganizationSafetyReportingRulesResponse boxedResult = portType.deactivateOrganizationSafetyReportingRules(params);
    return boxedResult.getReportingRule();
    }
  }

  public gov.nih.nci.ess.safetyreporting.types.ReportingRule createStudySafetyReportingRules(gov.nih.nci.ess.safetyreporting.types.ReportingRule reportingRule,ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Id organizationId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"createStudySafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequestReportingRule reportingRuleContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequestReportingRule();
    reportingRuleContainer.setReportingRule(reportingRule);
    params.setReportingRule(reportingRuleContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequestStudyId studyIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequestStudyId();
    studyIdContainer.setId(studyId);
    params.setStudyId(studyIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequestOrganizationId organizationIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesRequestOrganizationId();
    organizationIdContainer.setId(organizationId);
    params.setOrganizationId(organizationIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.CreateStudySafetyReportingRulesResponse boxedResult = portType.createStudySafetyReportingRules(params);
    return boxedResult.getReportingRule();
    }
  }

  public gov.nih.nci.ess.safetyreporting.types.ReportingRule updateStudySafetyReportingRules(gov.nih.nci.ess.safetyreporting.types.ReportingRule reportingRule,ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Id organizationId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"updateStudySafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequestReportingRule reportingRuleContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequestReportingRule();
    reportingRuleContainer.setReportingRule(reportingRule);
    params.setReportingRule(reportingRuleContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequestStudyId studyIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequestStudyId();
    studyIdContainer.setId(studyId);
    params.setStudyId(studyIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequestOrganizationId organizationIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesRequestOrganizationId();
    organizationIdContainer.setId(organizationId);
    params.setOrganizationId(organizationIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.UpdateStudySafetyReportingRulesResponse boxedResult = portType.updateStudySafetyReportingRules(params);
    return boxedResult.getReportingRule();
    }
  }

  public gov.nih.nci.ess.safetyreporting.types.ReportingRule deactivateStudySafetyReportingRules(ess.caaers.nci.nih.gov.Id studyId,ess.caaers.nci.nih.gov.Id organizationId,_21090.org.iso.ST reasonForDeactivation) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"deactivateStudySafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequestStudyId studyIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequestStudyId();
    studyIdContainer.setId(studyId);
    params.setStudyId(studyIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequestOrganizationId organizationIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequestOrganizationId();
    organizationIdContainer.setId(organizationId);
    params.setOrganizationId(organizationIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequestReasonForDeactivation reasonForDeactivationContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesRequestReasonForDeactivation();
    reasonForDeactivationContainer.setST(reasonForDeactivation);
    params.setReasonForDeactivation(reasonForDeactivationContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.DeactivateStudySafetyReportingRulesResponse boxedResult = portType.deactivateStudySafetyReportingRules(params);
    return boxedResult.getReportingRule();
    }
  }

  public void querySafetyReportingRules() throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"querySafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.QuerySafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.QuerySafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.QuerySafetyReportingRulesResponse boxedResult = portType.querySafetyReportingRules(params);
    }
  }

  public gov.nih.nci.ess.safetyreporting.types.ReportingRule getSafetyReportingRules(ess.caaers.nci.nih.gov.Id ruleId) throws RemoteException, gov.nih.nci.ess.safetyreporting.management.stubs.types.SafetyReportingServiceException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getSafetyReportingRules");
    gov.nih.nci.ess.safetyreporting.rules.stubs.GetSafetyReportingRulesRequest params = new gov.nih.nci.ess.safetyreporting.rules.stubs.GetSafetyReportingRulesRequest();
    gov.nih.nci.ess.safetyreporting.rules.stubs.GetSafetyReportingRulesRequestRuleId ruleIdContainer = new gov.nih.nci.ess.safetyreporting.rules.stubs.GetSafetyReportingRulesRequestRuleId();
    ruleIdContainer.setId(ruleId);
    params.setRuleId(ruleIdContainer);
    gov.nih.nci.ess.safetyreporting.rules.stubs.GetSafetyReportingRulesResponse boxedResult = portType.getSafetyReportingRules(params);
    return boxedResult.getReportingRule();
    }
  }

  public org.oasis.wsrf.lifetime.DestroyResponse destroy(org.oasis.wsrf.lifetime.Destroy params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"destroy");
    return portType.destroy(params);
    }
  }

  public org.oasis.wsrf.lifetime.SetTerminationTimeResponse setTerminationTime(org.oasis.wsrf.lifetime.SetTerminationTime params) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"setTerminationTime");
    return portType.setTerminationTime(params);
    }
  }

}
