package gov.nih.nci.cabig.caaers.grid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface StudyServiceI {

    public gov.nih.nci.cabig.caaers.grid.beans.StudyParticipantAssignment assignParticipant(gov.nih.nci.cabig.caaers.grid.beans.Study study,gov.nih.nci.cabig.caaers.grid.beans.Participant participant,gov.nih.nci.cabig.caaers.grid.beans.Site site) throws RemoteException ;

    public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

}

